project_id = "antaverse"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/sport/compte/", "http://localhost:3000/sport/compte/?recovery=1"]
minimum_password_length = 8

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.send-session-push]
verify_jwt = false
