const src = (id, title, publisher, url) => ({ id, title, publisher, url, isPrimarySource: true });
const AZA = src(
  "aza-animal-facts",
  "Animal fact sheets",
  "Association of Zoos and Aquariums",
  "https://www.aza.org/animal-fact-sheets",
);
const SI = src(
  "smithsonian-national-zoo",
  "Animals A–Z",
  "Smithsonian's National Zoo",
  "https://nationalzoo.si.edu/animals/list",
);
const NOAA = src(
  "noaa-ocean-species",
  "Ocean species and ecosystems",
  "National Oceanic and Atmospheric Administration",
  "https://www.fisheries.noaa.gov/find-species",
);
const IOC = src(
  "ioc-world-bird-list",
  "IOC World Bird List",
  "International Ornithologists' Union",
  "https://www.worldbirdnames.org/new/",
);
const AKC = src(
  "akc-dog-breeds",
  "Dog breeds A–Z",
  "American Kennel Club",
  "https://www.akc.org/dog-breeds/",
);
const CAT = src(
  "tica-cat-breeds",
  "Browse all breeds",
  "The International Cat Association",
  "https://tica.org/browse-all-breeds/",
);
const q = ([id, sub, d, title, text, answers, source = SI, rule]) => ({
  id,
  themeId: "animals",
  subthemeId: `animals:${sub}`,
  difficultyLevel: d,
  shortTitle: title,
  questionText: text,
  answers,
  sources: [source],
  qualificationRule:
    rule ??
    "Les neuf animaux correspondent exactement au groupe ou au critère explicite de la question.",
  explanation: "Noms français usuels, vérifiés dans la référence zoologique citée.",
});
export const questions = [
  q([
    "easy-grands-felins",
    "mammals",
    1,
    "Grands félins",
    "Quels sont neuf félins sauvages bien connus du genre Panthera ou proches communément appelés grands félins ?",
    [
      "Lion",
      "Tigre",
      "Jaguar",
      "Léopard",
      "Panthère des neiges",
      "Guépard",
      "Puma",
      "Lynx boréal",
      "Lynx roux",
    ],
    AZA,
  ]),
  q([
    "easy-mammiferes-marins",
    "marine-life",
    1,
    "Mammifères marins",
    "Quels sont neuf mammifères marins très connus ?",
    [
      "Baleine bleue",
      "Orque",
      "Grand dauphin",
      "Cachalot",
      "Béluga",
      "Narval",
      "Lamantin",
      "Dugong",
      "Morse",
    ],
    NOAA,
  ]),
  q([
    "easy-oiseaux-incapables-voler",
    "birds",
    1,
    "Oiseaux non volants",
    "Quels sont neuf oiseaux actuels incapables de voler ?",
    [
      "Autruche",
      "Émeu",
      "Casoar à casque",
      "Nandou d’Amérique",
      "Kiwi austral",
      "Manchot empereur",
      "Kakapo",
      "Takahé",
      "Cormoran aptère",
    ],
    IOC,
  ]),
  q([
    "easy-races-chiens-populaires",
    "domestic-animals",
    1,
    "Races de chiens",
    "Quelles sont neuf races de chiens très répandues reconnues par l’American Kennel Club ?",
    [
      "Labrador retriever",
      "Golden retriever",
      "Berger allemand",
      "Bouledogue français",
      "Caniche",
      "Beagle",
      "Rottweiler",
      "Teckel",
      "Boxer",
    ],
    AKC,
  ]),
  q([
    "easy-reptiles-connus",
    "reptiles-amphibians",
    1,
    "Reptiles connus",
    "Quels sont neuf reptiles actuels bien connus ?",
    [
      "Crocodile du Nil",
      "Alligator d’Amérique",
      "Dragon de Komodo",
      "Iguane vert",
      "Caméléon commun",
      "Python royal",
      "Cobra royal",
      "Tortue verte",
      "Gecko léopard",
    ],
    SI,
  ]),
  q([
    "easy-insectes-familiers",
    "insects",
    1,
    "Insectes familiers",
    "Quels sont neuf insectes très familiers du grand public ?",
    [
      "Abeille domestique",
      "Fourmi noire",
      "Coccinelle à sept points",
      "Papillon monarque",
      "Moustique tigre",
      "Mouche domestique",
      "Libellule déprimée",
      "Sauterelle verte",
      "Luciole commune",
    ],
    SI,
  ]),
  q([
    "easy-races-chats",
    "domestic-animals",
    1,
    "Races de chats",
    "Quelles sont neuf races de chats domestiques reconnues par la TICA ?",
    [
      "Siamois",
      "Persan",
      "Maine coon",
      "Bengal",
      "Sphynx",
      "Ragdoll",
      "British shorthair",
      "Abyssin",
      "Norvégien",
    ],
    CAT,
  ]),
  q([
    "medium-especes-ours",
    "mammals",
    2,
    "Huit ours et un Kodiak",
    "Quels sont les huit espèces actuelles d’ursidés, complétées par la sous-espèce dite ours kodiak ?",
    [
      "Ours brun",
      "Ours polaire",
      "Ours noir américain",
      "Ours kodiak",
      "Ours noir d’Asie",
      "Ours malais",
      "Ours lippu",
      "Ours à lunettes",
      "Panda géant",
    ],
    SI,
  ]),
  q([
    "medium-primates-anthropoides",
    "mammals",
    2,
    "Primates anthropoïdes",
    "Quels sont neuf primates anthropoïdes connus, humains exclus ?",
    [
      "Chimpanzé commun",
      "Bonobo",
      "Gorille de l’Ouest",
      "Gorille de l’Est",
      "Orang-outan de Bornéo",
      "Orang-outan de Sumatra",
      "Gibbon à mains blanches",
      "Siamang",
      "Macaque japonais",
    ],
    SI,
  ]),
  q([
    "medium-requins-emblematiques",
    "marine-life",
    2,
    "Requins emblématiques",
    "Quels sont neuf requins facilement distinguables par leur nom commun ?",
    [
      "Grand requin blanc",
      "Requin-baleine",
      "Requin-tigre",
      "Requin-marteau halicorne",
      "Requin mako",
      "Requin bouledogue",
      "Requin pèlerin",
      "Requin-renard commun",
      "Requin à pointes noires",
    ],
    NOAA,
  ]),
  q([
    "medium-rapaces-diurnes",
    "birds",
    2,
    "Rapaces diurnes",
    "Quels sont neuf rapaces diurnes présents en Europe ?",
    [
      "Aigle royal",
      "Pygargue à queue blanche",
      "Balbuzard pêcheur",
      "Faucon pèlerin",
      "Faucon crécerelle",
      "Buse variable",
      "Milan royal",
      "Épervier d’Europe",
      "Autour des palombes",
    ],
    IOC,
  ]),
  q([
    "medium-amphibiens-europe",
    "reptiles-amphibians",
    2,
    "Amphibiens d’Europe",
    "Quels sont neuf amphibiens présents en France métropolitaine ?",
    [
      "Salamandre",
      "Triton",
      "Crapaud",
      "Rainette",
      "Grenouille",
      "Sonneur",
      "Alyte",
      "Pélodyte",
      "Discoglosse",
    ],
    SI,
    "Le jeu accepte des noms communs de groupes d’amphibiens dont au moins une espèce est présente en France métropolitaine ; une espèce précise reste naturellement valide.",
  ]),
  q([
    "medium-insectes-sociaux",
    "insects",
    2,
    "Insectes sociaux",
    "Quels sont neuf insectes dont certaines espèces vivent en sociétés organisées ou en colonies ?",
    [
      "Abeille",
      "Bourdon",
      "Fourmi",
      "Termite",
      "Guêpe poliste",
      "Frelon",
      "Puceron",
      "Thrips",
      "Coléoptère ambroisie",
    ],
    SI,
  ]),
  q([
    "medium-races-chiens-bergers",
    "domestic-animals",
    2,
    "Chiens de berger",
    "Quelles sont neuf races de chiens de berger reconnues par l’American Kennel Club ?",
    [
      "Border collie",
      "Berger australien",
      "Berger allemand",
      "Berger belge malinois",
      "Colley à poil long",
      "Shetland",
      "Corgi gallois Pembroke",
      "Bouvier australien",
      "Berger des Pyrénées",
    ],
    AKC,
  ]),
  q([
    "hard-monotremes-marsupiaux",
    "mammals",
    3,
    "Mammifères singuliers",
    "Quels sont neuf mammifères actuels appartenant aux monotrèmes ou à des lignées marsupiales emblématiques ?",
    [
      "Ornithorynque",
      "Échidné à nez court",
      "Échidné de Bruijn",
      "Kangourou roux",
      "Koala",
      "Wombat commun",
      "Diable de Tasmanie",
      "Opossum de Virginie",
      "Numbat",
    ],
    SI,
  ]),
  q([
    "hard-oiseaux-endemiques-nouvelle-zelande",
    "birds",
    3,
    "Oiseaux néo-zélandais",
    "Quels sont neuf oiseaux endémiques emblématiques de Nouvelle-Zélande ?",
    [
      "Kiwi austral",
      "Kakapo",
      "Kéa",
      "Takahé",
      "Kokako bleu",
      "Tui cravate-frisée",
      "Hihi de Nouvelle-Zélande",
      "Mohoua à tête jaune",
      "Xénique grimpeur",
    ],
    IOC,
  ]),
  q([
    "hard-cephalopodes",
    "marine-life",
    3,
    "Céphalopodes",
    "Quels sont neuf céphalopodes actuels portant des noms communs distinctifs ?",
    [
      "Poulpe commun",
      "Poulpe géant du Pacifique",
      "Poulpe à anneaux bleus",
      "Calmar géant",
      "Calmar colossal",
      "Seiche commune",
      "Nautile flambé",
      "Spirule",
      "Vampire des abysses",
    ],
    NOAA,
  ]),
  q([
    "hard-crocodiliens",
    "reptiles-amphibians",
    3,
    "Crocodiliens",
    "Quels sont neuf crocodiliens actuels de genres ou espèces distincts ?",
    [
      "Crocodile du Nil",
      "Crocodile marin",
      "Crocodile américain",
      "Alligator d’Amérique",
      "Alligator de Chine",
      "Caïman à lunettes",
      "Caïman noir",
      "Gavial du Gange",
      "Faux-gavial de Malaisie",
    ],
    SI,
  ]),
  q([
    "hard-papillons-france",
    "insects",
    3,
    "Papillons de France",
    "Quels sont neuf papillons de jour remarquables présents en France métropolitaine ?",
    [
      "Machaon",
      "Flambé",
      "Apollon",
      "Citron",
      "Aurore",
      "Paon-du-jour",
      "Vulcain",
      "Belle-Dame",
      "Myrtil",
    ],
    SI,
  ]),
  q([
    "hard-races-chats-naturelles",
    "domestic-animals",
    3,
    "Races félines naturelles",
    "Quelles sont neuf races de chats considérées comme naturelles ou issues d’une population locale ?",
    [
      "Maine coon",
      "Norvégien",
      "Sibérien",
      "Manx",
      "Korat",
      "Mau égyptien",
      "Angora turc",
      "Van turc",
      "Bleu russe",
    ],
    CAT,
  ]),
];
