const source = (id, title, publisher, url, primary = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource: primary,
});
const q = (s) => ({
  themeId: "animation",
  qualificationRule:
    s.qualificationRule ??
    "Sont retenus les neuf films, épisodes, personnages ou lauréats exactement délimités dans la question.",
  explanation:
    s.explanation ?? "Le catalogue ou palmarès cité confirme cet ensemble de neuf réponses.",
  ...s,
});
export const questions = [
  q({
    id: "easy-disney-neuf-premiers-classiques",
    subthemeId: "animation:animated-films",
    difficultyLevel: 1,
    shortTitle: "Premiers classiques Disney",
    questionText: "Quels sont les neuf premiers longs-métrages du canon d’animation Disney ?",
    answers: [
      "Blanche-Neige et les Sept Nains",
      "Pinocchio",
      "Fantasia",
      "Dumbo",
      "Bambi",
      "Saludos Amigos",
      "Les Trois Caballeros",
      "La Boîte à musique",
      "Coquin de printemps",
    ],
    sources: [
      source(
        "disney-animated-films",
        "Walt Disney Animation Studios films",
        "Walt Disney Animation Studios",
        "https://www.disneyanimation.com/films/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-vice-versa-neuf-emotions",
    subthemeId: "animation:characters",
    difficultyLevel: 1,
    shortTitle: "Les émotions de Vice-Versa",
    questionText:
      "Quelles sont les neuf émotions installées à la console de Riley dans Vice-Versa et Vice-Versa 2 ?",
    answers: [
      "Joie",
      "Tristesse",
      "Colère",
      "Peur",
      "Dégoût",
      "Anxiété",
      "Envie",
      "Ennui",
      "Embarras",
    ],
    sources: [
      source(
        "pixar-inside-out-2",
        "Inside Out 2 — characters",
        "Pixar Animation Studios",
        "https://www.pixar.com/inside-out-2",
        true,
      ),
    ],
    exclusionNotes: "Nostalgie apparaît brièvement mais n’intègre pas durablement la console.",
  }),
  q({
    id: "easy-ghibli-neuf-premiers",
    subthemeId: "animation:studios",
    difficultyLevel: 1,
    shortTitle: "Premiers films Ghibli",
    questionText: "Quels sont les neuf premiers longs-métrages produits par le Studio Ghibli ?",
    answers: [
      "Le Château dans le ciel",
      "Le Tombeau des lucioles",
      "Mon voisin Totoro",
      "Kiki la petite sorcière",
      "Souvenirs goutte à goutte",
      "Porco Rosso",
      "Je peux entendre l’océan",
      "Pompoko",
      "Si tu tends l’oreille",
    ],
    sources: [
      source(
        "ghibli-works",
        "Studio Ghibli works",
        "Studio Ghibli",
        "https://www.ghibli.jp/works/",
        true,
      ),
    ],
    exclusionNotes: "Nausicaä est antérieur à la fondation officielle du studio.",
  }),
  q({
    id: "easy-dreamworks-neuf-premiers",
    subthemeId: "animation:studios",
    difficultyLevel: 1,
    shortTitle: "Premiers DreamWorks",
    questionText: "Quels sont les neuf premiers longs-métrages de DreamWorks Animation ?",
    answers: [
      "Fourmiz",
      "Le Prince d’Égypte",
      "La Route d’Eldorado",
      "Chicken Run",
      "Shrek",
      "Spirit, l’étalon des plaines",
      "Sinbad : La Légende des sept mers",
      "Shrek 2",
      "Gang de requins",
    ],
    sources: [
      source(
        "dreamworks-films",
        "Movies",
        "DreamWorks Animation",
        "https://www.dreamworks.com/movies",
        true,
      ),
    ],
  }),
  q({
    id: "easy-illumination-neuf-premiers",
    subthemeId: "animation:studios",
    difficultyLevel: 1,
    shortTitle: "Premiers Illumination",
    questionText: "Quels sont les neuf premiers longs-métrages produits par Illumination ?",
    answers: [
      "Moi, moche et méchant",
      "Hop",
      "Le Lorax",
      "Moi, moche et méchant 2",
      "Les Minions",
      "Comme des bêtes",
      "Tous en scène",
      "Moi, moche et méchant 3",
      "Le Grinch",
    ],
    sources: [
      source(
        "illumination-films",
        "Movies",
        "Illumination",
        "https://www.illumination.com/movies/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-blue-sky-neuf-premiers",
    subthemeId: "animation:studios",
    difficultyLevel: 1,
    shortTitle: "Premiers Blue Sky",
    questionText: "Quels sont les neuf premiers longs-métrages de Blue Sky Studios ?",
    answers: [
      "L’Âge de glace",
      "Robots",
      "L’Âge de glace 2",
      "Horton",
      "L’Âge de glace 3",
      "Rio",
      "L’Âge de glace 4",
      "Epic : La Bataille du royaume secret",
      "Rio 2",
    ],
    sources: [
      source(
        "blue-sky-films",
        "Blue Sky Studios filmography",
        "The Walt Disney Company",
        "https://thewaltdisneycompany.com/blue-sky-studios/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-princesses-neuf-films",
    subthemeId: "animation:characters",
    difficultyLevel: 1,
    shortTitle: "Films des princesses Disney",
    questionText:
      "Dans quels neuf films d’animation apparaissent pour la première fois Blanche-Neige, Cendrillon, Aurore, Ariel, Belle, Jasmine, Pocahontas, Mulan et Tiana ?",
    answers: [
      "Blanche-Neige et les Sept Nains",
      "Cendrillon",
      "La Belle au bois dormant",
      "La Petite Sirène",
      "La Belle et la Bête",
      "Aladdin",
      "Pocahontas, une légende indienne",
      "Mulan",
      "La Princesse et la Grenouille",
    ],
    sources: [
      source(
        "disney-princess",
        "Disney Princess characters",
        "Disney",
        "https://princess.disney.com/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-aardman-neuf-longs",
    subthemeId: "animation:studios",
    difficultyLevel: 2,
    shortTitle: "Longs-métrages Aardman",
    questionText:
      "Quels sont les neuf premiers longs-métrages produits ou coproduits par Aardman, de Chicken Run à Chicken Run 2 ?",
    answers: [
      "Chicken Run",
      "Wallace et Gromit : Le Mystère du lapin-garou",
      "Souris City",
      "Mission : Noël",
      "Les Pirates ! Bons à rien, mauvais en tout",
      "Shaun le mouton, le film",
      "Cro Man",
      "Shaun le mouton : La ferme contre-attaque",
      "Chicken Run : La Menace nuggets",
    ],
    sources: [
      source(
        "aardman-films",
        "Feature films",
        "Aardman Animations",
        "https://www.aardman.com/film-tv-games/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-don-bluth-neuf-premiers",
    subthemeId: "animation:animated-films",
    difficultyLevel: 2,
    shortTitle: "Films de Don Bluth",
    questionText: "Quels sont les neuf premiers longs-métrages réalisés par Don Bluth ?",
    answers: [
      "Brisby et le Secret de NIMH",
      "Fievel et le Nouveau Monde",
      "Le Petit Dinosaure et la Vallée des merveilles",
      "Charlie",
      "Rock-o-rico",
      "Poucelina",
      "Le Lutin magique",
      "Youbi, le petit pingouin",
      "Anastasia",
    ],
    sources: [
      source(
        "don-bluth-films",
        "Don Bluth filmography",
        "Internet Movie Database",
        "https://www.imdb.com/name/nm0089940/",
        false,
      ),
    ],
  }),
  q({
    id: "medium-futurama-neuf-premiers",
    subthemeId: "animation:animated-series",
    difficultyLevel: 2,
    shortTitle: "Débuts de Futurama",
    questionText: "Quels sont les neuf premiers épisodes de Futurama ?",
    answers: [
      "Spaciopilote 3000",
      "La Série débarque",
      "Le Colocataire",
      "Victime de l’amour, perdue dans l’espace",
      "Terreur sur la planète robot",
      "Cinquante Millions de dollars d’anchois",
      "Trois Soleils",
      "Un gros tas d’ordures",
      "L’Enfer, c’est les autres robots",
    ],
    sources: [
      source(
        "imdb-futurama",
        "Futurama — episodes",
        "Internet Movie Database",
        "https://www.imdb.com/title/tt0149460/episodes/?season=1",
        false,
      ),
    ],
  }),
  q({
    id: "medium-south-park-neuf-premiers",
    subthemeId: "animation:animated-series",
    difficultyLevel: 2,
    shortTitle: "Débuts de South Park",
    questionText: "Quels sont les neuf premiers épisodes de South Park ?",
    answers: [
      "Cartman a une sonde anale",
      "Muscle Plus 4000",
      "Volcano",
      "Une promenade complètement folle avec Al Super Gay",
      "Un éléphant fait l’amour à un cochon",
      "La Mort",
      "Conjonctivite",
      "Le Petit Éthernopien",
      "Monsieur Hankey, le petit caca Noël",
    ],
    sources: [
      source(
        "south-park-episodes",
        "Full episodes",
        "South Park Studios",
        "https://www.southparkstudios.com/seasons/south-park",
        true,
      ),
    ],
  }),
  q({
    id: "medium-rick-morty-neuf-premiers",
    subthemeId: "animation:animated-series",
    difficultyLevel: 2,
    shortTitle: "Débuts de Rick et Morty",
    questionText: "Quels sont les neuf premiers épisodes de Rick et Morty ?",
    answers: [
      "Pilote",
      "I, Croquette",
      "Anatomy Park",
      "M. Night Shaym-Aliens!",
      "La Boîte à larbins",
      "E-Rick-xir d’amour",
      "Gazorpazorp Junior",
      "Télé…visions",
      "La Petite Bou-Rick des horreurs",
    ],
    sources: [
      source(
        "adult-swim-rick",
        "Rick and Morty episodes",
        "Adult Swim",
        "https://www.adultswim.com/videos/rick-and-morty",
        true,
      ),
    ],
  }),
  q({
    id: "medium-spongebob-neuf-premiers",
    subthemeId: "animation:animated-series",
    difficultyLevel: 2,
    shortTitle: "Débuts de Bob l’éponge",
    questionText:
      "Quels sont les neuf premiers segments de Bob l’éponge dans l’ordre de diffusion ?",
    answers: [
      "Bienvenue à bord",
      "Le Grand Nettoyage",
      "Asphyxies en chaîne",
      "Les Bulles",
      "Pantalon déchiré",
      "Pêche aux méduses",
      "Le Plankton",
      "Les Voisins",
      "L’École de conduite",
    ],
    sources: [
      source(
        "nick-spongebob",
        "SpongeBob SquarePants episodes",
        "Nickelodeon",
        "https://www.nick.com/shows/spongebob-squarepants",
        true,
      ),
    ],
  }),
  q({
    id: "medium-oscar-animation-2002-2010",
    subthemeId: "animation:animated-films",
    difficultyLevel: 2,
    shortTitle: "Premiers Oscars d’animation",
    questionText:
      "Quels films ont remporté l’Oscar du meilleur film d’animation lors des cérémonies 2002 à 2010 ?",
    answers: [
      "Shrek",
      "Le Voyage de Chihiro",
      "Le Monde de Nemo",
      "Les Indestructibles",
      "Wallace et Gromit : Le Mystère du lapin-garou",
      "Happy Feet",
      "Ratatouille",
      "WALL-E",
      "Là-haut",
    ],
    sources: [
      source(
        "oscars-animation",
        "Animated Feature Film winners",
        "Academy of Motion Picture Arts and Sciences",
        "https://www.oscars.org/oscars/ceremonies",
        true,
      ),
    ],
  }),
  q({
    id: "hard-fleischer-superman-neuf-premiers",
    subthemeId: "animation:techniques",
    difficultyLevel: 3,
    shortTitle: "Superman des Fleischer",
    questionText:
      "Quels sont les neuf premiers courts métrages Superman produits par Fleischer Studios ?",
    answers: [
      "Superman",
      "The Mechanical Monsters",
      "Billion Dollar Limited",
      "The Arctic Giant",
      "The Bulleteers",
      "The Magnetic Telescope",
      "Electric Earthquake",
      "Volcano",
      "Terror on the Midway",
    ],
    sources: [
      source(
        "loc-superman-fleischer",
        "Fleischer Superman cartoons",
        "Library of Congress",
        "https://www.loc.gov/search/?q=Fleischer+Superman",
        false,
      ),
    ],
  }),
  q({
    id: "hard-tex-avery-mgm-neuf-premiers",
    subthemeId: "animation:techniques",
    difficultyLevel: 3,
    shortTitle: "Tex Avery chez MGM",
    questionText:
      "Quels sont les neuf premiers courts métrages réalisés par Tex Avery pour la MGM ?",
    answers: [
      "The Blitz Wolf",
      "The Early Bird Dood It!",
      "Dumb-Hounded",
      "Red Hot Riding Hood",
      "Who Killed Who?",
      "One Ham’s Family",
      "What’s Buzzin’ Buzzard?",
      "Screwball Squirrel",
      "Batty Baseball",
    ],
    sources: [
      source(
        "bfi-tex-avery",
        "Tex Avery filmography",
        "British Film Institute",
        "https://www.bfi.org.uk/films-tv-people/4ce2ba12bd91c",
        false,
      ),
    ],
  }),
  q({
    id: "hard-annecy-cristal-2014-2022",
    subthemeId: "animation:animated-films",
    difficultyLevel: 3,
    shortTitle: "Cristal d’Annecy",
    questionText:
      "Quels films ont reçu le Cristal du long métrage au Festival d’Annecy de 2014 à 2022 ?",
    answers: [
      "Le Garçon et le Monde",
      "Avril et le Monde truqué",
      "Ma vie de Courgette",
      "Lou et l’Île aux sirènes",
      "Funan",
      "J’ai perdu mon corps",
      "Calamity, une enfance de Martha Jane Cannary",
      "Flee",
      "Le Petit Nicolas : Qu’est-ce qu’on attend pour être heureux ?",
    ],
    sources: [
      source(
        "annecy-palmares",
        "Palmarès",
        "Festival international du film d’animation d’Annecy",
        "https://www.annecyfestival.com/le-festival/palmares",
        true,
      ),
    ],
  }),
  q({
    id: "hard-silly-symphonies-neuf-premieres",
    subthemeId: "animation:techniques",
    difficultyLevel: 3,
    shortTitle: "Premières Silly Symphonies",
    questionText:
      "Quelles sont les neuf premières Silly Symphonies de Disney dans l’ordre de sortie ?",
    answers: [
      "The Skeleton Dance",
      "El Terrible Toreador",
      "Springtime",
      "Hell’s Bells",
      "The Merry Dwarfs",
      "Summer",
      "Autumn",
      "Cannibal Capers",
      "Night",
    ],
    sources: [
      source(
        "d23-silly-symphonies",
        "Silly Symphonies",
        "D23 — The Official Disney Fan Club",
        "https://d23.com/a-to-z/silly-symphonies/",
        true,
      ),
    ],
  }),
  q({
    id: "hard-oscar-court-animation-neuf-premiers",
    subthemeId: "animation:animated-films",
    difficultyLevel: 3,
    shortTitle: "Premiers Oscars du court animé",
    questionText:
      "Quels films ont remporté les neuf premiers Oscars du meilleur court métrage d’animation, de 1932 à 1940 ?",
    answers: [
      "Des arbres et des fleurs",
      "Les Trois Petits Cochons",
      "Le Lièvre et la Tortue",
      "Trois Petits Orphelins",
      "Le Cousin de campagne",
      "Le Vieux Moulin",
      "Ferdinand le taureau",
      "Le Vilain Petit Canard",
      "The Milky Way",
    ],
    sources: [
      source(
        "oscars-short-animation",
        "Short Film (Animated) winners",
        "Academy of Motion Picture Arts and Sciences",
        "https://www.oscars.org/oscars/ceremonies",
        true,
      ),
    ],
  }),
  q({
    id: "hard-pixar-neuf-premiers-courts",
    subthemeId: "animation:techniques",
    difficultyLevel: 3,
    shortTitle: "Premiers courts Pixar",
    questionText:
      "Quels sont les neuf premiers courts métrages produits par Pixar, d’André et Wally B. à Saute-mouton ?",
    answers: [
      "Les Aventures d’André et Wally B.",
      "Luxo Jr.",
      "Le Rêve de Rouge",
      "Tin Toy",
      "Knick Knack",
      "Le Joueur d’échecs",
      "Drôles d’oiseaux sur une ligne à haute tension",
      "La Nouvelle Voiture de Bob",
      "Saute-mouton",
    ],
    sources: [
      source(
        "pixar-shorts",
        "Short films",
        "Pixar Animation Studios",
        "https://www.pixar.com/short-films",
        true,
      ),
    ],
  }),
];
