const source=(id,title,publisher,url,isPrimarySource=false)=>({id,title,publisher,url,isPrimarySource});
const WIPO=source("wipo-global-brand-db","Global Brand Database","World Intellectual Property Organization","https://branddb.wipo.int/",true);
const INTERBRAND=source("interbrand-global-brands","Best Global Brands","Interbrand","https://interbrand.com/best-global-brands/");
const COMPANIES=source("companiesmarketcap-brands-pack","Companies and brands directory","CompaniesMarketCap","https://companiesmarketcap.com/");
const BRITANNICA=source("britannica-companies-pack","Companies and brands","Encyclopaedia Britannica","https://www.britannica.com/topic/list-of-companies-2030040");
const q=spec=>({themeId:"brands-logos",qualificationRule:spec.qualificationRule??"Les neuf réponses correspondent aux marques ou entreprises indiquées.",explanation:spec.explanation??"La liste est vérifiée dans la base de marques ou la source d’entreprise citée.",...spec});
export const questions=[
q({id:"easy-marques-automobiles-pays",subthemeId:"brands-logos:companies",difficultyLevel:1,shortTitle:"Automobiles et pays",questionText:"De quels pays sont originaires Toyota, BMW, Ferrari, Volvo, Hyundai, Renault, Ford, Škoda et Tata Motors ?",answers:["Toyota — Japon","BMW — Allemagne","Ferrari — Italie","Volvo — Suède","Hyundai — Corée du Sud","Renault — France","Ford — États-Unis","Škoda — Tchéquie","Tata Motors — Inde"],sources:[BRITANNICA],qualificationRule:"Le pays d’origine, seul ou associé à la marque, est attendu dans l’ordre."}),
q({id:"easy-produits-entreprises-tech",subthemeId:"brands-logos:products",difficultyLevel:1,shortTitle:"Produits technologiques",questionText:"Quelles entreprises commercialisent l’iPhone, la PlayStation, la Xbox, le Galaxy, le Kindle, la Switch, le ThinkPad, la GoPro et la gamme Pixel ?",answers:["Apple","Sony","Microsoft","Samsung","Amazon","Nintendo","Lenovo","GoPro","Google"],sources:[WIPO]}),
q({id:"easy-logos-animaux",subthemeId:"brands-logos:logos",difficultyLevel:1,shortTitle:"Animaux dans les logos",questionText:"Quels animaux figurent dans les emblèmes de Ferrari, Peugeot, Lacoste, Puma, Jaguar, Lamborghini, Red Bull, Twitter historique et WWF ?",answers:["Cheval","Lion","Crocodile","Puma","Jaguar","Taureau","Deux taureaux","Oiseau","Panda"],sources:[WIPO]}),
q({id:"easy-marques-sport",subthemeId:"brands-logos:products",difficultyLevel:1,shortTitle:"Marques de sport",questionText:"Quelles sont ces neuf grandes marques d’équipements ou vêtements de sport ?",answers:["Nike","Adidas","Puma","Reebok","Under Armour","Asics","New Balance","Fila","Salomon"],sources:[INTERBRAND]}),
q({id:"easy-marques-alimentaires-produits",subthemeId:"brands-logos:food-brands",difficultyLevel:1,shortTitle:"Marques alimentaires",questionText:"Quels produits associe-t-on principalement à Nutella, Coca-Cola, Nespresso, Häagen-Dazs, Pringles, Tabasco, Evian, Barilla et Haribo ?",answers:["Pâte à tartiner","Soda au cola","Café en capsules","Crème glacée","Chips empilables","Sauce pimentée","Eau minérale","Pâtes alimentaires","Confiseries gélifiées"],sources:[WIPO]}),
q({id:"easy-maisons-luxe-pays",subthemeId:"brands-logos:luxury-fashion",difficultyLevel:1,shortTitle:"Maisons de luxe",questionText:"De quels pays sont originaires Chanel, Gucci, Hermès, Prada, Burberry, Rolex, Loewe, Louis Vuitton et Bulgari ?",answers:["Chanel — France","Gucci — Italie","Hermès — France","Prada — Italie","Burberry — Royaume-Uni","Rolex — Suisse","Loewe — Espagne","Louis Vuitton — France","Bulgari — Italie"],sources:[WIPO],qualificationRule:"Le pays d’origine, seul ou associé à la maison, est attendu pour chaque marque."}),
q({id:"easy-plateformes-societes-meres",subthemeId:"brands-logos:companies",difficultyLevel:1,shortTitle:"Plateformes et groupes",questionText:"À quels groupes appartiennent YouTube, Instagram, WhatsApp, LinkedIn, Twitch, GitHub, Waze, Pixar et LinkedIn Learning ?",answers:["YouTube — Alphabet","Instagram — Meta","WhatsApp — Meta","LinkedIn — Microsoft","Twitch — Amazon","GitHub — Microsoft","Waze — Alphabet","Pixar — Disney","LinkedIn Learning — Microsoft"],sources:[COMPANIES],qualificationRule:"Le groupe propriétaire, seul ou associé au service, est attendu; les réponses sont distinguées par service."}),

q({id:"medium-slogans-marques",subthemeId:"brands-logos:slogans",difficultyLevel:2,shortTitle:"Slogans célèbres",questionText:"Quelles marques utilisent ou ont utilisé « Just Do It », « I’m Lovin’ It », « Think Different », « Because You’re Worth It », « The Ultimate Driving Machine », « Have a Break », « Finger Lickin’ Good », « Impossible Is Nothing » et « Connecting People » ?",answers:["Nike","McDonald’s","Apple","L’Oréal Paris","BMW","KitKat","KFC","Adidas","Nokia"],sources:[WIPO]}),
q({id:"medium-fondateurs-marques-tech",subthemeId:"brands-logos:companies",difficultyLevel:2,shortTitle:"Fondateurs de la tech",questionText:"Quel fondateur ou duo fondateur associe-t-on à Microsoft, Apple, Google, Amazon, Meta, Dell, Huawei, Spotify et Airbnb ?",answers:["Bill Gates et Paul Allen","Steve Jobs, Steve Wozniak et Ronald Wayne","Larry Page et Sergey Brin","Jeff Bezos","Mark Zuckerberg","Michael Dell","Ren Zhengfei","Daniel Ek et Martin Lorentzon","Brian Chesky, Joe Gebbia et Nathan Blecharczyk"],sources:[BRITANNICA]}),
q({id:"medium-marques-groupes-automobiles",subthemeId:"brands-logos:companies",difficultyLevel:2,shortTitle:"Groupes automobiles",questionText:"À quels groupes appartiennent Audi, Peugeot, Dacia, Mini, Lexus, Infiniti, Škoda, Jeep et Volvo Cars ?",answers:["Audi — Volkswagen","Peugeot — Stellantis","Dacia — Renault","Mini — BMW","Lexus — Toyota","Infiniti — Nissan","Škoda — Volkswagen","Jeep — Stellantis","Volvo Cars — Geely"],sources:[COMPANIES],qualificationRule:"Le groupe, seul ou associé à la marque, est attendu pour chaque élément."}),
q({id:"medium-logos-formes-symboles",subthemeId:"brands-logos:logos",difficultyLevel:2,shortTitle:"Symboles de logos",questionText:"Quel symbole reconnaît-on dans les logos de Nike, Apple, Mercedes-Benz, Audi, Target, Shell, Mitsubishi, Airbnb et Bluetooth ?",answers:["Swoosh","Pomme croquée","Étoile à trois branches","Quatre anneaux","Cible","Coquille Saint-Jacques","Trois losanges","Bélo","Rune liée"],sources:[WIPO]}),
q({id:"medium-marques-anciens-noms",subthemeId:"brands-logos:companies",difficultyLevel:2,shortTitle:"Anciens noms d’entreprises",questionText:"Quels noms portaient auparavant Google, Nike, Pepsi, Sony, Amazon, eBay, Subway, LG et Nissan ?",answers:["BackRub","Blue Ribbon Sports","Brad’s Drink","Tokyo Tsushin Kogyo","Cadabra","AuctionWeb","Pete’s Super Submarines","Lucky-Goldstar","Datsun"],sources:[BRITANNICA]}),
q({id:"medium-parfums-maisons",subthemeId:"brands-logos:luxury-fashion",difficultyLevel:2,shortTitle:"Parfums et maisons",questionText:"Quelles maisons commercialisent N°5, J’adore, Shalimar, Opium, La Vie est Belle, Terre d’Hermès, Light Blue, Flowerbomb et Acqua di Giò ?",answers:["Chanel","Dior","Guerlain","Yves Saint Laurent","Lancôme","Hermès","Dolce & Gabbana","Viktor & Rolf","Giorgio Armani"],sources:[WIPO]}),
q({id:"medium-confiseries-groupes",subthemeId:"brands-logos:food-brands",difficultyLevel:2,shortTitle:"Confiseries et groupes",questionText:"Quels groupes produisent M&M’s, KitKat, Milka, Kinder, Haribo, Chupa Chups, Toblerone, Skittles et Tic Tac ?",answers:["M&M’s — Mars","KitKat — Nestlé","Milka — Mondelez","Kinder — Ferrero","Haribo — Haribo","Chupa Chups — Perfetti Van Melle","Toblerone — Mondelez","Skittles — Mars","Tic Tac — Ferrero"],sources:[WIPO]}),

q({id:"hard-createurs-logos",subthemeId:"brands-logos:logos",difficultyLevel:3,shortTitle:"Créateurs de logos",questionText:"Quels designers sont associés aux logos ou identités d’IBM, I Love New York, FedEx, Nike, Apple arc-en-ciel, Mobil, NeXT, Unilever 2004 et BP Helios ?",answers:["Paul Rand","Milton Glaser","Lindon Leader","Carolyn Davidson","Rob Janoff","Tom Geismar","Paul Rand pour NeXT","Miles Newlyn","Landor Associates"],sources:[WIPO]}),
q({id:"hard-symboles-blasons-automobiles",subthemeId:"brands-logos:logos",difficultyLevel:3,shortTitle:"Emblèmes automobiles",questionText:"Quels éléments figurent au centre ou dominent les emblèmes d’Alfa Romeo, Maserati, Porsche, Subaru, Abarth, Citroën, Renault, Saab et Opel ?",answers:["Croix et serpent","Trident","Cheval cabré","Pléiades","Scorpion","Doubles chevrons","Losange","Griffon","Éclair"],sources:[WIPO]}),
q({id:"hard-acronymes-marques",subthemeId:"brands-logos:companies",difficultyLevel:3,shortTitle:"Noms développés",questionText:"Que signifient les noms ou sigles IKEA, BMW, IBM, H&M, DHL, HSBC, LG historique, FIAT et ASICS ?",answers:["Ingvar Kamprad Elmtaryd Agunnaryd","Bayerische Motoren Werke","International Business Machines","Hennes & Mauritz","Dalsey Hillblom Lynn","Hongkong and Shanghai Banking Corporation","Lucky-Goldstar","Fabbrica Italiana Automobili Torino","Anima Sana In Corpore Sano"],sources:[BRITANNICA]}),
q({id:"hard-luxe-directeurs-fondateurs",subthemeId:"brands-logos:luxury-fashion",difficultyLevel:3,shortTitle:"Fondateurs de maisons",questionText:"Quels fondateurs ont donné leur nom à Balenciaga, Givenchy, Ferragamo, Versace, Armani, Saint Laurent, McQueen, Miyake et Rabanne ?",answers:["Cristóbal Balenciaga","Hubert de Givenchy","Salvatore Ferragamo","Gianni Versace","Giorgio Armani","Yves Saint Laurent","Alexander McQueen","Issey Miyake","Paco Rabanne"],sources:[BRITANNICA]}),
q({id:"hard-marques-annees-fondation",subthemeId:"brands-logos:companies",difficultyLevel:3,shortTitle:"Années de fondation",questionText:"En quelles années ont été fondées Nintendo, Coca-Cola, Michelin, Philips, Lego, Samsung, Sony, Nike et Microsoft ?",answers:["Nintendo — 1889","Coca-Cola — 1892","Michelin — 1889","Philips — 1891","Lego — 1932","Samsung — 1938","Sony — 1946","Nike — 1964","Microsoft — 1975"],sources:[BRITANNICA]}),
q({id:"hard-marques-alimentaires-origines",subthemeId:"brands-logos:food-brands",difficultyLevel:3,shortTitle:"Origines de marques alimentaires",questionText:"Dans quelles villes ou régions sont nées Guinness, Tabasco, Nutella, Häagen-Dazs, Nespresso, Barilla, Twinings, Lindt et Perrier ?",answers:["Dublin","Louisiane","Piémont","Bronx","Suisse","Parme","Londres","Zurich","Vergèze"],sources:[BRITANNICA]}),
];
