const source = (id, title, publisher, url, isPrimarySource = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});
const imdb = (id, person, code) =>
  source(
    id,
    `${person} — filmographie`,
    "Internet Movie Database",
    `https://www.imdb.com/name/${code}/`,
    false,
  );
const q = (spec) => ({
  themeId: "celebrities",
  qualificationRule:
    spec.qualificationRule ??
    "Sont retenues les neuf personnalités ou les neuf apparitions précisément délimitées dans la question.",
  explanation:
    spec.explanation ??
    "La filmographie ou le palmarès cité confirme cet ensemble de neuf réponses.",
  ...spec,
});
const oscars = source(
  "oscars-acting",
  "Acting winners",
  "Academy of Motion Picture Arts and Sciences",
  "https://www.oscars.org/oscars/ceremonies",
);
const cannes = source(
  "cannes-awards",
  "Retrospective and awards",
  "Festival de Cannes",
  "https://www.festival-cannes.com/en/retrospective/",
);
const venice = source(
  "venice-awards",
  "Recent years and awards",
  "La Biennale di Venezia",
  "https://www.labiennale.org/en/history/recent-years",
);

export const questions = [
  q({
    id: "easy-oscar-acteur-2015-2023",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Oscars du meilleur acteur",
    questionText:
      "Quels acteurs ont remporté l’Oscar du meilleur acteur lors des cérémonies 2015 à 2023 ?",
    answers: [
      "Eddie Redmayne",
      "Leonardo DiCaprio",
      "Casey Affleck",
      "Gary Oldman",
      "Rami Malek",
      "Joaquin Phoenix",
      "Anthony Hopkins",
      "Will Smith",
      "Brendan Fraser",
    ],
    sources: [oscars],
  }),
  q({
    id: "easy-oscar-actrice-2004-2012",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Oscars de la meilleure actrice",
    questionText:
      "Quelles actrices ont remporté l’Oscar de la meilleure actrice lors des cérémonies 2004 à 2012 ?",
    answers: [
      "Charlize Theron",
      "Hilary Swank",
      "Reese Witherspoon",
      "Helen Mirren",
      "Marion Cotillard",
      "Kate Winslet",
      "Sandra Bullock",
      "Natalie Portman",
      "Meryl Streep",
    ],
    sources: [oscars],
  }),
  q({
    id: "easy-emma-watson-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Emma Watson au cinéma",
    questionText:
      "Quels sont les neuf premiers longs-métrages d’Emma Watson, des huit Harry Potter à My Week with Marilyn ?",
    answers: [
      "Harry Potter à l’école des sorciers",
      "Harry Potter et la Chambre des secrets",
      "Harry Potter et le Prisonnier d’Azkaban",
      "Harry Potter et la Coupe de feu",
      "Harry Potter et l’Ordre du Phénix",
      "Harry Potter et le Prince de sang-mêlé",
      "Harry Potter et les Reliques de la Mort — partie 1",
      "Harry Potter et les Reliques de la Mort — partie 2",
      "My Week with Marilyn",
    ],
    sources: [imdb("imdb-emma-watson", "Emma Watson", "nm0914612")],
  }),
  q({
    id: "easy-daniel-radcliffe-neuf-films",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Daniel Radcliffe au cinéma",
    questionText:
      "Quels sont les huit films Harry Potter avec Daniel Radcliffe et son premier long-métrage suivant, La Dame en noir ?",
    answers: [
      "Harry Potter à l’école des sorciers",
      "Harry Potter et la Chambre des secrets",
      "Harry Potter et le Prisonnier d’Azkaban",
      "Harry Potter et la Coupe de feu",
      "Harry Potter et l’Ordre du Phénix",
      "Harry Potter et le Prince de sang-mêlé",
      "Harry Potter et les Reliques de la Mort — partie 1",
      "Harry Potter et les Reliques de la Mort — partie 2",
      "La Dame en noir",
    ],
    sources: [imdb("imdb-daniel-radcliffe", "Daniel Radcliffe", "nm0705356")],
    qualificationRule:
      "Sont retenus les huit longs-métrages Harry Potter puis le premier long-métrage de cinéma de l’acteur sorti après la saga.",
  }),
  q({
    id: "easy-tom-cruise-neuf-premiers",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 1,
    shortTitle: "Débuts de Tom Cruise",
    questionText:
      "Quels sont les neuf premiers longs-métrages avec Tom Cruise, d’Un amour infini à La Couleur de l’argent ?",
    answers: [
      "Un amour infini",
      "Taps",
      "Outsiders",
      "American Teenagers",
      "Risky Business",
      "L’Esprit d’équipe",
      "Legend",
      "Top Gun",
      "La Couleur de l’argent",
    ],
    sources: [imdb("imdb-tom-cruise", "Tom Cruise", "nm0000129")],
  }),
  q({
    id: "easy-will-smith-neuf-premiers",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 1,
    shortTitle: "Débuts de Will Smith",
    questionText:
      "Quels sont les neuf premiers longs-métrages en prises de vues réelles avec Will Smith ?",
    answers: [
      "Break Out",
      "Made in America",
      "Six degrés de séparation",
      "Bad Boys",
      "Independence Day",
      "Men in Black",
      "Ennemi d’État",
      "Wild Wild West",
      "La Légende de Bagger Vance",
    ],
    sources: [imdb("imdb-will-smith", "Will Smith", "nm0000226")],
    exclusionNotes: "Les productions uniquement vocales ou télévisées sont exclues.",
  }),
  q({
    id: "easy-jennifer-lawrence-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Débuts de Jennifer Lawrence",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Jennifer Lawrence, de Garden Party à Happiness Therapy ?",
    answers: [
      "Garden Party",
      "Loin de la terre brûlée",
      "Winter’s Bone",
      "Like Crazy",
      "Le Complexe du castor",
      "X-Men : Le Commencement",
      "Hunger Games",
      "La Maison au bout de la rue",
      "Happiness Therapy",
    ],
    sources: [imdb("imdb-jennifer-lawrence", "Jennifer Lawrence", "nm2225369")],
  }),

  q({
    id: "medium-tom-hanks-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Tom Hanks",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Tom Hanks, de Noces sanglantes à Dragnet ?",
    answers: [
      "Noces sanglantes",
      "Splash",
      "Le Palace en délire",
      "L’Homme à la chaussure rouge",
      "Toujours prêts",
      "Une baraque à tout casser",
      "Rien en commun",
      "Chaque fois que nous nous disons adieu",
      "Dragnet",
    ],
    sources: [imdb("imdb-tom-hanks", "Tom Hanks", "nm0000158")],
  }),
  q({
    id: "medium-dicaprio-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de DiCaprio",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Leonardo DiCaprio, de Critters 3 à Simples Secrets ?",
    answers: [
      "Critters 3",
      "Fleur de poison",
      "Blessures secrètes",
      "Gilbert Grape",
      "Mort ou vif",
      "Basketball Diaries",
      "Rimbaud Verlaine",
      "Roméo + Juliette",
      "Simples Secrets",
    ],
    sources: [imdb("imdb-dicaprio", "Leonardo DiCaprio", "nm0000138")],
  }),
  q({
    id: "medium-denzel-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Denzel Washington",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Denzel Washington, de Carbon Copy à Mo’ Better Blues ?",
    answers: [
      "Carbon Copy",
      "A Soldier’s Story",
      "Power",
      "Cry Freedom",
      "Pour la gloire",
      "The Mighty Quinn",
      "Glory",
      "Un ange de trop",
      "Mo’ Better Blues",
    ],
    sources: [imdb("imdb-denzel", "Denzel Washington", "nm0000243")],
  }),
  q({
    id: "medium-natalie-portman-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Natalie Portman",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Natalie Portman hors simple caméo, de Léon à Star Wars épisode II ?",
    answers: [
      "Léon",
      "Heat",
      "Beautiful Girls",
      "Tout le monde dit I love you",
      "Mars Attacks!",
      "Star Wars, épisode I : La Menace fantôme",
      "Ma mère, moi et ma mère",
      "Où le cœur nous mène",
      "Star Wars, épisode II : L’Attaque des clones",
    ],
    sources: [imdb("imdb-natalie-portman", "Natalie Portman", "nm0000204")],
    exclusionNotes: "Le bref caméo dans Zoolander est exclu.",
  }),
  q({
    id: "medium-meryl-streep-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Meryl Streep",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Meryl Streep, de Julia au Mystère Silkwood ?",
    answers: [
      "Julia",
      "Voyage au bout de l’enfer",
      "Manhattan",
      "La Vie privée d’un sénateur",
      "Kramer contre Kramer",
      "La Maîtresse du lieutenant français",
      "La Mort aux enchères",
      "Le Choix de Sophie",
      "Le Mystère Silkwood",
    ],
    sources: [imdb("imdb-meryl-streep", "Meryl Streep", "nm0000658")],
    qualificationRule:
      "Sont retenus ses neuf premiers longs-métrages de cinéma par ordre de sortie, jusqu’au Mystère Silkwood inclus.",
  }),
  q({
    id: "medium-scarlett-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Scarlett Johansson",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Scarlett Johansson, de L’Irrésistible North à Ghost World ?",
    answers: [
      "L’Irrésistible North",
      "Juste Cause",
      "If Lucy Fell",
      "Manny & Lo",
      "Fall",
      "Maman, je m’occupe des méchants !",
      "L’Homme qui murmurait à l’oreille des chevaux",
      "My Brother the Pig",
      "Ghost World",
    ],
    sources: [imdb("imdb-scarlett", "Scarlett Johansson", "nm0424060")],
  }),
  q({
    id: "medium-jean-dujardin-neuf-premiers",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Débuts de Jean Dujardin",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Jean Dujardin, de Si tous les gars du monde… à OSS 117 : Le Caire, nid d’espions ?",
    answers: [
      "Si tous les gars du monde…",
      "Bienvenue chez les Rozes",
      "Toutes les filles sont folles",
      "Le Convoyeur",
      "Mariages !",
      "Les Dalton",
      "Brice de Nice",
      "L’Amour aux trousses",
      "OSS 117 : Le Caire, nid d’espions",
    ],
    sources: [imdb("imdb-jean-dujardin", "Jean Dujardin", "nm0241121")],
  }),

  q({
    id: "hard-cannes-acteur-2011-2019",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 3,
    shortTitle: "Prix d’interprétation à Cannes",
    questionText:
      "Quels acteurs ont reçu le prix d’interprétation masculine à Cannes de 2011 à 2019 ?",
    answers: [
      "Jean Dujardin",
      "Mads Mikkelsen",
      "Bruce Dern",
      "Timothy Spall",
      "Vincent Lindon",
      "Shahab Hosseini",
      "Joaquin Phoenix",
      "Marcello Fonte",
      "Antonio Banderas",
    ],
    sources: [cannes],
  }),
  q({
    id: "hard-venise-acteur-2015-2023",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 3,
    shortTitle: "Coupe Volpi masculine",
    questionText: "Quels acteurs ont reçu la Coupe Volpi masculine à Venise de 2015 à 2023 ?",
    answers: [
      "Fabrice Luchini",
      "Óscar Martínez",
      "Kamel El Basha",
      "Willem Dafoe",
      "Luca Marinelli",
      "Pierfrancesco Favino",
      "John Arcilla",
      "Colin Farrell",
      "Peter Sarsgaard",
    ],
    sources: [venice],
  }),
  q({
    id: "hard-venise-actrice-2015-2023",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 3,
    shortTitle: "Coupe Volpi féminine",
    questionText: "Quelles actrices ont reçu la Coupe Volpi féminine à Venise de 2015 à 2023 ?",
    answers: [
      "Valeria Golino",
      "Emma Stone",
      "Charlotte Rampling",
      "Olivia Colman",
      "Ariane Ascaride",
      "Vanessa Kirby",
      "Penélope Cruz",
      "Cate Blanchett",
      "Cailee Spaeny",
    ],
    sources: [venice],
  }),
  q({
    id: "hard-nobel-litterature-2015-2023",
    subthemeId: "celebrities:public-figures",
    difficultyLevel: 3,
    shortTitle: "Nobel de littérature",
    questionText: "Quelles personnalités ont reçu le prix Nobel de littérature de 2015 à 2023 ?",
    answers: [
      "Svetlana Alexievitch",
      "Bob Dylan",
      "Kazuo Ishiguro",
      "Olga Tokarczuk",
      "Peter Handke",
      "Louise Glück",
      "Abdulrazak Gurnah",
      "Annie Ernaux",
      "Jon Fosse",
    ],
    sources: [
      source(
        "nobel-literature-laureates",
        "All Nobel Prizes in Literature",
        "Nobel Prize Outreach",
        "https://www.nobelprize.org/prizes/lists/all-nobel-prizes-in-literature/",
      ),
    ],
  }),
  q({
    id: "hard-time-person-2014-2022",
    subthemeId: "celebrities:media-figures",
    difficultyLevel: 3,
    shortTitle: "Personnalité de l’année",
    questionText:
      "Qui ou quel collectif le magazine Time a-t-il désigné Person of the Year de 2014 à 2022 ?",
    answers: [
      "Les combattants d’Ebola",
      "Angela Merkel",
      "Donald Trump",
      "The Silence Breakers",
      "The Guardians",
      "Greta Thunberg",
      "Joe Biden et Kamala Harris",
      "Elon Musk",
      "Volodymyr Zelensky et l’esprit de l’Ukraine",
    ],
    sources: [
      source(
        "time-person-year",
        "Person of the Year",
        "Time",
        "https://time.com/person-of-the-year/",
      ),
    ],
  }),
  q({
    id: "hard-cannes-palme-realisateurs-2011-2019",
    subthemeId: "celebrities:actors",
    difficultyLevel: 3,
    shortTitle: "Réalisateurs palmés",
    questionText:
      "Quels réalisateurs ont remporté la Palme d’or au Festival de Cannes de 2011 à 2019 ?",
    answers: [
      "Terrence Malick",
      "Michael Haneke",
      "Abdellatif Kechiche",
      "Nuri Bilge Ceylan",
      "Jacques Audiard",
      "Ken Loach",
      "Ruben Östlund",
      "Hirokazu Kore-eda",
      "Bong Joon-ho",
    ],
    sources: [cannes],
    qualificationRule:
      "Sont retenus les réalisateurs des neuf films lauréats de la Palme d’or entre 2011 et 2019.",
  }),
];
