const source = (id, title, publisher, url, isPrimarySource = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});

const SOURCES = {
  pixar: source(
    "pixar-films",
    "Feature Films",
    "Pixar Animation Studios",
    "https://www.pixar.com/feature-films/",
  ),
  fast: source(
    "fast-saga-films",
    "The Fast Saga",
    "Universal Pictures",
    "https://www.thefastsaga.com/",
  ),
  wizarding: source(
    "wizarding-world-films",
    "Discover the films",
    "Wizarding World",
    "https://www.wizardingworld.com/discover/films",
  ),
  rocky: source(
    "mgm-rocky",
    "Rocky franchise",
    "Metro-Goldwyn-Mayer",
    "https://www.mgm.com/franchise/rocky",
  ),
  apes: source(
    "fox-planet-apes",
    "Planet of the Apes",
    "20th Century Studios",
    "https://www.20thcenturystudios.com/franchise/planet-of-the-apes",
  ),
  marvel: source(
    "marvel-movies",
    "Marvel Movies",
    "Marvel Entertainment",
    "https://www.marvel.com/movies",
  ),
  wes: source(
    "bfi-wes-anderson",
    "Where to begin with Wes Anderson",
    "British Film Institute",
    "https://www.bfi.org.uk/features/where-begin-with-wes-anderson",
    false,
  ),
  fincher: source(
    "bfi-david-fincher",
    "Where to begin with David Fincher",
    "British Film Institute",
    "https://www.bfi.org.uk/features/where-begin-with-david-fincher",
    false,
  ),
  ghibli: source(
    "ghibli-works",
    "Studio Ghibli works",
    "Studio Ghibli",
    "https://www.ghibli.jp/works/",
  ),
  coen: source(
    "bfi-coen-brothers",
    "Where to begin with the Coen brothers",
    "British Film Institute",
    "https://www.bfi.org.uk/features/where-begin-with-coen-brothers",
    false,
  ),
  almodovar: source(
    "bfi-almodovar",
    "Where to begin with Pedro Almodóvar",
    "British Film Institute",
    "https://www.bfi.org.uk/features/where-begin-with-pedro-almodovar",
    false,
  ),
  tarantino: source(
    "bfi-tarantino",
    "Where to begin with Quentin Tarantino",
    "British Film Institute",
    "https://www.bfi.org.uk/features/where-begin-with-quentin-tarantino",
    false,
  ),
  kurosawa: source(
    "bfi-kurosawa",
    "Akira Kurosawa — films",
    "British Film Institute",
    "https://www.bfi.org.uk/people/akira-kurosawa",
    false,
  ),
  scorsese: source(
    "bfi-scorsese",
    "Martin Scorsese — films",
    "British Film Institute",
    "https://www.bfi.org.uk/people/martin-scorsese",
    false,
  ),
  cannes: source(
    "cannes-retrospective",
    "Retrospective and awards",
    "Festival de Cannes",
    "https://www.festival-cannes.com/en/retrospective/",
  ),
  venice: source(
    "venice-history",
    "Recent years and awards",
    "La Biennale di Venezia",
    "https://www.labiennale.org/en/history/recent-years",
  ),
  berlin: source(
    "berlinale-awards",
    "Awards and juries",
    "Berlinale",
    "https://www.berlinale.de/en/archive/awards-juries/awards.html",
  ),
};

const q = (spec) => ({
  themeId: "cinema",
  qualificationRule:
    spec.qualificationRule ??
    "Sont retenus les neuf films qui satisfont la franchise, la filmographie ou le palmarès exactement délimité dans la question.",
  explanation:
    spec.explanation ??
    "La source citée permet de contrôler les titres et la limite chronologique de cet ensemble de neuf films.",
  ...spec,
});

export const questions = [
  q({
    id: "easy-pixar-neuf-premiers",
    subthemeId: "cinema:films",
    difficultyLevel: 1,
    shortTitle: "Les débuts de Pixar",
    questionText: "Quels sont les neuf premiers longs-métrages sortis par Pixar ?",
    answers: [
      "Toy Story",
      { display: "1001 Pattes", aliases: ["A Bug’s Life"] },
      "Toy Story 2",
      { display: "Monstres & Cie", aliases: ["Monsters, Inc."] },
      { display: "Le Monde de Nemo", aliases: ["Finding Nemo"] },
      { display: "Les Indestructibles", aliases: ["The Incredibles"] },
      "Cars",
      "Ratatouille",
      "WALL-E",
    ],
    sources: [SOURCES.pixar],
  }),
  q({
    id: "easy-fast-saga-neuf-premiers",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "Fast Saga",
    questionText:
      "Quels sont les neuf premiers films principaux de la saga Fast & Furious, jusqu’à F9 ?",
    answers: [
      "Fast and Furious",
      "2 Fast 2 Furious",
      "Fast and Furious: Tokyo Drift",
      "Fast & Furious 4",
      "Fast Five",
      "Fast & Furious 6",
      "Fast & Furious 7",
      "Fast & Furious 8",
      "Fast & Furious 9",
    ],
    sources: [SOURCES.fast],
    exclusionNotes: "Le film dérivé Hobbs & Shaw n’appartient pas à la série principale numérotée.",
  }),
  q({
    id: "easy-wizarding-world-neuf-premiers",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "Monde des sorciers",
    questionText:
      "Quels sont les neuf premiers films du Wizarding World, des huit Harry Potter au premier Animaux fantastiques ?",
    answers: [
      "Harry Potter à l’école des sorciers",
      "Harry Potter et la Chambre des secrets",
      "Harry Potter et le Prisonnier d’Azkaban",
      "Harry Potter et la Coupe de feu",
      "Harry Potter et l’Ordre du Phénix",
      "Harry Potter et le Prince de sang-mêlé",
      "Harry Potter et les Reliques de la Mort — partie 1",
      "Harry Potter et les Reliques de la Mort — partie 2",
      "Les Animaux fantastiques",
    ],
    sources: [SOURCES.wizarding],
  }),
  q({
    id: "easy-rocky-creed-neuf-films",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "Rocky et Creed",
    questionText:
      "Quels sont les neuf films de la série Rocky et Creed sortis de Rocky à Creed III ?",
    answers: [
      "Rocky",
      "Rocky II",
      "Rocky III",
      "Rocky IV",
      "Rocky V",
      "Rocky Balboa",
      "Creed",
      "Creed II",
      "Creed III",
    ],
    sources: [SOURCES.rocky],
  }),
  q({
    id: "easy-planete-singes-neuf-canoniques",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "La Planète des singes",
    questionText:
      "Quels sont les neuf films des séries originale et moderne de La Planète des singes, jusqu’au Nouveau Royaume ?",
    answers: [
      "La Planète des singes",
      "Le Secret de la planète des singes",
      "Les Évadés de la planète des singes",
      "La Conquête de la planète des singes",
      "La Bataille de la planète des singes",
      "La Planète des singes : Les Origines",
      "La Planète des singes : L’Affrontement",
      "La Planète des singes : Suprématie",
      "La Planète des singes : Le Nouveau Royaume",
    ],
    sources: [SOURCES.apes],
    exclusionNotes:
      "Le remake indépendant réalisé par Tim Burton en 2001 est exclu des deux continuités visées.",
  }),
  q({
    id: "easy-mcu-neuf-premiers",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "Débuts du MCU",
    questionText:
      "Quels sont les neuf premiers films du Marvel Cinematic Universe, d’Iron Man à Captain America : Le Soldat de l’hiver ?",
    answers: [
      "Iron Man",
      "L’Incroyable Hulk",
      "Iron Man 2",
      "Thor",
      "Captain America: First Avenger",
      "Avengers",
      "Iron Man 3",
      "Thor : Le Monde des ténèbres",
      "Captain America : Le Soldat de l’hiver",
    ],
    sources: [SOURCES.marvel],
  }),
  q({
    id: "medium-wes-anderson-neuf-premiers",
    subthemeId: "cinema:directors",
    difficultyLevel: 2,
    shortTitle: "Wes Anderson",
    questionText:
      "Quels sont les neuf premiers longs-métrages réalisés par Wes Anderson, de Bottle Rocket à L’Île aux chiens ?",
    answers: [
      "Bottle Rocket",
      "Rushmore",
      "La Famille Tenenbaum",
      "La Vie aquatique",
      "À bord du Darjeeling Limited",
      "Fantastic Mr. Fox",
      "Moonrise Kingdom",
      "The Grand Budapest Hotel",
      "L’Île aux chiens",
    ],
    sources: [SOURCES.wes],
  }),
  q({
    id: "medium-david-fincher-neuf-premiers",
    subthemeId: "cinema:directors",
    difficultyLevel: 2,
    shortTitle: "David Fincher",
    questionText:
      "Quels sont les neuf premiers longs-métrages réalisés par David Fincher, d’Alien 3 à Gone Girl ?",
    answers: [
      "Alien 3",
      "Seven",
      "The Game",
      "Fight Club",
      "Panic Room",
      "Zodiac",
      "The Social Network",
      "Millénium : Les Hommes qui n’aimaient pas les femmes",
      "Gone Girl",
    ],
    sources: [SOURCES.fincher],
  }),
  q({
    id: "medium-miyazaki-neuf-premiers",
    subthemeId: "cinema:world-cinema",
    difficultyLevel: 2,
    shortTitle: "Hayao Miyazaki",
    questionText:
      "Quels sont les neuf premiers longs-métrages réalisés par Hayao Miyazaki, de Cagliostro au Château ambulant ?",
    answers: [
      "Le Château de Cagliostro",
      "Nausicaä de la Vallée du Vent",
      "Le Château dans le ciel",
      "Mon voisin Totoro",
      "Kiki la petite sorcière",
      "Porco Rosso",
      "Princesse Mononoké",
      "Le Voyage de Chihiro",
      "Le Château ambulant",
    ],
    sources: [SOURCES.ghibli],
  }),
  q({
    id: "medium-coen-neuf-premiers",
    subthemeId: "cinema:directors",
    difficultyLevel: 2,
    shortTitle: "Frères Coen",
    questionText:
      "Quels sont les neuf premiers longs-métrages réalisés par les frères Coen, de Sang pour sang à The Barber ?",
    answers: [
      "Sang pour sang",
      "Arizona Junior",
      "Miller’s Crossing",
      "Barton Fink",
      "Le Grand Saut",
      "Fargo",
      "The Big Lebowski",
      "O’Brother",
      "The Barber",
    ],
    sources: [SOURCES.coen],
  }),
  q({
    id: "medium-almodovar-neuf-premiers",
    subthemeId: "cinema:world-cinema",
    difficultyLevel: 2,
    shortTitle: "Pedro Almodóvar",
    questionText:
      "Quels sont les neuf premiers longs-métrages de Pedro Almodóvar, de Pepi, Luci, Bom à Talons aiguilles ?",
    answers: [
      "Pepi, Luci, Bom et autres filles du quartier",
      "Le Labyrinthe des passions",
      "Dans les ténèbres",
      "Qu’est-ce que j’ai fait pour mériter ça ?",
      "Matador",
      "La Loi du désir",
      "Femmes au bord de la crise de nerfs",
      "Attache-moi !",
      "Talons aiguilles",
    ],
    sources: [SOURCES.almodovar],
  }),
  q({
    id: "medium-tarantino-neuf-jusqua-hateful-eight",
    subthemeId: "cinema:directors",
    difficultyLevel: 2,
    shortTitle: "Quentin Tarantino",
    questionText:
      "Quels sont les neuf longs-métrages réalisés par Quentin Tarantino de Reservoir Dogs aux Huit Salopards, en comptant séparément les deux Kill Bill ?",
    answers: [
      "Reservoir Dogs",
      "Pulp Fiction",
      "Jackie Brown",
      "Kill Bill : Volume 1",
      "Kill Bill : Volume 2",
      "Boulevard de la mort",
      "Inglourious Basterds",
      "Django Unchained",
      "Les Huit Salopards",
    ],
    sources: [SOURCES.tarantino],
  }),
  q({
    id: "hard-kurosawa-neuf-premiers",
    subthemeId: "cinema:world-cinema",
    difficultyLevel: 3,
    shortTitle: "Akira Kurosawa",
    questionText:
      "Quels sont les neuf premiers longs-métrages réalisés par Akira Kurosawa, de La Légende du grand judo à Chien enragé ?",
    answers: [
      "La Légende du grand judo",
      "Le Plus Beau",
      "La Nouvelle Légende du grand judo",
      "Les Hommes qui marchèrent sur la queue du tigre",
      "Je ne regrette rien de ma jeunesse",
      "Un merveilleux dimanche",
      "L’Ange ivre",
      "Le Duel silencieux",
      "Chien enragé",
    ],
    sources: [SOURCES.kurosawa],
  }),
  q({
    id: "hard-scorsese-neuf-premiers-fictions",
    subthemeId: "cinema:directors",
    difficultyLevel: 3,
    shortTitle: "Martin Scorsese",
    questionText:
      "Quels sont les neuf premiers longs-métrages de fiction réalisés par Martin Scorsese, de Who’s That Knocking at My Door à After Hours ?",
    answers: [
      "Who’s That Knocking at My Door",
      "Bertha Boxcar",
      "Mean Streets",
      "Alice n’est plus ici",
      "Taxi Driver",
      "New York, New York",
      "Raging Bull",
      "La Valse des pantins",
      "After Hours",
    ],
    sources: [SOURCES.scorsese],
    exclusionNotes:
      "Les documentaires et films de concert sont exclus de cette filmographie de fiction.",
  }),
  q({
    id: "hard-palmes-or-2014-2023",
    subthemeId: "cinema:awards",
    difficultyLevel: 3,
    shortTitle: "Palmes d’or récentes",
    questionText:
      "Quels sont les neuf films ayant reçu la Palme d’or entre 2014 et 2023, aucune édition n’ayant eu lieu en 2020 ?",
    answers: [
      "Winter Sleep",
      "Dheepan",
      "Moi, Daniel Blake",
      "The Square",
      "Une affaire de famille",
      "Parasite",
      "Titane",
      "Sans filtre",
      "Anatomie d’une chute",
    ],
    sources: [SOURCES.cannes],
    qualificationRule:
      "Sont retenus les neuf lauréats de la Palme d’or des éditions 2014 à 2019 puis 2021 à 2023.",
  }),
  q({
    id: "hard-lions-or-2015-2023",
    subthemeId: "cinema:awards",
    difficultyLevel: 3,
    shortTitle: "Lions d’or",
    questionText:
      "Quels films ont remporté le Lion d’or à la Mostra de Venise de 2015 à 2023 inclus ?",
    answers: [
      "Desde allá",
      "The Woman Who Left",
      "La Forme de l’eau",
      "Roma",
      "Joker",
      "Nomadland",
      "L’Événement",
      "Toute la beauté et le sang versé",
      "Pauvres Créatures",
    ],
    sources: [SOURCES.venice],
  }),
  q({
    id: "hard-ours-or-2015-2023",
    subthemeId: "cinema:awards",
    difficultyLevel: 3,
    shortTitle: "Ours d’or",
    questionText: "Quels films ont remporté l’Ours d’or à la Berlinale de 2015 à 2023 inclus ?",
    answers: [
      "Taxi Téhéran",
      "Fuocoammare",
      "Corps et Âme",
      "Touch Me Not",
      "Synonymes",
      "Le Diable n’existe pas",
      "Bad Luck Banging or Loony Porn",
      "Nos soleils",
      "Sur l’Adamant",
    ],
    sources: [SOURCES.berlin],
  }),
];
