const source=(id,title,publisher,url,primary=true)=>({id,title,publisher,url,isPrimarySource:primary});
const q=(s)=>({themeId:"comics-manga",qualificationRule:s.qualificationRule??"Sont retenus les neuf personnages, albums ou arcs exactement délimités dans la question.",explanation:s.explanation??"La série ou le catalogue cité confirme cet ensemble de neuf réponses.",...s});
export const questions=[
q({id:"easy-one-piece-neuf-mugiwara",subthemeId:"comics-manga:characters",difficultyLevel:1,shortTitle:"L’équipage au chapeau de paille",questionText:"Quels sont les neuf premiers membres de l’équipage de Luffy dans One Piece, jusqu’à Brook ?",answers:["Monkey D. Luffy","Roronoa Zoro","Nami","Usopp","Sanji","Tony-Tony Chopper","Nico Robin","Franky","Brook"],sources:[source("one-piece-characters","Characters","ONE PIECE official website","https://one-piece.com/character/",true)]}),
q({id:"easy-asterix-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:1,shortTitle:"Les débuts d’Astérix",questionText:"Quels sont les neuf premiers albums d’Astérix dans l’ordre de publication ?",answers:["Astérix le Gaulois","La Serpe d’or","Astérix et les Goths","Astérix gladiateur","Le Tour de Gaule d’Astérix","Astérix et Cléopâtre","Le Combat des chefs","Astérix chez les Bretons","Astérix et les Normands"],sources:[source("asterix-albums","Tous les albums","Les Éditions Albert René","https://asterix.com/albums/",true)]}),
q({id:"easy-tintin-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:1,shortTitle:"Les débuts de Tintin",questionText:"Quels sont les neuf premiers albums des Aventures de Tintin dans l’ordre de publication ?",answers:["Tintin au pays des Soviets","Tintin au Congo","Tintin en Amérique","Les Cigares du pharaon","Le Lotus bleu","L’Oreille cassée","L’Île Noire","Le Sceptre d’Ottokar","Le Crabe aux pinces d’or"],sources:[source("tintin-albums","Les albums de Tintin","Tintinimaginatio","https://www.tintin.com/fr/albums",true)]}),
q({id:"easy-lucky-luke-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:1,shortTitle:"Les débuts de Lucky Luke",questionText:"Quels sont les neuf premiers albums de Lucky Luke dans la collection historique Dupuis ?",answers:["La Mine d’or de Dick Digger","Rodéo","Arizona","Sous le ciel de l’Ouest","Lucky Luke contre Pat Poker","Hors-la-loi","L’Élixir du docteur Doxey","Phil Defer","Des rails sur la prairie"],sources:[source("lucky-luke-albums","Les albums de Lucky Luke","Lucky Comics","https://www.lucky-luke.com/albums/",true)]}),
q({id:"easy-schtroumpfs-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:1,shortTitle:"Les débuts des Schtroumpfs",questionText:"Quels sont les neuf premiers albums de la série Les Schtroumpfs ?",answers:["Les Schtroumpfs noirs","Le Schtroumpfissime","La Schtroumpfette","L’Œuf et les Schtroumpfs","Les Schtroumpfs et le Cracoucass","Le Cosmoschtroumpf","L’Apprenti Schtroumpf","Histoires de Schtroumpfs","Schtroumpf vert et vert Schtroumpf"],sources:[source("smurfs-books","Albums","Peyo Company","https://www.smurf.com/en/books",true)]}),
q({id:"easy-sailor-neuf-guerrieres",subthemeId:"comics-manga:manga",difficultyLevel:1,shortTitle:"Les guerrières Sailor",questionText:"Quelles sont les neuf guerrières Sailor du système solaire autres que Sailor Moon ?",answers:["Sailor Mercury","Sailor Mars","Sailor Jupiter","Sailor Venus","Sailor Uranus","Sailor Neptune","Sailor Pluto","Sailor Saturn","Sailor Chibi Moon"],sources:[source("sailor-moon-characters","Sailor Moon characters","Kodansha","https://kodansha.us/series/sailor-moon/",true)]}),
q({id:"easy-avengers-neuf-premiers-membres",subthemeId:"comics-manga:superheroes",difficultyLevel:1,shortTitle:"Premiers Avengers",questionText:"Quels sont les neuf premiers héros à rejoindre les Avengers dans les comics Marvel ?",answers:["Iron Man","Thor","Hulk","Wasp","Ant-Man","Captain America","Hawkeye","Quicksilver","Scarlet Witch"],sources:[source("marvel-avengers","Avengers — team history","Marvel","https://www.marvel.com/teams-and-groups/avengers",true)]}),
q({id:"medium-naruto-neuf-jinchuriki",subthemeId:"comics-manga:manga",difficultyLevel:2,shortTitle:"Les neuf jinchūriki",questionText:"Quels sont les neuf jinchūriki associés aux démons à queues de un à neuf dans Naruto ?",answers:["Gaara","Yugito Nii","Yagura Karatachi","Rōshi","Han","Utakata","Fū","Killer B","Naruto Uzumaki"],sources:[source("naruto-characters","Naruto character profiles","Shueisha","https://naruto-official.com/en/",true)]}),
q({id:"medium-attaque-titans-neuf-titans",subthemeId:"comics-manga:manga",difficultyLevel:2,shortTitle:"Les neuf Titans",questionText:"Quels sont les neuf Titans primordiaux dans L’Attaque des Titans ?",answers:["Titan Originel","Titan Assaillant","Titan Colossal","Titan Cuirassé","Titan Féminin","Titan Bestial","Titan Mâchoire","Titan Charrette","Titan Marteau d’armes"],sources:[source("aot-nine-titans","Attack on Titan guide","Kodansha","https://kodansha.us/series/attack-on-titan/",true)]}),
q({id:"medium-sandman-neuf-premiers-volumes",subthemeId:"comics-manga:publishers",difficultyLevel:2,shortTitle:"The Sandman",questionText:"Quels sont les neuf premiers recueils de la série The Sandman de Neil Gaiman ?",answers:["Préludes et Nocturnes","La Maison de poupée","Domaine du rêve","La Saison des brumes","Jouons à être toi","Fables et Réflexions","Vies brèves","Au bout des mondes","Les Bienveillantes"],sources:[source("dc-sandman","The Sandman books","DC Comics","https://www.dc.com/graphic-novels/the-sandman",true)]}),
q({id:"medium-walking-dead-neuf-premiers",subthemeId:"comics-manga:publishers",difficultyLevel:2,shortTitle:"The Walking Dead",questionText:"Quels sont les neuf premiers recueils de comics The Walking Dead ?",answers:["Passé décomposé","Cette vie derrière nous","Sains et saufs ?","Amour et Mort","Monstrueux","Vengeance","Dans l’œil du cyclone","Une vie de souffrance","Ceux qui restent"],sources:[source("image-walking-dead","The Walking Dead collections","Image Comics","https://imagecomics.com/comics/series/the-walking-dead",true)]}),
q({id:"medium-blake-mortimer-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:2,shortTitle:"Blake et Mortimer",questionText:"Quels sont les neuf premiers albums de Blake et Mortimer dans l’ordre de la collection ?",answers:["Le Secret de l’Espadon — tome 1","Le Secret de l’Espadon — tome 2","Le Mystère de la Grande Pyramide — tome 1","Le Mystère de la Grande Pyramide — tome 2","La Marque jaune","L’Énigme de l’Atlantide","S.O.S. Météores","Le Piège diabolique","L’Affaire du collier"],sources:[source("blake-mortimer-albums","Les albums","Éditions Blake et Mortimer","https://www.blakeetmortimer.com/albums/",true)]}),
q({id:"medium-one-piece-neuf-premiers-arcs",subthemeId:"comics-manga:manga",difficultyLevel:2,shortTitle:"Premiers arcs de One Piece",questionText:"Quels sont les neuf premiers arcs narratifs du manga One Piece, de Romance Dawn à Little Garden ?",answers:["Romance Dawn","Orange Town","Village de Sirop","Baratie","Arlong Park","Loguetown","Reverse Mountain","Whiskey Peak","Little Garden"],sources:[source("one-piece-story","Story arcs","ONE PIECE official website","https://one-piece.com/comics/",true)]}),
q({id:"medium-dragon-ball-neuf-premiers-arcs",subthemeId:"comics-manga:manga",difficultyLevel:2,shortTitle:"Les arcs de Dragon Ball",questionText:"Quels sont les neuf premiers grands arcs du manga Dragon Ball, de Pilaf à Freezer ?",answers:["Empereur Pilaf","21e Tenkaichi Budokai","Armée du Ruban Rouge","Baba la voyante","22e Tenkaichi Budokai","Roi Piccolo","23e Tenkaichi Budokai","Saiyans","Freezer"],sources:[source("dragon-ball-manga","Dragon Ball manga","Shueisha","https://dragon-ball-official.com/",true)]}),
q({id:"hard-thorgal-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:3,shortTitle:"Les débuts de Thorgal",questionText:"Quels sont les neuf premiers albums de Thorgal ?",answers:["La Magicienne trahie","L’Île des mers gelées","Les Trois Vieillards du pays d’Aran","La Galère noire","Au-delà des ombres","La Chute de Brek Zarith","L’Enfant des étoiles","Alinoë","Les Archers"],sources:[source("thorgal-albums","Les albums de Thorgal","Le Lombard","https://www.lelombard.com/bd/thorgal",true)]}),
q({id:"hard-blueberry-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:3,shortTitle:"Les débuts de Blueberry",questionText:"Quels sont les neuf premiers albums de la série Blueberry ?",answers:["Fort Navajo","Tonnerre à l’Ouest","L’Aigle solitaire","Le Cavalier perdu","La Piste des Navajos","L’Homme à l’étoile d’argent","Le Cheval de fer","L’Homme au poing d’acier","La Piste des Sioux"],sources:[source("blueberry-albums","Blueberry — albums","Dargaud","https://www.dargaud.com/bd/blueberry",true)]}),
q({id:"hard-valerian-neuf-premiers",subthemeId:"comics-manga:franco-belgian-comics",difficultyLevel:3,shortTitle:"Les débuts de Valérian",questionText:"Quels sont les neuf premiers albums de Valérian et Laureline ?",answers:["La Cité des eaux mouvantes","L’Empire des mille planètes","Le Pays sans étoile","Bienvenue sur Alflolol","Les Oiseaux du Maître","L’Ambassadeur des Ombres","Sur les terres truquées","Les Héros de l’équinoxe","Métro Châtelet, direction Cassiopée"],sources:[source("valerian-albums","Valérian — albums","Dargaud","https://www.dargaud.com/bd/valerian",true)]}),
q({id:"hard-spirou-franquin-neuf-premiers",subthemeId:"comics-manga:authors-artists",difficultyLevel:3,shortTitle:"Spirou par Franquin",questionText:"Quels sont les neuf premiers albums de Spirou et Fantasio dessinés par André Franquin ?",answers:["Quatre aventures de Spirou et Fantasio","Il y a un sorcier à Champignac","Les Chapeaux noirs","Spirou et les Héritiers","Les Voleurs du Marsupilami","La Corne de rhinocéros","Le Dictateur et le Champignon","La Mauvaise Tête","Le Repaire de la murène"],sources:[source("dupuis-spirou","Spirou et Fantasio — albums","Éditions Dupuis","https://www.dupuis.com/seriebd/spirou-et-fantasio/88",true)]}),
q({id:"hard-corto-neuf-premiers",subthemeId:"comics-manga:authors-artists",difficultyLevel:3,shortTitle:"Les débuts de Corto Maltese",questionText:"Quels sont les neuf premiers albums de Corto Maltese dans l’ordre de parution français ?",answers:["La Ballade de la mer salée","Sous le signe du Capricorne","Corto toujours un peu plus loin","Les Celtiques","Les Éthiopiques","Corto Maltese en Sibérie","Fable de Venise","La Maison dorée de Samarkand","La Jeunesse"],sources:[source("corto-albums","Les aventures de Corto Maltese","Casterman","https://www.casterman.com/Bande-dessinee/Collections-series/corto-maltese",true)]}),
q({id:"hard-angouleme-fauve-2015-2023",subthemeId:"comics-manga:authors-artists",difficultyLevel:3,shortTitle:"Fauves d’or récents",questionText:"Quels albums ont reçu le Fauve d’or à Angoulême de 2015 à 2023 ?",answers:["L’Arabe du futur","Ici","Paysage après la bataille","La Saga de Grimr","Moi, ce que j’aime, c’est les monstres","Révolution — Liberté","L’Accident de chasse","Écoute, jolie Márcia","La Couleur des choses"],sources:[source("fibd-palmares","Palmarès du Festival","Festival international de la bande dessinée d’Angoulême","https://www.bdangouleme.com/palmares",true)]}),
];
