const source = (id, title, publisher, url, isPrimarySource = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});
const SERVICE = source(
  "service-public-quotidien-pack",
  "Fiches pratiques du quotidien",
  "Service-Public.fr",
  "https://www.service-public.fr/particuliers",
  true,
);
const ROUTE = source(
  "securite-routiere-code-pack",
  "Code de la route et sécurité routière",
  "Sécurité routière",
  "https://www.securite-routiere.gouv.fr/reglementation-liee-la-route",
  true,
);
const EDUCATION = source(
  "education-programmes-pack",
  "Programmes scolaires",
  "Ministère de l’Éducation nationale",
  "https://www.education.gouv.fr/les-programmes-du-college-3203",
  true,
);
const INRS = source(
  "inrs-metiers-securite-pack",
  "Métiers et prévention",
  "Institut national de recherche et de sécurité",
  "https://www.inrs.fr/metiers.html",
  true,
);
const ISO = source(
  "iso-everyday-standards",
  "Standards in action",
  "International Organization for Standardization",
  "https://www.iso.org/standards.html",
  true,
);
const q = (spec) => ({
  themeId: "everyday-life",
  qualificationRule:
    spec.qualificationRule ??
    "Les neuf réponses correspondent aux objets, usages ou catégories demandés.",
  explanation: spec.explanation ?? "La liste suit la référence pratique ou normative citée.",
  ...spec,
});
export const questions = [
  q({
    id: "easy-pieces-maison",
    subthemeId: "everyday-life:home",
    difficultyLevel: 1,
    shortTitle: "Pièces de la maison",
    questionText: "Quelles sont ces neuf pièces ou espaces courants d’un logement ?",
    answers: [
      "Cuisine",
      "Salon",
      "Chambre",
      "Salle de bains",
      "Toilettes",
      "Entrée",
      "Bureau",
      "Buanderie",
      "Garage",
    ],
    sources: [SERVICE],
  }),
  q({
    id: "easy-fournitures-scolaires",
    subthemeId: "everyday-life:school",
    difficultyLevel: 1,
    shortTitle: "Fournitures scolaires",
    questionText: "Quelles sont ces neuf fournitures scolaires courantes ?",
    answers: [
      "Cahier",
      "Stylo",
      "Crayon",
      "Gomme",
      "Règle",
      "Compas",
      "Équerre",
      "Colle",
      "Trousse",
    ],
    sources: [EDUCATION],
  }),
  q({
    id: "easy-transports-urbains",
    subthemeId: "everyday-life:transport",
    difficultyLevel: 1,
    shortTitle: "Transports urbains",
    questionText: "Quels sont ces neuf moyens de transport utilisés en ville ?",
    answers: [
      "Métro",
      "Bus",
      "Tramway",
      "Train",
      "Vélo",
      "Trottinette",
      "Taxi",
      "Voiture",
      "Marche",
    ],
    sources: [ROUTE],
  }),
  q({
    id: "easy-appareils-menagers",
    subthemeId: "everyday-life:objects",
    difficultyLevel: 1,
    shortTitle: "Électroménager",
    questionText: "Quels sont ces neuf appareils électroménagers courants ?",
    answers: [
      "Réfrigérateur",
      "Four",
      "Plaque de cuisson",
      "Lave-linge",
      "Lave-vaisselle",
      "Aspirateur",
      "Micro-ondes",
      "Grille-pain",
      "Bouilloire",
    ],
    sources: [ISO],
  }),
  q({
    id: "easy-metiers-sante",
    subthemeId: "everyday-life:jobs",
    difficultyLevel: 1,
    shortTitle: "Métiers de la santé",
    questionText: "Quels sont ces neuf métiers du secteur de la santé ?",
    answers: [
      "Médecin",
      "Infirmier",
      "Pharmacien",
      "Dentiste",
      "Sage-femme",
      "Kinésithérapeute",
      "Orthophoniste",
      "Opticien",
      "Ambulancier",
    ],
    sources: [INRS],
  }),
  q({
    id: "easy-taches-menageres",
    subthemeId: "everyday-life:habits",
    difficultyLevel: 1,
    shortTitle: "Tâches ménagères",
    questionText: "Quelles sont ces neuf tâches ménagères courantes ?",
    answers: [
      "Faire la vaisselle",
      "Passer l’aspirateur",
      "Laver le sol",
      "Faire la lessive",
      "Repasser",
      "Dépoussiérer",
      "Faire le lit",
      "Sortir les poubelles",
      "Nettoyer les vitres",
    ],
    sources: [SERVICE],
  }),
  q({
    id: "easy-outils-bricolage",
    subthemeId: "everyday-life:objects",
    difficultyLevel: 1,
    shortTitle: "Outils de bricolage",
    questionText: "Quels sont ces neuf outils de bricolage courants ?",
    answers: [
      "Marteau",
      "Tournevis",
      "Pince",
      "Clé à molette",
      "Scie",
      "Perceuse",
      "Niveau à bulle",
      "Mètre ruban",
      "Cutter",
    ],
    sources: [INRS],
  }),

  q({
    id: "medium-panneaux-danger",
    subthemeId: "everyday-life:transport",
    difficultyLevel: 2,
    shortTitle: "Panneaux de danger",
    questionText:
      "Quels dangers annoncent les panneaux triangulaires montrant un virage, deux virages, une pente, un rétrécissement, un pont mobile, un quai, des travaux, des enfants et des animaux sauvages ?",
    answers: [
      "Virage dangereux",
      "Succession de virages",
      "Descente dangereuse",
      "Chaussée rétrécie",
      "Pont mobile",
      "Débouché sur quai",
      "Travaux",
      "Passage d’enfants",
      "Passage d’animaux sauvages",
    ],
    sources: [ROUTE],
  }),
  q({
    id: "medium-symboles-entretien-textile",
    subthemeId: "everyday-life:objects",
    difficultyLevel: 2,
    shortTitle: "Étiquettes textiles",
    questionText:
      "Quelles opérations représentent les neuf familles ou variantes de symboles d’entretien suivantes : cuve, triangle, carré, fer, cercle, cuve barrée, triangle barré, carré barré et fer barré ?",
    answers: [
      "Lavage",
      "Blanchiment",
      "Séchage",
      "Repassage",
      "Nettoyage professionnel",
      "Ne pas laver",
      "Ne pas blanchir",
      "Ne pas sécher en machine",
      "Ne pas repasser",
    ],
    sources: [ISO],
  }),
  q({
    id: "medium-documents-demarches",
    subthemeId: "everyday-life:habits",
    difficultyLevel: 2,
    shortTitle: "Documents administratifs",
    questionText: "Quels sont ces neuf documents personnels ou administratifs courants en France ?",
    answers: [
      "Carte nationale d’identité",
      "Passeport",
      "Permis de conduire",
      "Carte Vitale",
      "Acte de naissance",
      "Justificatif de domicile",
      "Avis d’imposition",
      "Livret de famille",
      "Relevé d’identité bancaire",
    ],
    sources: [SERVICE],
  }),
  q({
    id: "medium-metiers-batiment",
    subthemeId: "everyday-life:jobs",
    difficultyLevel: 2,
    shortTitle: "Métiers du bâtiment",
    questionText:
      "Quels professionnels posent respectivement les installations électriques, canalisations, murs, charpentes, couvertures, peintures, carrelages, menuiseries et systèmes de chauffage ?",
    answers: [
      "Électricien",
      "Plombier",
      "Maçon",
      "Charpentier",
      "Couvreur",
      "Peintre en bâtiment",
      "Carreleur",
      "Menuisier",
      "Chauffagiste",
    ],
    sources: [INRS],
  }),
  q({
    id: "medium-disciplines-college",
    subthemeId: "everyday-life:school",
    difficultyLevel: 2,
    shortTitle: "Matières au collège",
    questionText: "Quelles sont ces neuf disciplines enseignées au collège en France ?",
    answers: [
      "Français",
      "Mathématiques",
      "Histoire-géographie",
      "Sciences de la vie et de la Terre",
      "Physique-chimie",
      "Technologie",
      "Langue vivante",
      "Arts plastiques",
      "Éducation musicale",
    ],
    sources: [EDUCATION],
  }),
  q({
    id: "medium-elements-velo",
    subthemeId: "everyday-life:transport",
    difficultyLevel: 2,
    shortTitle: "Équipement du vélo",
    questionText: "Quels sont ces neuf éléments ou équipements courants d’un vélo ?",
    answers: [
      "Cadre",
      "Guidon",
      "Selle",
      "Pédale",
      "Chaîne",
      "Dérailleur",
      "Frein",
      "Pneu",
      "Éclairage",
    ],
    sources: [ROUTE],
  }),
  q({
    id: "medium-zones-refrigerateur",
    subthemeId: "everyday-life:home",
    difficultyLevel: 2,
    shortTitle: "Rangement alimentaire",
    questionText:
      "Quels sont ces neuf types de produits à ranger séparément dans une cuisine ou un réfrigérateur ?",
    answers: [
      "Viandes crues",
      "Poissons crus",
      "Produits laitiers",
      "Œufs",
      "Fruits",
      "Légumes",
      "Plats cuisinés",
      "Condiments",
      "Produits surgelés",
    ],
    sources: [SERVICE],
    qualificationRule:
      "Sont attendues les neuf catégories de produits nommées; leur emplacement précis dépend du modèle d’appareil.",
  }),

  q({
    id: "hard-categories-permis-france",
    subthemeId: "everyday-life:transport",
    difficultyLevel: 3,
    shortTitle: "Catégories de permis",
    questionText:
      "Quelles sont les neuf catégories de permis françaises suivantes, des cyclomoteurs aux ensembles lourds : AM, A1, A2, A, B, C, D, CE et DE ?",
    answers: ["AM", "A1", "A2", "A", "B", "C", "D", "CE", "DE"],
    sources: [SERVICE],
  }),
  q({
    id: "hard-classes-feux-extincteurs",
    subthemeId: "everyday-life:home",
    difficultyLevel: 3,
    shortTitle: "Classes de feu",
    questionText:
      "À quels types de combustibles correspondent les classes de feu A, B, C, D et F, puis quels agents sont le plus couramment associés à l’eau pulvérisée, la mousse, la poudre et le CO₂ ?",
    answers: [
      "A — solides",
      "B — liquides",
      "C — gaz",
      "D — métaux",
      "F — huiles de cuisson",
      "Eau — classe A",
      "Mousse — classes A et B",
      "Poudre — classes A, B et C",
      "CO₂ — feux électriques et classe B",
    ],
    sources: [INRS],
  }),
  q({
    id: "hard-normes-formats-papier",
    subthemeId: "everyday-life:school",
    difficultyLevel: 3,
    shortTitle: "Formats de papier",
    questionText: "Quels sont les neuf formats de papier de la série A allant de A0 à A8 ?",
    answers: ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8"],
    sources: [ISO],
  }),
  q({
    id: "hard-pictogrammes-danger-chimique",
    subthemeId: "everyday-life:objects",
    difficultyLevel: 3,
    shortTitle: "Pictogrammes chimiques",
    questionText:
      "Que signalent les neuf pictogrammes SGH : bombe explosant, flamme, flamme sur cercle, bouteille, corrosion, tête de mort, point d’exclamation, silhouette et environnement ?",
    answers: [
      "Explosif",
      "Inflammable",
      "Comburant",
      "Gaz sous pression",
      "Corrosif",
      "Toxicité aiguë",
      "Nocif ou irritant",
      "Danger grave pour la santé",
      "Dangereux pour l’environnement",
    ],
    sources: [INRS],
  }),
  q({
    id: "hard-professions-justice",
    subthemeId: "everyday-life:jobs",
    difficultyLevel: 3,
    shortTitle: "Métiers de la justice",
    questionText: "Quels sont ces neuf métiers ou fonctions du système judiciaire français ?",
    answers: [
      "Magistrat du siège",
      "Procureur",
      "Greffier",
      "Avocat",
      "Commissaire de justice",
      "Notaire",
      "Éducateur de la protection judiciaire de la jeunesse",
      "Conseiller pénitentiaire d’insertion et de probation",
      "Surveillant pénitentiaire",
    ],
    sources: [SERVICE],
  }),
  q({
    id: "hard-cycles-lavage-symboles",
    subthemeId: "everyday-life:home",
    difficultyLevel: 3,
    shortTitle: "Symboles de lavage",
    questionText:
      "Que signifient les neuf indications textiles suivantes : 30 °C, 40 °C, 60 °C, une barre sous la cuve, deux barres, lavage à la main, cuve barrée, cercle P et cercle F ?",
    answers: [
      "Lavage à 30 °C",
      "Lavage à 40 °C",
      "Lavage à 60 °C",
      "Programme modéré",
      "Programme très modéré",
      "Lavage à la main",
      "Ne pas laver",
      "Nettoyage professionnel au perchloroéthylène",
      "Nettoyage professionnel aux hydrocarbures",
    ],
    sources: [ISO],
  }),
];
