const src=(id,title,publisher,url)=>({id,title,publisher,url,isPrimarySource:true});
const FIFA=src("fifa-football-history","FIFA World Cup — archive and statistics","FIFA","https://www.fifa.com/en/tournaments/mens/worldcup");
const UEFA=src("uefa-football-history","UEFA competition histories and statistics","UEFA","https://www.uefa.com/uefachampionsleague/history/");
const FFF=src("fff-equipe-france","Histoire et palmarès des Bleus","Fédération française de football","https://www.fff.fr/equipe-nationale/");
const LFP=src("lfp-palmares","Palmarès de la Ligue 1","Ligue de football professionnel","https://www.ligue1.fr/Articles/Histoire/2020/02/07/le-palmares");
const BALLON=src("france-football-ballon-or","Palmarès du Ballon d’Or","France Football","https://www.francefootball.fr/ballon-d-or/palmares/");
const q=([id,sub,d,title,text,answers,source=FIFA,rule])=>({id,themeId:"football",subthemeId:`football:${sub}`,difficultyLevel:d,shortTitle:title,questionText:text,answers,sources:[source],qualificationRule:rule??"Les neuf réponses sont celles de la période et de la compétition précisément indiquées.",explanation:"Liste chronologique vérifiable dans les archives officielles de la compétition."});
export const questions=[
q(["easy-hotes-coupe-monde-1930-1970","world-cup",1,"Premiers pays hôtes","Quels sont les neuf pays ayant accueilli les Coupes du monde masculines de 1930 à 1970 ?",["Uruguay","Italie","France","Brésil","Suisse","Suède","Chili","Angleterre","Mexique"]]),
q(["easy-premiers-ballon-or-differents","clubs-players",1,"Premiers Ballons d’or","Qui sont les neuf premiers lauréats différents du Ballon d’or masculin ?",["Stanley Matthews","Alfredo Di Stéfano","Raymond Kopa","Luis Suárez","Omar Sívori","Josef Masopust","Lev Yachine","Denis Law","Eusébio"],BALLON]),
q(["easy-finalistes-france-1998","national-teams",1,"Onze des Bleus en 1998","Quels sont les neuf joueurs de champ titulaires de la France en finale du Mondial 1998, hors capitaine Didier Deschamps ?",["Lilian Thuram","Frank Lebœuf","Marcel Desailly","Bixente Lizarazu","Christian Karembeu","Emmanuel Petit","Zinédine Zidane","Youri Djorkaeff","Stéphane Guivarc’h"],FFF]),
q(["easy-vainqueurs-ligue1-1998-2021","french-football",1,"Champions de France","Quels sont les neuf clubs différents champions de France entre 1998 et 2021 ?",["Lens","Bordeaux","Monaco","Nantes","Olympique lyonnais","Olympique de Marseille","Lille","Montpellier","Paris Saint-Germain"],LFP]),
q(["easy-stades-finales-mondial-1990-2022","stadiums",1,"Stades des finales","Dans quels neuf stades se sont jouées les finales de Coupe du monde masculine de 1990 à 2022 ?",["Stadio Olimpico","Rose Bowl","Stade de France","International Stadium Yokohama","Olympiastadion Berlin","Soccer City","Maracanã","Stade Loujniki","Stade de Lusail"]]),
q(["easy-neuf-premiers-vainqueurs-c1","champions-league",1,"Premiers champions d’Europe","Quels sont les neuf premiers clubs différents à avoir remporté la Coupe des clubs champions européens ?",["Real Madrid","Benfica","AC Milan","Inter Milan","Celtic","Manchester United","Feyenoord","Ajax","Bayern Munich"],UEFA]),
q(["easy-pays-euro-2016","european-championship",1,"Parcours du Portugal","Quelles sont les neuf sélections rencontrées par le Portugal dans son groupe de qualification à l’Euro 2016 puis lors de ses cinq premiers matchs du tournoi ?",["Albanie","Arménie","Danemark","Serbie","Islande","Autriche","Hongrie","Croatie","Pologne"],UEFA]),
q(["medium-buteurs-finales-mondial-depuis-1986","world-cup",2,"Buteurs en finale","Qui sont les neuf premiers joueurs différents à avoir marqué en finale de Coupe du monde masculine à partir de 1986 ?",["José Luis Brown","Jorge Valdano","Karl-Heinz Rummenigge","Rudi Völler","Jorge Burruchaga","Andreas Brehme","Zinédine Zidane","Emmanuel Petit","Ronaldo"]]),
q(["medium-adversaires-france-1998-2000","national-teams",2,"Adversaires des Bleus","Quelles sont les neuf premières sélections différentes rencontrées par la France lors des Mondiaux 1998 puis de l’Euro 2000 ?",["Afrique du Sud","Arabie saoudite","Danemark","Paraguay","Italie","Croatie","Brésil","Tchéquie","Pays-Bas"],FFF]),
q(["medium-finalistes-euro-1960-1992","european-championship",2,"Premiers finalistes de l’Euro","Quelles sont les neuf premières sélections différentes à avoir atteint une finale de l’Euro masculin ?",["Union soviétique","Yougoslavie","Espagne","Italie","Allemagne de l’Ouest","Tchécoslovaquie","Belgique","France","Pays-Bas"],UEFA]),
q(["hard-clubs-francais-finales-uefa","champions-league",3,"Finalistes français en Europe","Quels sont les neuf clubs français ayant disputé une finale majeure UEFA masculine avant 2025 ?",["Stade de Reims","AS Saint-Étienne","Olympique de Marseille","AS Monaco","Paris Saint-Germain","Girondins de Bordeaux","SC Bastia","RC Lens","Montpellier HSC"],UEFA]),
q(["medium-selectionneurs-bleus-1984-2024","national-teams",2,"Sélectionneurs des Bleus","Quels sont les neuf sélectionneurs de l’équipe de France masculine de 1984 à 2024 ?",["Michel Hidalgo","Henri Michel","Michel Platini","Gérard Houllier","Aimé Jacquet","Roger Lemerre","Jacques Santini","Raymond Domenech","Didier Deschamps"],FFF]),
q(["medium-clubs-champions-france-1993-2012","french-football",2,"Champions de France distincts","Quels sont les neuf clubs différents sacrés champions de France entre 1993 et 2012 ?",["Paris Saint-Germain","Nantes","Auxerre","Monaco","Lens","Bordeaux","Olympique lyonnais","Olympique de Marseille","Montpellier"],LFP]),
q(["medium-stades-euro-2016-france","stadiums",2,"Stades de l’Euro 2016","Quels sont les neuf stades français de l’Euro 2016 autres que le Stade de France ?",["Parc des Princes","Stade Vélodrome","Groupama Stadium","Stade Pierre-Mauroy","Matmut Atlantique","Stade Geoffroy-Guichard","Stadium de Toulouse","Allianz Riviera","Stade Bollaert-Delelis"],UEFA]),
q(["medium-gardiens-champions-monde-1990-2022","world-cup",2,"Gardiens champions du monde","Quels sont les neuf gardiens titulaires des équipes championnes du monde masculines de 1990 à 2022 ?",["Bodo Illgner","Cláudio Taffarel","Fabien Barthez","Marcos","Gianluigi Buffon","Iker Casillas","Manuel Neuer","Hugo Lloris","Emiliano Martínez"]]),
q(["hard-capitaines-champions-monde-1990-2022","world-cup",3,"Le brassard et le trophée","De Lothar Matthäus à Lionel Messi, quels neuf joueurs ont soulevé le trophée mondial comme capitaine entre 1990 et 2022 ?",["Lothar Matthäus","Dunga","Didier Deschamps","Cafu","Fabio Cannavaro","Iker Casillas","Philipp Lahm","Hugo Lloris","Lionel Messi"]]),
q(["hard-buteurs-france-euro-1984","national-teams",3,"Buteurs français 1984","Quels sont les neuf buts français de la phase de groupes de l’Euro 1984, classés par buteur et adversaire ?",["Platini contre le Danemark","Platini contre la Belgique 1","Platini contre la Belgique 2","Platini contre la Belgique 3","Giresse contre la Belgique","Fernandez contre la Belgique","Platini contre la Yougoslavie 1","Platini contre la Yougoslavie 2","Platini contre la Yougoslavie 3"],FFF]),
q(["hard-finales-c1-neuf-villes","champions-league",3,"Villes de finales européennes","Quelles sont les neuf premières villes différentes à avoir accueilli une finale de Coupe des clubs champions européens ?",["Paris","Madrid","Bruxelles","Stuttgart","Glasgow","Berne","Amsterdam","Londres","Vienne"],UEFA]),
q(["hard-ballon-or-1961-1969","clubs-players",3,"Ballons d’or des années 1960","Quels sont les neuf lauréats du Ballon d’or masculin de 1961 à 1969, année par année ?",["Omar Sívori 1961","Josef Masopust 1962","Lev Yachine 1963","Denis Law 1964","Eusébio 1965","Bobby Charlton 1966","Flórián Albert 1967","George Best 1968","Gianni Rivera 1969"],BALLON]),
q(["hard-neuf-stades-france-mondial-1938","stadiums",3,"Stades du Mondial 1938","Quels sont les neuf stades ayant accueilli au moins un match de la Coupe du monde 1938 en France, hors Parc Lescure de Bordeaux ?",["Stade olympique de Colombes","Parc des Princes","Stade Vélodrome","Stade municipal de Toulouse","Stade du Fort Carré","Stade de la Meinau","Stade Victor-Boucquey","Stade municipal du Havre","Stade Auguste-Delaune"],FIFA])
];
