const source = (id, title, publisher, url, isPrimarySource = true) => ({ id, title, publisher, url, isPrimarySource });
const INSEE = source("insee-cog-france-pack", "Code officiel géographique", "Insee", "https://www.insee.fr/fr/information/2560452");
const ELYSEE = source("elysee-presidents-republique", "Les présidents de la République", "Présidence de la République", "https://www.elysee.fr/la-presidence/les-presidents-de-la-republique");
const CULTURE = source("culture-monuments-nationaux", "Monuments nationaux", "Ministère de la Culture", "https://www.culture.gouv.fr/thematiques/monuments-sites/monuments-historiques-sites-patrimoniaux");
const PARCS = source("parcs-nationaux-france", "Les parcs nationaux de France", "Office français de la biodiversité", "https://www.ofb.gouv.fr/les-parcs-nationaux-de-france");
const SENAT = source("senat-constitutions-france", "Les Constitutions de la France", "Sénat", "https://www.senat.fr/evenement/revision/constitutions.html");
const ACADEMIE = source("academie-francaise-immortels", "Les Immortels", "Académie française", "https://www.academie-francaise.fr/les-immortels");
const UNESCO = source("unesco-france-properties", "France — World Heritage properties", "UNESCO World Heritage Centre", "https://whc.unesco.org/en/statesparties/fr");
const ASSEMBLEE = source("assemblee-republiques-france", "Les Républiques françaises", "Assemblée nationale", "https://www.assemblee-nationale.fr/dyn/histoire-et-patrimoine");
const q = (spec) => ({ themeId:"france", qualificationRule:spec.qualificationRule ?? "Les neuf réponses suivent le périmètre et l’ordre indiqués dans la question.", explanation:spec.explanation ?? "La liste est vérifiée dans la source institutionnelle citée.", ...spec });

export const questions = [
  q({ id:"easy-paris-arrondissements-01-09", subthemeId:"france:geography", difficultyLevel:1, shortTitle:"Arrondissements de Paris", questionText:"Quels sont les neuf premiers arrondissements municipaux de Paris ?", answers:["1er arrondissement de Paris","2e arrondissement de Paris","3e arrondissement de Paris","4e arrondissement de Paris","5e arrondissement de Paris","6e arrondissement de Paris","7e arrondissement de Paris","8e arrondissement de Paris","9e arrondissement de Paris"], sources:[INSEE] }),
  q({ id:"easy-departements-10-18", subthemeId:"france:regions", difficultyLevel:1, shortTitle:"Départements 10 à 18", questionText:"Quels départements français portent les numéros 10 à 18 ?", answers:["Aube","Aude","Aveyron","Bouches-du-Rhône","Calvados","Cantal","Charente","Charente-Maritime","Cher"], sources:[INSEE] }),
  q({ id:"easy-neuf-premiers-louis", subthemeId:"france:history", difficultyLevel:1, shortTitle:"Rois nommés Louis", questionText:"Comment désigne-t-on les rois de France numérotés de Louis Ier à Louis IX ?", answers:["Louis Ier","Louis II","Louis III","Louis IV","Louis V","Louis VI","Louis VII","Louis VIII","Louis IX"], sources:[ELYSEE], qualificationRule:"Les formes numérotées de Louis Ier à Louis IX sont attendues; les surnoms sont facultatifs." }),
  q({ id:"easy-neuf-premiers-presidents-republique", subthemeId:"france:history", difficultyLevel:1, shortTitle:"Premiers présidents français", questionText:"Quels sont les neuf premiers présidents de la République française, de Louis-Napoléon Bonaparte à Armand Fallières ?", answers:["Louis-Napoléon Bonaparte","Adolphe Thiers","Patrice de Mac Mahon","Jules Grévy","Sadi Carnot","Jean Casimir-Perier","Félix Faure","Émile Loubet","Armand Fallières"], sources:[ELYSEE] }),
  q({ id:"easy-neuf-regions-alphabetiques", subthemeId:"france:regions", difficultyLevel:1, shortTitle:"Régions par ordre alphabétique", questionText:"Quelles sont les neuf premières régions françaises par ordre alphabétique, outre-mer compris ?", answers:["Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Bretagne","Centre-Val de Loire","Corse","Grand Est","Guadeloupe","Guyane","Hauts-de-France"], sources:[INSEE] }),
  q({ id:"easy-neuf-monuments-parisiens", subthemeId:"france:heritage", difficultyLevel:1, shortTitle:"Monuments de Paris", questionText:"Quels sont ces neuf monuments emblématiques situés à Paris ?", answers:["Tour Eiffel","Arc de Triomphe","Panthéon","Notre-Dame de Paris","Sainte-Chapelle","Opéra Garnier","Hôtel des Invalides","Conciergerie","Colonne de Juillet"], sources:[CULTURE], qualificationRule:"Sont attendus les neuf monuments parisiens explicitement sélectionnés." }),

  q({ id:"medium-departements-19-26", subthemeId:"france:regions", difficultyLevel:2, shortTitle:"Départements 19 à 26", questionText:"Quels départements français sont placés de 19 à 26 dans le Code officiel géographique, en incluant 2A et 2B ?", answers:["Corrèze","Corse-du-Sud","Haute-Corse","Côte-d’Or","Côtes-d’Armor","Creuse","Dordogne","Doubs","Drôme"], sources:[INSEE], qualificationRule:"La Corse-du-Sud (2A) et la Haute-Corse (2B) sont placées entre 19 et 21; il n’existe pas de département 20." }),
  q({ id:"medium-departements-28-36", subthemeId:"france:regions", difficultyLevel:2, shortTitle:"Départements 28 à 36", questionText:"Quels départements français portent les numéros 28 à 36 ?", answers:["Eure-et-Loir","Finistère","Gard","Haute-Garonne","Gers","Gironde","Hérault","Ille-et-Vilaine","Indre"], sources:[INSEE] }),
  q({ id:"medium-neuf-parcs-nationaux-creation", subthemeId:"france:geography", difficultyLevel:2, shortTitle:"Premiers parcs nationaux", questionText:"Quels sont les neuf premiers parcs nationaux français par date de création ?", answers:["Vanoise","Port-Cros","Pyrénées","Cévennes","Écrins","Mercantour","Guadeloupe","La Réunion","Guyane"], sources:[PARCS] }),
  q({ id:"medium-neuf-presidents-cinquieme", subthemeId:"france:institutions", difficultyLevel:2, shortTitle:"Présidents de la Ve République", questionText:"Quels sont les huit présidents de la Ve République et le président par intérim Alain Poher ?", answers:["Charles de Gaulle","Georges Pompidou","Alain Poher","Valéry Giscard d’Estaing","François Mitterrand","Jacques Chirac","Nicolas Sarkozy","François Hollande","Emmanuel Macron"], sources:[ELYSEE], qualificationRule:"Alain Poher est compté une seule fois malgré ses deux intérims." }),
  q({ id:"medium-neuf-sites-unesco-1979-1981", subthemeId:"france:heritage", difficultyLevel:2, shortTitle:"Premiers biens UNESCO", questionText:"Quels sont les cinq biens français inscrits au patrimoine mondial de l’UNESCO en 1979 et ces quatre biens inscrits en 1981 ?", answers:["Mont-Saint-Michel et sa baie","Cathédrale de Chartres","Versailles","Vézelay","Sites préhistoriques et grottes ornées de la vallée de la Vézère","Palais et parc de Fontainebleau","Cathédrale d’Amiens","Théâtre antique et arc de triomphe d’Orange","Monuments romains et romans d’Arles"], sources:[UNESCO], qualificationRule:"Sont attendus les cinq biens français de 1979, puis les quatre biens de 1981 sélectionnés dans la question." }),
  q({ id:"medium-neuf-femmes-academie-francaise", subthemeId:"france:arts", difficultyLevel:2, shortTitle:"Premières académiciennes", questionText:"Quelles sont les neuf premières femmes élues à l’Académie française ?", answers:["Marguerite Yourcenar","Jacqueline de Romilly","Hélène Carrère d’Encausse","Florence Delay","Assia Djebar","Simone Veil","Danièle Sallenave","Dominique Bona","Barbara Cassin"], sources:[ACADEMIE] }),

  q({ id:"hard-neuf-constitutions-1791-1848", subthemeId:"france:institutions", difficultyLevel:3, shortTitle:"Constitutions 1791-1848", questionText:"Quels sont les neuf textes constitutionnels français adoptés de 1791 à 1848 inclus ?", answers:["Constitution de 1791","Constitution de l’an I","Constitution de l’an III","Constitution de l’an VIII","Constitution de l’an X","Constitution de l’an XII","Charte constitutionnelle de 1814","Charte constitutionnelle de 1830","Constitution de 1848"], sources:[SENAT] }),
  q({ id:"hard-neuf-presidents-assemblee-constituante-1789", subthemeId:"france:history", difficultyLevel:3, shortTitle:"Présidents de la Constituante", questionText:"Quels sont ces neuf premiers présidents de l’Assemblée nationale constituante en 1789 ?", answers:["Jean-Sylvain Bailly","François-Alexandre-Frédéric de La Rochefoucauld-Liancourt","Isaac Le Chapelier","Jean-Georges Lefranc de Pompignan","François de Clermont-Tonnerre","César-Guillaume de La Luzerne","Stanislas de Clermont-Tonnerre","Pierre-Victor Malouët","Charles-Maurice de Talleyrand-Périgord"], sources:[ASSEMBLEE], qualificationRule:"Sont attendus les neuf titulaires nommés dans cette sélection du début de la Constituante." }),
  q({ id:"hard-neuf-departements-revolutionnaires-belgique", subthemeId:"france:history", difficultyLevel:3, shortTitle:"Départements réunis de Belgique", questionText:"Quels étaient les neuf départements français créés en 1795 dans les territoires des anciens Pays-Bas autrichiens et de Liège ?", answers:["Dyle","Deux-Nèthes","Escaut","Forêts","Jemmapes","Lys","Meuse-Inférieure","Ourthe","Sambre-et-Meuse"], sources:[INSEE] }),
  q({ id:"hard-neuf-rois-capetiens-directs", subthemeId:"france:history", difficultyLevel:3, shortTitle:"Premiers Capétiens directs", questionText:"Quels sont les neuf premiers rois de la dynastie des Capétiens directs ?", answers:["Hugues Capet","Robert II","Henri Ier","Philippe Ier","Louis VI","Louis VII","Philippe II Auguste","Louis VIII","Louis IX"], sources:[ELYSEE] }),
  q({ id:"hard-neuf-architectes-monuments-francais", subthemeId:"france:heritage", difficultyLevel:3, shortTitle:"Architectes et monuments", questionText:"Quels sont les architectes associés à ces neuf monuments français : tour Eiffel, Arc de Triomphe, Panthéon, opéra Garnier, pyramide du Louvre, Centre Pompidou, viaduc de Millau, arche de la Défense et villa Savoye ?", answers:["Gustave Eiffel","Jean-François-Thérèse Chalgrin","Jacques-Germain Soufflot","Charles Garnier","Ieoh Ming Pei","Renzo Piano et Richard Rogers","Norman Foster","Johan Otto von Spreckelsen","Le Corbusier et Pierre Jeanneret"], sources:[CULTURE], qualificationRule:"Une réponse associe chaque monument cité à son architecte ou à son équipe principale." }),
  q({ id:"hard-goncourt-2010-2018", subthemeId:"france:geography", difficultyLevel:3, shortTitle:"Territoires français ultramarins", questionText:"Quels sont ces neuf départements ou collectivités français habités situés outre-mer ?", answers:["Guadeloupe","Martinique","Guyane","La Réunion","Mayotte","Saint-Pierre-et-Miquelon","Saint-Barthélemy","Saint-Martin","Wallis-et-Futuna"], sources:[INSEE], qualificationRule:"Sont retenus les neuf territoires explicitement sélectionnés parmi les départements et collectivités habités d’outre-mer." }),
];
