const source = (id, title, publisher, url, isPrimarySource = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});

const SOURCES = {
  southAmerica: source(
    "britannica-south-america",
    "South America",
    "Encyclopædia Britannica",
    "https://www.britannica.com/place/South-America",
    false,
  ),
  drc: source(
    "cia-drc",
    "Democratic Republic of the Congo",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/democratic-republic-of-the-congo/",
  ),
  brazil: source(
    "ibge-regions-brazil",
    "Divisões regionais do Brasil",
    "Instituto Brasileiro de Geografia e Estatística",
    "https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/15778-divisoes-regionais-do-brasil.html",
  ),
  southAfrica: source(
    "south-africa-provinces",
    "Provinces",
    "Gouvernement sud-africain",
    "https://www.gov.za/provinces",
  ),
  austria: source(
    "cia-austria",
    "Austria",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/austria/",
  ),
  bolivia: source(
    "cia-bolivia",
    "Bolivia",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/bolivia/",
  ),
  england: source(
    "ons-england-regions",
    "England — administrative geography",
    "Office for National Statistics",
    "https://www.ons.gov.uk/methodology/geography/ukgeographies/administrativegeography/england",
  ),
  ulster: source(
    "britannica-ulster",
    "Ulster",
    "Encyclopædia Britannica",
    "https://www.britannica.com/place/Ulster-historic-province-Ireland",
    false,
  ),
  baltic: source(
    "helcom-baltic-states",
    "Baltic Sea coastal countries",
    "Commission d’Helsinki — HELCOM",
    "https://helcom.fi/about-us/contracting-parties/",
  ),
  usRegions: source(
    "us-census-regions",
    "Census Regions and Divisions of the United States",
    "United States Census Bureau",
    "https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf",
  ),
  worldArea: source(
    "un-surface-area",
    "Surface area and population",
    "Nations unies — Division de statistique",
    "https://unstats.un.org/unsd/demographic-social/products/dyb/dybsets/2022.pdf",
  ),
  worldPopulation: source(
    "un-wpp-2024",
    "World Population Prospects 2024",
    "Nations unies — Population Division",
    "https://population.un.org/wpp/Download/Standard/MostUsed/",
  ),
  canada: source(
    "canada-provinces-territories",
    "Provinces and territories",
    "Gouvernement du Canada",
    "https://www.canada.ca/en/intergovernmental-affairs/services/provinces-territories.html",
  ),
  gabon: source(
    "cia-gabon",
    "Gabon",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/gabon/",
  ),
  solomon: source(
    "cia-solomon-islands",
    "Solomon Islands",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/solomon-islands/",
  ),
  tuvalu: source(
    "cia-tuvalu",
    "Tuvalu",
    "CIA World Factbook",
    "https://www.cia.gov/the-world-factbook/countries/tuvalu/",
  ),
};

const q = (spec) => ({
  themeId: "geography",
  qualificationRule:
    spec.qualificationRule ??
    "Chaque réponse appartient exactement à l’ensemble géographique défini dans la question et la source citée.",
  explanation:
    spec.explanation ??
    "La source de référence délimite cet ensemble à neuf territoires ou entités géographiques.",
  ...spec,
});

export const questions = [
  q({
    id: "easy-amerique-hispanophone",
    subthemeId: "geography:flags-languages",
    difficultyLevel: 1,
    shortTitle: "Amérique hispanophone",
    questionText: "Quels sont les neuf pays hispanophones d’Amérique du Sud ?",
    answers: [
      "Argentine",
      "Bolivie",
      "Chili",
      "Colombie",
      "Équateur",
      "Paraguay",
      "Pérou",
      "Uruguay",
      "Venezuela",
    ],
    sources: [SOURCES.southAmerica],
    exclusionNotes:
      "Le Brésil, le Guyana et le Suriname n’ont pas l’espagnol comme langue nationale principale.",
  }),
  q({
    id: "medium-voisins-rdc",
    subthemeId: "geography:borders-territories",
    difficultyLevel: 2,
    shortTitle: "Frontières congolaises",
    questionText: "Quels sont les neuf pays frontaliers de la République démocratique du Congo ?",
    answers: [
      "Angola",
      "Burundi",
      "République centrafricaine",
      "République du Congo",
      "Rwanda",
      "Soudan du Sud",
      "Tanzanie",
      "Ouganda",
      "Zambie",
    ],
    sources: [SOURCES.drc],
  }),
  q({
    id: "medium-nordeste-bresil",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 2,
    shortTitle: "Nordeste brésilien",
    questionText: "Quels sont les neuf États de la région Nordeste du Brésil ?",
    answers: [
      "Maranhão",
      "Piauí",
      "Ceará",
      "Rio Grande do Norte",
      "Paraíba",
      "Pernambuco",
      "Alagoas",
      "Sergipe",
      "Bahia",
    ],
    sources: [SOURCES.brazil],
  }),
  q({
    id: "medium-provinces-afrique-sud",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 2,
    shortTitle: "Provinces sud-africaines",
    questionText: "Quelles sont les neuf provinces de l’Afrique du Sud ?",
    answers: [
      "Cap-Oriental",
      "État-Libre",
      "Gauteng",
      "KwaZulu-Natal",
      "Limpopo",
      "Mpumalanga",
      "Cap-Nord",
      "Nord-Ouest",
      "Cap-Occidental",
    ],
    sources: [SOURCES.southAfrica],
  }),
  q({
    id: "medium-etats-autriche",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 2,
    shortTitle: "Autriche fédérale",
    questionText: "Quels sont les neuf Länder, ou États fédérés, de l’Autriche ?",
    answers: [
      "Burgenland",
      "Carinthie",
      "Basse-Autriche",
      "Haute-Autriche",
      "Salzbourg",
      "Styrie",
      "Tyrol",
      "Vorarlberg",
      "Vienne",
    ],
    sources: [SOURCES.austria],
  }),
  q({
    id: "medium-departements-bolivie",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 2,
    shortTitle: "Départements boliviens",
    questionText: "Quels sont les neuf départements de la Bolivie ?",
    answers: [
      "Beni",
      "Chuquisaca",
      "Cochabamba",
      "La Paz",
      "Oruro",
      "Pando",
      "Potosí",
      "Santa Cruz",
      "Tarija",
    ],
    sources: [SOURCES.bolivia],
  }),
  q({
    id: "hard-regions-angleterre",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 3,
    shortTitle: "Régions anglaises",
    questionText: "Quelles sont les neuf régions statistiques officielles de l’Angleterre ?",
    answers: [
      "Angleterre du Nord-Est",
      "Angleterre du Nord-Ouest",
      "Yorkshire-et-Humber",
      "Midlands de l’Est",
      "Midlands de l’Ouest",
      "Angleterre de l’Est",
      "Londres",
      "Angleterre du Sud-Est",
      "Angleterre du Sud-Ouest",
    ],
    sources: [SOURCES.england],
  }),
  q({
    id: "hard-comtes-ulster",
    subthemeId: "geography:borders-territories",
    difficultyLevel: 3,
    shortTitle: "Province d’Ulster",
    questionText: "Quels sont les neuf comtés historiques de la province irlandaise d’Ulster ?",
    answers: [
      "Antrim",
      "Armagh",
      "Cavan",
      "Londonderry",
      "Donegal",
      "Down",
      "Fermanagh",
      "Monaghan",
      "Tyrone",
    ],
    sources: [SOURCES.ulster],
    exclusionNotes: "L’Ulster historique ne se limite pas aux six comtés de l’Irlande du Nord.",
  }),
  q({
    id: "easy-pays-riverains-baltique",
    subthemeId: "geography:rivers-seas",
    difficultyLevel: 1,
    shortTitle: "Autour de la Baltique",
    questionText: "Quels sont les neuf pays qui possèdent un littoral sur la mer Baltique ?",
    answers: [
      "Allemagne",
      "Danemark",
      "Estonie",
      "Finlande",
      "Lettonie",
      "Lituanie",
      "Pologne",
      "Russie",
      "Suède",
    ],
    sources: [SOURCES.baltic],
  }),
  q({
    id: "easy-etats-nord-est-etats-unis",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 1,
    shortTitle: "Nord-Est américain",
    questionText:
      "Quels sont les neuf États de la région Nord-Est selon le Bureau du recensement des États-Unis ?",
    answers: [
      "Maine",
      "New Hampshire",
      "Vermont",
      "Massachusetts",
      "Rhode Island",
      "Connecticut",
      "New York",
      "New Jersey",
      "Pennsylvanie",
    ],
    sources: [SOURCES.usRegions],
  }),
  q({
    id: "easy-neuf-plus-grands-pays-superficie",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 1,
    shortTitle: "Géants territoriaux",
    questionText:
      "Quels sont les neuf plus grands pays du monde par superficie totale dans l’annuaire 2022 de l’ONU ?",
    answers: [
      "Russie",
      "Canada",
      "Chine",
      "États-Unis",
      "Brésil",
      "Australie",
      "Inde",
      "Argentine",
      "Kazakhstan",
    ],
    sources: [SOURCES.worldArea],
    referenceDate: "2022-12-31",
    timeSensitive: true,
    recommendedReviewAt: "2030-01-31",
    qualificationRule:
      "Sont retenus les neuf États souverains ayant la plus grande superficie totale dans le tableau de l’ONU.",
  }),
  q({
    id: "easy-neuf-pays-plus-peuples-2024",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 1,
    shortTitle: "Population mondiale 2024",
    questionText:
      "Selon les estimations médianes de l’ONU pour 2024, quels étaient les neuf pays les plus peuplés ?",
    answers: [
      "Inde",
      "Chine",
      "États-Unis",
      "Indonésie",
      "Pakistan",
      "Nigeria",
      "Brésil",
      "Bangladesh",
      "Russie",
    ],
    sources: [SOURCES.worldPopulation],
    referenceDate: "2024-07-01",
    timeSensitive: true,
    recommendedReviewAt: "2027-07-31",
    qualificationRule:
      "Sont retenus les neuf premiers États du classement de population médiane 2024 des Nations unies.",
  }),
  q({
    id: "easy-neuf-plus-petits-etats-superficie",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 1,
    shortTitle: "Micro-États",
    questionText:
      "Quels sont les neuf plus petits États souverains du monde par superficie totale ?",
    answers: [
      "Vatican",
      "Monaco",
      "Nauru",
      "Tuvalu",
      "Saint-Marin",
      "Liechtenstein",
      "Îles Marshall",
      "Saint-Christophe-et-Niévès",
      "Maldives",
    ],
    sources: [SOURCES.worldArea],
    qualificationRule:
      "Sont retenus les neuf États souverains ayant la plus faible superficie totale dans le tableau de l’ONU.",
  }),
  q({
    id: "hard-provinces-canada-avant-1949",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 3,
    shortTitle: "Confédération canadienne",
    questionText:
      "Quelles sont les neuf provinces entrées dans la Confédération canadienne avant Terre-Neuve-et-Labrador en 1949 ?",
    answers: [
      "Ontario",
      "Québec",
      "Nouvelle-Écosse",
      "Nouveau-Brunswick",
      "Manitoba",
      "Colombie-Britannique",
      "Île-du-Prince-Édouard",
      "Saskatchewan",
      "Alberta",
    ],
    sources: [SOURCES.canada],
    exclusionNotes:
      "Les trois territoires ne sont pas des provinces ; Terre-Neuve-et-Labrador a rejoint la Confédération en 1949.",
  }),
  q({
    id: "medium-neuf-provinces-gabon",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 2,
    shortTitle: "Provinces gabonaises",
    questionText: "Quelles sont les neuf provinces du Gabon ?",
    answers: [
      "Estuaire",
      "Haut-Ogooué",
      "Moyen-Ogooué",
      "Ngounié",
      "Nyanga",
      "Ogooué-Ivindo",
      "Ogooué-Lolo",
      "Ogooué-Maritime",
      "Woleu-Ntem",
    ],
    sources: [SOURCES.gabon],
  }),
  q({
    id: "hard-provinces-iles-salomon",
    subthemeId: "geography:mountains-islands",
    difficultyLevel: 3,
    shortTitle: "Îles Salomon",
    questionText:
      "Quelles sont les neuf provinces des Îles Salomon, hors territoire de la capitale ?",
    answers: [
      "Central",
      "Choiseul",
      "Guadalcanal",
      "Isabel",
      "Makira-Ulawa",
      "Malaita",
      "Rennell-et-Bellona",
      "Temotu",
      "Western",
    ],
    sources: [SOURCES.solomon],
    exclusionNotes: "Honiara forme un territoire-capitale distinct et n’est pas une province.",
  }),
  q({
    id: "hard-neuf-iles-tuvalu",
    subthemeId: "geography:mountains-islands",
    difficultyLevel: 3,
    shortTitle: "Archipel des Tuvalu",
    questionText: "Quels sont les neuf atolls ou îles principales qui composent les Tuvalu ?",
    answers: [
      "Funafuti",
      "Nanumea",
      "Nanumaga",
      "Niutao",
      "Nui",
      "Nukufetau",
      "Nukulaelae",
      "Vaitupu",
      "Niulakita",
    ],
    sources: [SOURCES.tuvalu],
  }),
  q({
    id: "hard-provinces-sri-lanka",
    subthemeId: "geography:cities-regions",
    difficultyLevel: 3,
    shortTitle: "Provinces sri-lankaises",
    questionText: "Quelles sont les neuf provinces du Sri Lanka ?",
    answers: [
      "Centre",
      "Est",
      "Centre-Nord",
      "Nord",
      "Nord-Ouest",
      "Sabaragamuwa",
      "Sud",
      "Uva",
      "Ouest",
    ],
    sources: [
      source(
        "sri-lanka-census-2024-pack",
        "Census of Population and Housing 2024 — Preliminary Report",
        "Department of Census and Statistics, Sri Lanka",
        "https://www.statistics.gov.lk/Resource/en/Population/CPH_2024/Preliminary_Report.pdf",
      ),
    ],
    exclusionNotes: "Les vingt-cinq districts sont un niveau administratif différent.",
  }),
];
