const source = (id, title, publisher, url, isPrimarySource = false) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});

const BRITANNICA = source(
  "britannica-history-pack",
  "World history",
  "Encyclopaedia Britannica",
  "https://www.britannica.com/topic/history",
);
const US_GOV = source(
  "usa-presidents-official",
  "Presidents of the United States",
  "The White House",
  "https://www.whitehouse.gov/about-the-white-house/presidents/",
  true,
);
const ROMAN = source(
  "britannica-roman-emperors",
  "List of Roman emperors",
  "Encyclopaedia Britannica",
  "https://www.britannica.com/topic/list-of-Roman-emperors-2043294",
);
const UK = source(
  "royal-family-kings-queens",
  "Kings and Queens from 1066",
  "The Royal Family",
  "https://www.royal.uk/kings-and-queens-1066",
  true,
);
const UN = source(
  "un-secretaries-general",
  "Former Secretaries-General",
  "United Nations",
  "https://www.un.org/sg/en/content/former-secretaries-general",
  true,
);
const NATO = source(
  "nato-members-history",
  "NATO member countries",
  "NATO",
  "https://www.nato.int/cps/en/natohq/topics_52044.htm",
  true,
);
const EU = source(
  "eu-history-enlargement",
  "History of the European Union",
  "European Union",
  "https://european-union.europa.eu/principles-countries-history/history-eu_en",
  true,
);
const NOBEL = source(
  "nobel-peace-laureates",
  "All Nobel Peace Prizes",
  "Nobel Prize Outreach",
  "https://www.nobelprize.org/prizes/lists/all-nobel-peace-prizes/",
  true,
);
const NASA = source(
  "nasa-moonwalkers",
  "Who has walked on the Moon?",
  "NASA",
  "https://science.nasa.gov/moon/moon-walkers/",
  true,
);
const q = (spec) => ({
  themeId: "history",
  qualificationRule:
    spec.qualificationRule ??
    "Les neuf éléments retenus suivent le périmètre et l’ordre précisés dans la question.",
  explanation: spec.explanation ?? "La liste est vérifiée dans la source historique citée.",
  ...spec,
});

export const questions = [
  q({
    id: "easy-neuf-empereurs-romains",
    subthemeId: "history:antiquity",
    difficultyLevel: 1,
    shortTitle: "Premiers empereurs romains",
    questionText: "Quels sont les neuf premiers empereurs romains, d’Auguste à Vespasien ?",
    answers: [
      "Auguste",
      "Tibère",
      "Caligula",
      "Claude",
      "Néron",
      "Galba",
      "Othon",
      "Vitellius",
      "Vespasien",
    ],
    sources: [ROMAN],
    qualificationRule:
      "Sont retenus les neuf premiers empereurs dans l’ordre chronologique, jusqu’à Vespasien inclus.",
  }),
  q({
    id: "easy-neuf-premiers-presidents-usa",
    subthemeId: "history:leaders",
    difficultyLevel: 1,
    shortTitle: "Premiers présidents américains",
    questionText: "Quels sont les neuf premiers présidents des États-Unis ?",
    answers: [
      "George Washington",
      "John Adams",
      "Thomas Jefferson",
      "James Madison",
      "James Monroe",
      "John Quincy Adams",
      "Andrew Jackson",
      "Martin Van Buren",
      "William Henry Harrison",
    ],
    sources: [US_GOV],
  }),
  q({
    id: "easy-neuf-pharaons-celebres",
    subthemeId: "history:antiquity",
    difficultyLevel: 1,
    shortTitle: "Pharaons célèbres",
    questionText: "Quels sont ces neuf pharaons majeurs de l’Égypte antique ?",
    answers: [
      "Khéops",
      "Khéphren",
      "Mykérinos",
      "Hatchepsout",
      "Akhenaton",
      "Toutânkhamon",
      "Séthi Ier",
      "Ramsès II",
      "Cléopâtre VII",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendus les neuf souverains nommément proposés par cette sélection pédagogique.",
  }),
  q({
    id: "easy-neuf-croisades-numerotees",
    subthemeId: "history:middle-ages",
    difficultyLevel: 1,
    shortTitle: "Croisades numérotées",
    questionText:
      "Comment nomme-t-on les neuf croisades traditionnellement numérotées vers la Terre sainte ?",
    answers: [
      "Première croisade",
      "Deuxième croisade",
      "Troisième croisade",
      "Quatrième croisade",
      "Cinquième croisade",
      "Sixième croisade",
      "Septième croisade",
      "Huitième croisade",
      "Neuvième croisade",
    ],
    sources: [BRITANNICA],
  }),
  q({
    id: "easy-neuf-decennies-xxe-siecle",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 1,
    shortTitle: "Décennies du XXe siècle",
    questionText: "Quelles sont les neuf décennies allant des années 1900 aux années 1980 ?",
    answers: [
      "Années 1900",
      "Années 1910",
      "Années 1920",
      "Années 1930",
      "Années 1940",
      "Années 1950",
      "Années 1960",
      "Années 1970",
      "Années 1980",
    ],
    sources: [BRITANNICA],
  }),
  q({
    id: "easy-neuf-rois-anglais-1066",
    subthemeId: "history:leaders",
    difficultyLevel: 1,
    shortTitle: "Rois anglais après 1066",
    questionText:
      "Quels sont les neuf premiers rois d’Angleterre à partir de Guillaume le Conquérant, sans compter Mathilde ?",
    answers: [
      "Guillaume Ier",
      "Guillaume II",
      "Henri Ier",
      "Étienne",
      "Henri II",
      "Richard Ier",
      "Jean sans Terre",
      "Henri III",
      "Édouard Ier",
    ],
    sources: [UK],
  }),
  q({
    id: "easy-neuf-civilisations-antiques",
    subthemeId: "history:civilizations",
    difficultyLevel: 1,
    shortTitle: "Civilisations antiques",
    questionText: "Quelles sont ces neuf grandes civilisations du monde antique ?",
    answers: [
      "Égypte antique",
      "Grèce antique",
      "Rome antique",
      "Mésopotamie",
      "Perse achéménide",
      "Civilisation de l’Indus",
      "Chine des Han",
      "Civilisation maya",
      "Civilisation phénicienne",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendues les neuf civilisations explicitement délimitées par cette sélection généraliste.",
  }),

  q({
    id: "medium-neuf-presidents-americains",
    subthemeId: "history:leaders",
    difficultyLevel: 2,
    shortTitle: "Présidents américains 10 à 18",
    questionText: "Quels sont les présidents des États-Unis classés du 10e au 18e ?",
    answers: [
      "John Tyler",
      "James K. Polk",
      "Zachary Taylor",
      "Millard Fillmore",
      "Franklin Pierce",
      "James Buchanan",
      "Abraham Lincoln",
      "Andrew Johnson",
      "Ulysses S. Grant",
    ],
    sources: [US_GOV],
  }),
  q({
    id: "medium-neuf-secretaires-generaux-onu",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 2,
    shortTitle: "Secrétaires généraux de l’ONU",
    questionText:
      "Quels sont les neuf secrétaires généraux de l’ONU, de Trygve Lie à António Guterres ?",
    answers: [
      "Trygve Lie",
      "Dag Hammarskjöld",
      "U Thant",
      "Kurt Waldheim",
      "Javier Pérez de Cuéllar",
      "Boutros Boutros-Ghali",
      "Kofi Annan",
      "Ban Ki-moon",
      "António Guterres",
    ],
    sources: [UN],
  }),
  q({
    id: "medium-neuf-pays-otan-1949",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 2,
    shortTitle: "Fondateurs européens de l’OTAN",
    questionText:
      "Quels sont les neuf pays européens parmi les douze membres fondateurs de l’OTAN en 1949 ?",
    answers: [
      "Belgique",
      "Danemark",
      "France",
      "Islande",
      "Italie",
      "Luxembourg",
      "Norvège",
      "Pays-Bas",
      "Royaume-Uni",
    ],
    sources: [NATO],
  }),
  q({
    id: "medium-neuf-pays-communaute-europeenne-1973",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 2,
    shortTitle: "Europe des Neuf",
    questionText: "Quels pays formaient l’Europe des Neuf après l’élargissement de 1973 ?",
    answers: [
      "Allemagne de l’Ouest",
      "Belgique",
      "Danemark",
      "France",
      "Irlande",
      "Italie",
      "Luxembourg",
      "Pays-Bas",
      "Royaume-Uni",
    ],
    sources: [EU],
  }),
  q({
    id: "medium-neuf-batailles-napoleoniennes",
    subthemeId: "history:modern-era",
    difficultyLevel: 2,
    shortTitle: "Batailles napoléoniennes",
    questionText:
      "Quelles sont ces neuf batailles majeures livrées par Napoléon Ier entre 1800 et 1815 ?",
    answers: [
      "Marengo",
      "Austerlitz",
      "Iéna",
      "Eylau",
      "Friedland",
      "Wagram",
      "Borodino",
      "Leipzig",
      "Waterloo",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendues les neuf batailles nommées dans cette sélection chronologique.",
  }),
  q({
    id: "medium-neuf-dynasties-chinoises",
    subthemeId: "history:civilizations",
    difficultyLevel: 2,
    shortTitle: "Dynasties chinoises",
    questionText:
      "Quelles sont ces neuf grandes dynasties de la Chine impériale, des Qin aux Qing ?",
    answers: ["Qin", "Han", "Sui", "Tang", "Song", "Yuan", "Ming", "Qing", "Jin"],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendues les neuf dynasties explicitement citées, sans prétendre à une succession exhaustive.",
  }),
  q({
    id: "medium-neuf-traites-historiques",
    subthemeId: "history:modern-era",
    difficultyLevel: 2,
    shortTitle: "Traités historiques",
    questionText: "Quels sont ces neuf traités de paix européens conclus entre 1648 et 1992 ?",
    answers: [
      "Westphalie",
      "Utrecht",
      "Paris de 1763",
      "Vienne",
      "Paris de 1856",
      "Versailles",
      "Trianon",
      "Rome",
      "Maastricht",
    ],
    sources: [BRITANNICA],
    qualificationRule: "Le nom usuel du traité ou de l’ensemble de traités est accepté.",
  }),

  q({
    id: "hard-neuf-laureats-nobel-paix-2000-2008",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 3,
    shortTitle: "Nobel de la paix 2000-2008",
    questionText: "Quels furent les neuf lauréats du prix Nobel de la paix de 2000 à 2008 ?",
    answers: [
      "Kim Dae-jung",
      "Organisation des Nations unies et Kofi Annan",
      "Jimmy Carter",
      "Shirin Ebadi",
      "Wangari Maathai",
      "Agence internationale de l’énergie atomique et Mohamed ElBaradei",
      "Muhammad Yunus et Grameen Bank",
      "GIEC et Al Gore",
      "Martti Ahtisaari",
    ],
    sources: [NOBEL],
    qualificationRule:
      "Une année compte comme une réponse; lorsque le prix fut partagé, les colauréats constituent ensemble cette réponse.",
  }),
  q({
    id: "hard-neuf-empereurs-byzantins-macedoniens",
    subthemeId: "history:middle-ages",
    difficultyLevel: 3,
    shortTitle: "Dynastie macédonienne",
    questionText:
      "Quels sont les neuf premiers empereurs byzantins de la dynastie macédonienne, de Basile Ier à Romain II ?",
    answers: [
      "Basile Ier",
      "Léon VI",
      "Alexandre",
      "Constantin VII",
      "Romain Ier Lécapène",
      "Christophe Lécapène",
      "Étienne Lécapène",
      "Constantin Lécapène",
      "Romain II",
    ],
    sources: [BRITANNICA],
  }),
  q({
    id: "hard-neuf-etats-confederes-initiaux",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 3,
    shortTitle: "États confédérés",
    questionText:
      "Quels furent les neuf premiers États à rejoindre les États confédérés d’Amérique en 1861 ?",
    answers: [
      "Caroline du Sud",
      "Mississippi",
      "Floride",
      "Alabama",
      "Géorgie",
      "Louisiane",
      "Texas",
      "Virginie",
      "Arkansas",
    ],
    sources: [BRITANNICA],
  }),
  q({
    id: "hard-neuf-membres-expedition-lewis-clark",
    subthemeId: "history:modern-era",
    difficultyLevel: 3,
    shortTitle: "Expédition Lewis et Clark",
    questionText:
      "Quels sont ces neuf membres ou compagnons célèbres de l’expédition Lewis et Clark ?",
    answers: [
      "Meriwether Lewis",
      "William Clark",
      "Sacagawea",
      "Toussaint Charbonneau",
      "York",
      "John Colter",
      "Patrick Gass",
      "George Drouillard",
      "Seaman",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendus les neuf participants ou compagnons nommés dans cette sélection historique.",
  }),
  q({
    id: "hard-neuf-marcheurs-lunaires",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 3,
    shortTitle: "Premiers marcheurs lunaires",
    questionText: "Quels sont les neuf premiers astronautes à avoir marché sur la Lune ?",
    answers: [
      "Neil Armstrong",
      "Buzz Aldrin",
      "Pete Conrad",
      "Alan Bean",
      "Alan Shepard",
      "Edgar Mitchell",
      "David Scott",
      "James Irwin",
      "John Young",
    ],
    sources: [NASA],
  }),
  q({
    id: "hard-neuf-rois-assyriens",
    subthemeId: "history:antiquity",
    difficultyLevel: 3,
    shortTitle: "Rois néo-assyriens",
    questionText: "Quels sont ces neuf souverains majeurs de l’Empire néo-assyrien ?",
    answers: [
      "Assurnasirpal II",
      "Salmanazar III",
      "Tiglath-Phalazar III",
      "Sargon II",
      "Sennachérib",
      "Assarhaddon",
      "Assurbanipal",
      "Shamash-shum-ukin",
      "Sin-shar-ishkun",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Sont attendus les neuf souverains nommés dans cette sélection consacrée à l’époque néo-assyrienne.",
  }),
];
