const source = (id, title, publisher, url, primary = false) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource: primary,
});
const q = (s) => ({
  themeId: "literature",
  qualificationRule:
    s.qualificationRule ??
    "Sont retenus les neuf livres, personnages ou lauréats exactement délimités dans la question.",
  explanation:
    s.explanation ?? "La bibliographie ou le palmarès cité confirme cet ensemble de neuf réponses.",
  ...s,
});
const bnf = (id, title, url) => source(id, title, "Bibliothèque nationale de France", url);
export const questions = [
  q({
    id: "easy-communaute-anneau",
    subthemeId: "literature:characters",
    difficultyLevel: 1,
    shortTitle: "La Communauté de l’Anneau",
    questionText: "Quels sont les neuf membres de la Communauté de l’Anneau ?",
    answers: [
      "Frodon Sacquet",
      "Sam Gamegie",
      "Meriadoc Brandebouc",
      "Peregrin Touque",
      "Gandalf",
      "Aragorn",
      "Boromir",
      "Legolas",
      "Gimli",
    ],
    sources: [
      source(
        "tolkien-fellowship",
        "The Fellowship of the Ring",
        "The Tolkien Estate",
        "https://www.tolkienestate.com/writing/the-lord-of-the-rings/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-harry-potter-neuf-livres",
    subthemeId: "literature:novels",
    difficultyLevel: 1,
    shortTitle: "Livres de Harry Potter",
    questionText:
      "Quels sont les sept romans Harry Potter et les deux livres de la bibliothèque de Poudlard publiés en 2001 ?",
    answers: [
      "Harry Potter à l’école des sorciers",
      "Harry Potter et la Chambre des secrets",
      "Harry Potter et le Prisonnier d’Azkaban",
      "Harry Potter et la Coupe de feu",
      "Harry Potter et l’Ordre du Phénix",
      "Harry Potter et le Prince de sang-mêlé",
      "Harry Potter et les Reliques de la Mort",
      "Le Quidditch à travers les âges",
      "Les Animaux fantastiques",
    ],
    sources: [
      source(
        "bloomsbury-harry-potter",
        "Harry Potter books",
        "Bloomsbury Publishing",
        "https://www.bloomsbury.com/uk/discover/harry-potter/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-poirot-neuf-premiers-livres",
    subthemeId: "literature:novels",
    difficultyLevel: 1,
    shortTitle: "Les débuts de Poirot",
    questionText:
      "Quels sont les neuf premiers livres d’Agatha Christie mettant en scène Hercule Poirot ?",
    answers: [
      "La Mystérieuse Affaire de Styles",
      "Le Crime du golf",
      "Les Enquêtes d’Hercule Poirot",
      "Le Meurtre de Roger Ackroyd",
      "Les Quatre",
      "Le Train bleu",
      "La Maison du péril",
      "Le Couteau sur la nuque",
      "Le Crime de l’Orient-Express",
    ],
    sources: [
      source(
        "christie-poirot",
        "Hercule Poirot stories",
        "Agatha Christie Limited",
        "https://www.agathachristie.com/characters/hercule-poirot",
        true,
      ),
    ],
  }),
  q({
    id: "easy-rougon-macquart-neuf-premiers",
    subthemeId: "literature:novels",
    difficultyLevel: 1,
    shortTitle: "Les Rougon-Macquart",
    questionText:
      "Quels sont les neuf premiers romans des Rougon-Macquart dans l’ordre de publication ?",
    answers: [
      "La Fortune des Rougon",
      "La Curée",
      "Le Ventre de Paris",
      "La Conquête de Plassans",
      "La Faute de l’abbé Mouret",
      "Son Excellence Eugène Rougon",
      "L’Assommoir",
      "Une page d’amour",
      "Nana",
    ],
    sources: [
      bnf(
        "bnf-zola-rougon",
        "Émile Zola et les Rougon-Macquart",
        "https://data.bnf.fr/fr/11909069/emile_zola/",
      ),
    ],
  }),
  q({
    id: "easy-stephen-king-neuf-premiers",
    subthemeId: "literature:authors",
    difficultyLevel: 1,
    shortTitle: "Les débuts de Stephen King",
    questionText:
      "Quels sont les neuf premiers romans publiés par Stephen King sous son propre nom ?",
    answers: [
      "Carrie",
      "Salem",
      "Shining",
      "Le Fléau",
      "Dead Zone",
      "Charlie",
      "Cujo",
      "Christine",
      "Simetierre",
    ],
    sources: [
      source(
        "king-books",
        "Written works — novels",
        "Stephen King",
        "https://stephenking.com/works/novel/index.html",
        true,
      ),
    ],
    exclusionNotes: "Les romans publiés sous le pseudonyme Richard Bachman sont exclus.",
  }),
  q({
    id: "easy-james-bond-neuf-premiers-livres",
    subthemeId: "literature:novels",
    difficultyLevel: 1,
    shortTitle: "James Bond par Fleming",
    questionText: "Quels sont les neuf premiers livres de James Bond écrits par Ian Fleming ?",
    answers: [
      "Casino Royale",
      "Vivre et laisser mourir",
      "Moonraker",
      "Les diamants sont éternels",
      "Bons Baisers de Russie",
      "James Bond contre Dr No",
      "Goldfinger",
      "Bons Baisers de Paris",
      "Opération Tonnerre",
    ],
    sources: [
      source(
        "fleming-bond-books",
        "The James Bond books",
        "Ian Fleming Publications",
        "https://ianfleming.com/books/",
        true,
      ),
    ],
  }),
  q({
    id: "easy-disque-monde-neuf-premiers",
    subthemeId: "literature:novels",
    difficultyLevel: 1,
    shortTitle: "Les débuts du Disque-monde",
    questionText: "Quels sont les neuf premiers romans des Annales du Disque-monde ?",
    answers: [
      "La Huitième Couleur",
      "Le Huitième Sortilège",
      "La Huitième Fille",
      "Mortimer",
      "Sourcellerie",
      "Trois Sœurcières",
      "Pyramides",
      "Au guet !",
      "Éric",
    ],
    sources: [
      source(
        "pratchett-discworld",
        "Discworld novels",
        "Terry Pratchett Estate",
        "https://www.terrypratchettbooks.com/books/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-romans-expanse",
    subthemeId: "literature:novels",
    difficultyLevel: 2,
    shortTitle: "The Expanse",
    questionText: "Quels sont les neuf romans principaux de la saga The Expanse ?",
    answers: [
      "L’Éveil du Léviathan",
      "La Guerre de Caliban",
      "La Porte d’Abaddon",
      "Les Feux de Cibola",
      "Les Jeux de Némésis",
      "Les Cendres de Babylone",
      "Le Soulèvement de Persépolis",
      "La Colère de Tiamat",
      "La Chute du Léviathan",
    ],
    sources: [
      source(
        "orbit-expanse",
        "The Expanse series",
        "Orbit Books",
        "https://www.orbitbooks.net/series/the-expanse/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-goncourt-2015-2023",
    subthemeId: "literature:awards",
    difficultyLevel: 2,
    shortTitle: "Prix Goncourt récents",
    questionText: "Quels romans ont reçu le prix Goncourt de 2015 à 2023 ?",
    answers: [
      "Boussole",
      "Chanson douce",
      "L’Ordre du jour",
      "Leurs enfants après eux",
      "Tous les hommes n’habitent pas le monde de la même façon",
      "L’Anomalie",
      "La Plus Secrète Mémoire des hommes",
      "Vivre vite",
      "Veiller sur elle",
    ],
    sources: [
      source(
        "goncourt-laureats",
        "Les lauréats du prix Goncourt",
        "Académie Goncourt",
        "https://www.academiegoncourt.com/tous-les-laureats-prix-goncourt",
        true,
      ),
    ],
  }),
  q({
    id: "medium-hugo-roman-2015-2023",
    subthemeId: "literature:awards",
    difficultyLevel: 2,
    shortTitle: "Prix Hugo du meilleur roman",
    questionText: "Quels romans ont reçu le prix Hugo du meilleur roman de 2015 à 2023 ?",
    answers: [
      "Le Problème à trois corps",
      "La Cinquième Saison",
      "La Porte de cristal",
      "Les Cieux pétrifiés",
      "Vers les étoiles",
      "Un souvenir nommé empire",
      "Effet de réseau",
      "Une désolation nommée paix",
      "Nettle and Bone",
    ],
    sources: [
      source(
        "hugo-novels",
        "Hugo Award — Best Novel",
        "World Science Fiction Society",
        "https://www.thehugoawards.org/hugo-history/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-maigret-neuf-premiers",
    subthemeId: "literature:characters",
    difficultyLevel: 2,
    shortTitle: "Les débuts de Maigret",
    questionText:
      "Quels sont les neuf premiers romans de Georges Simenon consacrés au commissaire Maigret ?",
    answers: [
      "Pietr-le-Letton",
      "Le Charretier de la Providence",
      "Monsieur Gallet, décédé",
      "Le Pendu de Saint-Pholien",
      "La Tête d’un homme",
      "Le Chien jaune",
      "La Nuit du carrefour",
      "Un crime en Hollande",
      "Au rendez-vous des Terre-Neuvas",
    ],
    sources: [
      source(
        "simenon-maigret",
        "Les romans Maigret",
        "Georges Simenon Limited",
        "https://www.simenon.com/livres/maigret/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-moliere-neuf-premieres-pieces",
    subthemeId: "literature:poetry-theatre",
    difficultyLevel: 2,
    shortTitle: "Les débuts de Molière",
    questionText:
      "Quelles sont les neuf premières pièces de Molière conservées et datées de L’Étourdi à La Critique de l’École des femmes ?",
    answers: [
      "L’Étourdi ou les Contretemps",
      "Le Dépit amoureux",
      "Les Précieuses ridicules",
      "Sganarelle ou le Cocu imaginaire",
      "Dom Garcie de Navarre",
      "L’École des maris",
      "Les Fâcheux",
      "L’École des femmes",
      "La Critique de l’École des femmes",
    ],
    sources: [
      bnf("bnf-moliere-oeuvres", "Molière — œuvres", "https://data.bnf.fr/fr/11916316/moliere/"),
    ],
  }),
  q({
    id: "medium-jack-reacher-neuf-premiers",
    subthemeId: "literature:novels",
    difficultyLevel: 2,
    shortTitle: "Les débuts de Jack Reacher",
    questionText: "Quels sont les neuf premiers romans de la série Jack Reacher ?",
    answers: [
      "Du fond de l’abîme",
      "Les Chemins de la perdition",
      "Ne pardonne jamais",
      "Le Visiteur",
      "La Faute à pas de chance",
      "Carmen à mort",
      "Ne t’enfuis plus",
      "L’Ennemi",
      "Un visiteur pour Ophélie",
    ],
    sources: [
      source(
        "lee-child-books",
        "Jack Reacher books in order",
        "Lee Child",
        "https://www.jackreacher.com/us/books/",
        true,
      ),
    ],
  }),
  q({
    id: "medium-rebus-neuf-premiers",
    subthemeId: "literature:novels",
    difficultyLevel: 2,
    shortTitle: "Les débuts de Rebus",
    questionText:
      "Quels sont les neuf premiers romans de Ian Rankin mettant en scène l’inspecteur Rebus ?",
    answers: [
      "L’Étrangleur d’Édimbourg",
      "Le Fond de l’enfer",
      "Rebus et le Loup-garou de Londres",
      "Piège pour un élu",
      "Une bonne pendaison",
      "Le Carnet noir",
      "Causes mortelles",
      "Ainsi saigne-t-il",
      "L’Ombre du tueur",
    ],
    sources: [
      source(
        "rankin-rebus",
        "Inspector Rebus books",
        "Ian Rankin",
        "https://www.ianrankin.net/landing-page/ian-rankin-books/",
        true,
      ),
    ],
  }),
  q({
    id: "hard-cercles-enfer-dante",
    subthemeId: "literature:poetry-theatre",
    difficultyLevel: 3,
    shortTitle: "L’Enfer de Dante",
    questionText: "Quels péchés ou états définissent les neuf cercles de l’Enfer de Dante ?",
    answers: [
      "Limbes",
      "Luxure",
      "Gourmandise",
      "Avarice et prodigalité",
      "Colère et acédie",
      "Hérésie",
      "Violence",
      "Fraude",
      "Trahison",
    ],
    sources: [
      source(
        "dante-worlds",
        "Dante’s Inferno",
        "Princeton University",
        "https://dante.princeton.edu/",
        false,
      ),
    ],
  }),
  q({
    id: "hard-nobel-neuf-premiers-laureats",
    subthemeId: "literature:awards",
    difficultyLevel: 3,
    shortTitle: "Premiers Nobel de littérature",
    questionText:
      "Quelles sont les neuf premières attributions du prix Nobel de littérature, de 1901 à 1909 ?",
    answers: [
      "Sully Prudhomme",
      "Theodor Mommsen",
      "Bjørnstjerne Bjørnson",
      "Frédéric Mistral et José Echegaray",
      "Henryk Sienkiewicz",
      "Giosuè Carducci",
      "Rudyard Kipling",
      "Rudolf Christoph Eucken",
      "Selma Lagerlöf",
    ],
    sources: [
      source(
        "nobel-literature-all",
        "All Nobel Prizes in Literature",
        "Nobel Prize Outreach",
        "https://www.nobelprize.org/prizes/lists/all-nobel-prizes-in-literature/",
        true,
      ),
    ],
  }),
  q({
    id: "hard-pulitzer-roman-neuf-premiers",
    subthemeId: "literature:awards",
    difficultyLevel: 3,
    shortTitle: "Premiers Pulitzer du roman",
    questionText:
      "Quels sont les neuf premiers romans lauréats du prix Pulitzer du roman, de 1918 à 1927 ?",
    answers: [
      "His Family",
      "The Magnificent Ambersons",
      "The Age of Innocence",
      "Alice Adams",
      "One of Ours",
      "The Able McLaughlins",
      "So Big",
      "Arrowsmith",
      "Early Autumn",
    ],
    sources: [
      source(
        "pulitzer-novel",
        "Novel winners and finalists",
        "The Pulitzer Prizes",
        "https://www.pulitzer.org/prize-winners-by-category/261",
        true,
      ),
    ],
  }),
  q({
    id: "hard-modiano-neuf-premiers",
    subthemeId: "literature:authors",
    difficultyLevel: 3,
    shortTitle: "Les débuts de Modiano",
    questionText:
      "Quels sont les neuf premiers romans de Patrick Modiano, de La Place de l’Étoile à Quartier perdu ?",
    answers: [
      "La Place de l’Étoile",
      "La Ronde de nuit",
      "Les Boulevards de ceinture",
      "Villa triste",
      "Livret de famille",
      "Rue des Boutiques obscures",
      "Une jeunesse",
      "Memory Lane",
      "Quartier perdu",
    ],
    sources: [
      bnf(
        "bnf-modiano",
        "Patrick Modiano — œuvres",
        "https://data.bnf.fr/fr/11916399/patrick_modiano/",
      ),
    ],
  }),
  q({
    id: "hard-woolf-neuf-romans",
    subthemeId: "literature:authors",
    difficultyLevel: 3,
    shortTitle: "Romans de Virginia Woolf",
    questionText:
      "Quels sont les neuf romans de Virginia Woolf, de La Traversée des apparences à Entre les actes ?",
    answers: [
      "La Traversée des apparences",
      "Nuit et Jour",
      "La Chambre de Jacob",
      "Mrs Dalloway",
      "La Promenade au phare",
      "Orlando",
      "Les Vagues",
      "Les Années",
      "Entre les actes",
    ],
    sources: [
      source(
        "woolf-works",
        "Virginia Woolf bibliography",
        "British Library",
        "https://www.bl.uk/people/virginia-woolf",
        false,
      ),
    ],
  }),
  q({
    id: "hard-booker-neuf-premiers-romans",
    subthemeId: "literature:awards",
    difficultyLevel: 3,
    shortTitle: "Premiers Booker Prize",
    questionText: "Quels sont les neuf premiers romans lauréats du Booker Prize, de 1969 à 1976 ?",
    answers: [
      "Something to Answer For",
      "The Elected Member",
      "In a Free State",
      "G.",
      "The Siege of Krishnapur",
      "The Conservationist",
      "Holiday",
      "Heat and Dust",
      "Saville",
    ],
    sources: [
      source(
        "booker-winners",
        "Booker Prize winners",
        "Booker Prize Foundation",
        "https://thebookerprizes.com/the-booker-library/prize-years",
        true,
      ),
    ],
    qualificationRule:
      "Sont retenus les neuf romans récompensés lors des huit premières éditions ; l’édition 1974 compte deux lauréats.",
  }),
];
