const source = (id, title, publisher, url, isPrimarySource = true) => ({ id, title, publisher, url, isPrimarySource });
const discography = (id, artist, url) => source(id, `${artist} — discographie`, artist, url);
const q = (spec) => ({ themeId: "music", qualificationRule: spec.qualificationRule ?? "Sont retenus les neuf albums, titres, artistes ou œuvres exactement délimités dans la question.", explanation: spec.explanation ?? "La discographie ou le palmarès cité confirme cet ensemble de neuf réponses.", ...spec });

export const questions = [
  q({ id: "easy-taylor-neuf-albums", subthemeId: "music:artists-groups", difficultyLevel: 1, shortTitle: "Taylor Swift", questionText: "Quels sont les neuf premiers albums studio de Taylor Swift, jusqu’à Evermore ?", answers: ["Taylor Swift", "Fearless", "Speak Now", "Red", "1989", "Reputation", "Lover", "Folklore", "Evermore"], sources: [discography("taylor-discography", "Taylor Swift", "https://www.taylorswift.com/music/")] }),
  q({ id: "easy-beatles-neuf-premiers-uk", subthemeId: "music:albums-songs", difficultyLevel: 1, shortTitle: "Albums des Beatles", questionText: "Quels sont les neuf premiers albums britanniques des Beatles, de Please Please Me à l’Album blanc ?", answers: ["Please Please Me", "With the Beatles", "A Hard Day’s Night", "Beatles for Sale", "Help!", "Rubber Soul", "Revolver", "Sgt. Pepper’s Lonely Hearts Club Band", "The Beatles"], sources: [discography("beatles-discography", "The Beatles", "https://www.thebeatles.com/albums")] }),
  q({ id: "easy-queen-neuf-premiers", subthemeId: "music:albums-songs", difficultyLevel: 1, shortTitle: "Albums de Queen", questionText: "Quels sont les neuf premiers albums de Queen, de Queen à Flash Gordon ?", answers: ["Queen", "Queen II", "Sheer Heart Attack", "A Night at the Opera", "A Day at the Races", "News of the World", "Jazz", "The Game", "Flash Gordon"], sources: [discography("queen-discography", "Queen", "https://www.queenonline.com/music")] }),
  q({ id: "easy-madonna-neuf-premiers", subthemeId: "music:albums-songs", difficultyLevel: 1, shortTitle: "Albums de Madonna", questionText: "Quels sont les neuf premiers albums studio de Madonna, de Madonna à American Life ?", answers: ["Madonna", "Like a Virgin", "True Blue", "Like a Prayer", "Erotica", "Bedtime Stories", "Ray of Light", "Music", "American Life"], sources: [discography("madonna-discography", "Madonna", "https://www.madonna.com/discography/")] }),
  q({ id: "easy-bowie-neuf-premiers", subthemeId: "music:albums-songs", difficultyLevel: 1, shortTitle: "Albums de Bowie", questionText: "Quels sont les neuf premiers albums studio de David Bowie, de David Bowie à Young Americans ?", answers: ["David Bowie", "Space Oddity", "The Man Who Sold the World", "Hunky Dory", "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "Aladdin Sane", "Pin Ups", "Diamond Dogs", "Young Americans"], sources: [discography("bowie-discography", "David Bowie", "https://www.davidbowie.com/albums")] }),
  q({ id: "easy-metallica-neuf-premiers", subthemeId: "music:albums-songs", difficultyLevel: 1, shortTitle: "Albums de Metallica", questionText: "Quels sont les neuf premiers albums studio de Metallica, de Kill ’Em All à Death Magnetic ?", answers: ["Kill ’Em All", "Ride the Lightning", "Master of Puppets", "…And Justice for All", "Metallica", "Load", "Reload", "St. Anger", "Death Magnetic"], sources: [discography("metallica-discography", "Metallica", "https://www.metallica.com/releases/albums/")] }),
  q({ id: "easy-eurovision-gagnants-2014-2023", subthemeId: "music:awards-festivals", difficultyLevel: 1, shortTitle: "Vainqueurs de l’Eurovision", questionText: "Quels artistes ont remporté les neuf éditions de l’Eurovision organisées de 2014 à 2023 ?", answers: ["Conchita Wurst", "Måns Zelmerlöw", "Jamala", "Salvador Sobral", "Netta", "Duncan Laurence", "Måneskin", "Kalush Orchestra", "Loreen"], sources: [source("eurovision-winners", "Eurovision Song Contest winners", "European Broadcasting Union", "https://eurovision.tv/history/winners")], exclusionNotes: "Aucune édition n’a eu lieu en 2020 ; les neuf éditions organisées dans l’intervalle sont retenues." }),

  q({ id: "medium-thriller-neuf-titres", subthemeId: "music:albums-songs", difficultyLevel: 2, shortTitle: "Thriller", questionText: "Quels sont les neuf titres de l’édition originale de l’album Thriller de Michael Jackson ?", answers: ["Wanna Be Startin’ Somethin’", "Baby Be Mine", "The Girl Is Mine", "Thriller", "Beat It", "Billie Jean", "Human Nature", "P.Y.T. (Pretty Young Thing)", "The Lady in My Life"], sources: [discography("michael-jackson-thriller", "Michael Jackson", "https://www.michaeljackson.com/music/thriller/")] }),
  q({ id: "medium-wu-tang", subthemeId: "music:artists-groups", difficultyLevel: 2, shortTitle: "Wu-Tang Clan", questionText: "Quels sont les neuf membres originels du Wu-Tang Clan ?", answers: ["RZA", "GZA", "Ol’ Dirty Bastard", "Method Man", "Raekwon", "Ghostface Killah", "Inspectah Deck", "U-God", "Masta Killa"], sources: [source("wu-tang-members", "Wu-Tang Clan biography", "Rock & Roll Hall of Fame", "https://rockhall.com/inductees/wu-tang-clan/", false)] }),
  q({ id: "medium-prince-neuf-premiers", subthemeId: "music:artists-groups", difficultyLevel: 2, shortTitle: "Albums de Prince", questionText: "Quels sont les neuf premiers albums studio de Prince, de For You à Sign o’ the Times ?", answers: ["For You", "Prince", "Dirty Mind", "Controversy", "1999", "Purple Rain", "Around the World in a Day", "Parade", "Sign o’ the Times"], sources: [discography("prince-discography", "Prince", "https://www.prince.com/music")] }),
  q({ id: "medium-u2-neuf-premiers", subthemeId: "music:artists-groups", difficultyLevel: 2, shortTitle: "Albums de U2", questionText: "Quels sont les neuf premiers albums studio de U2, de Boy à Pop ?", answers: ["Boy", "October", "War", "The Unforgettable Fire", "The Joshua Tree", "Rattle and Hum", "Achtung Baby", "Zooropa", "Pop"], sources: [discography("u2-discography", "U2", "https://www.u2.com/music")] }),
  q({ id: "medium-radiohead-neuf-albums", subthemeId: "music:artists-groups", difficultyLevel: 2, shortTitle: "Albums de Radiohead", questionText: "Quels sont les neuf albums studio de Radiohead parus de Pablo Honey à A Moon Shaped Pool ?", answers: ["Pablo Honey", "The Bends", "OK Computer", "Kid A", "Amnesiac", "Hail to the Thief", "In Rainbows", "The King of Limbs", "A Moon Shaped Pool"], sources: [discography("radiohead-discography", "Radiohead", "https://www.radiohead.com/library/")] }),
  q({ id: "medium-abba-neuf-albums", subthemeId: "music:artists-groups", difficultyLevel: 2, shortTitle: "Albums d’ABBA", questionText: "Quels sont les neuf albums studio d’ABBA, de Ring Ring à Voyage ?", answers: ["Ring Ring", "Waterloo", "ABBA", "Arrival", "The Album", "Voulez-Vous", "Super Trouper", "The Visitors", "Voyage"], sources: [discography("abba-discography", "ABBA", "https://abbasite.com/discography/")] }),
  q({ id: "medium-grammy-album-2015-2023", subthemeId: "music:awards-festivals", difficultyLevel: 2, shortTitle: "Grammy de l’album", questionText: "Quels albums ont gagné le Grammy de l’album de l’année lors des cérémonies 2015 à 2023 ?", answers: ["Morning Phase", "1989", "25", "24K Magic", "Golden Hour", "When We All Fall Asleep, Where Do We Go?", "Folklore", "We Are", "Harry’s House"], sources: [source("grammy-album-winners", "Album of the Year — winners", "Recording Academy", "https://grammy.com/awards/winners-nominees/40")] }),
  q({ id: "hard-symphonies-beethoven", subthemeId: "music:classical-music", difficultyLevel: 3, shortTitle: "Symphonies de Beethoven", questionText: "Quels numéros composent l’intégrale des neuf symphonies de Beethoven ?", answers: ["Symphonie no 1", "Symphonie no 2", "Symphonie no 3", "Symphonie no 4", "Symphonie no 5", "Symphonie no 6", "Symphonie no 7", "Symphonie no 8", "Symphonie no 9"], sources: [source("beethoven-symphonies", "Beethoven: the nine symphonies", "Beethoven-Haus Bonn", "https://www.beethoven.de/en/g/Beethoven-symphonies")], qualificationRule: "Sont acceptées les désignations des symphonies par leur numéro, de 1 à 9." }),
  q({ id: "hard-kraftwerk-neuf-premiers", subthemeId: "music:genres", difficultyLevel: 3, shortTitle: "Albums de Kraftwerk", questionText: "Quels sont les neuf premiers albums studio de Kraftwerk, de Kraftwerk à Electric Café ?", answers: ["Kraftwerk", "Kraftwerk 2", "Ralf und Florian", "Autobahn", "Radio-Activity", "Trans-Europe Express", "The Man-Machine", "Computer World", "Electric Café"], sources: [discography("kraftwerk-discography", "Kraftwerk", "https://kraftwerk.com/discography/")] }),
  q({ id: "hard-nick-cave-neuf-premiers", subthemeId: "music:artists-groups", difficultyLevel: 3, shortTitle: "Nick Cave and the Bad Seeds", questionText: "Quels sont les neuf premiers albums studio de Nick Cave and the Bad Seeds ?", answers: ["From Her to Eternity", "The Firstborn Is Dead", "Kicking Against the Pricks", "Your Funeral… My Trial", "Tender Prey", "The Good Son", "Henry’s Dream", "Let Love In", "Murder Ballads"], sources: [discography("nick-cave-discography", "Nick Cave", "https://www.nickcave.com/music/")] }),
  q({ id: "hard-pj-harvey-neuf-premiers", subthemeId: "music:artists-groups", difficultyLevel: 3, shortTitle: "Albums de PJ Harvey", questionText: "Quels sont les neuf premiers albums studio de PJ Harvey, de Dry à The Hope Six Demolition Project ?", answers: ["Dry", "Rid of Me", "To Bring You My Love", "Is This Desire?", "Stories from the City, Stories from the Sea", "Uh Huh Her", "White Chalk", "Let England Shake", "The Hope Six Demolition Project"], sources: [discography("pj-harvey-discography", "PJ Harvey", "https://pjharvey.net/music/")] }),
  q({ id: "hard-bjork-neuf-internationaux", subthemeId: "music:genres", difficultyLevel: 3, shortTitle: "Albums de Björk", questionText: "Quels sont les neuf premiers albums studio internationaux de Björk, de Debut à Utopia ?", answers: ["Debut", "Post", "Homogenic", "Vespertine", "Medúlla", "Volta", "Biophilia", "Vulnicura", "Utopia"], sources: [discography("bjork-discography", "Björk", "https://bjork.com/music/")], exclusionNotes: "L’album islandais Björk, enregistré enfant en 1977, précède sa carrière internationale et est exclu." }),
  q({ id: "hard-joni-mitchell-neuf-premiers", subthemeId: "music:genres", difficultyLevel: 3, shortTitle: "Albums de Joni Mitchell", questionText: "Quels sont les neuf premiers albums studio de Joni Mitchell, de Song to a Seagull à Don Juan’s Reckless Daughter ?", answers: ["Song to a Seagull", "Clouds", "Ladies of the Canyon", "Blue", "For the Roses", "Court and Spark", "The Hissing of Summer Lawns", "Hejira", "Don Juan’s Reckless Daughter"], sources: [discography("joni-mitchell-discography", "Joni Mitchell", "https://jonimitchell.com/music/albums.cfm")] }),
];
