const source = (id, title, publisher, url, isPrimarySource = false) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});
const THEOI = source(
  "theoi-greek-mythology-pack",
  "Theoi Greek Mythology",
  "Theoi Project",
  "https://www.theoi.com/",
);
const BRITANNICA = source(
  "britannica-mythology-pack",
  "Myth",
  "Encyclopaedia Britannica",
  "https://www.britannica.com/topic/myth",
);
const MET = source(
  "met-egyptian-gods",
  "Egyptian deities",
  "The Metropolitan Museum of Art",
  "https://www.metmuseum.org/toah/hd/deit/hd_deit.htm",
);
const NORSE = source(
  "world-history-norse-mythology",
  "Norse Mythology",
  "World History Encyclopedia",
  "https://www.worldhistory.org/Norse_Mythology/",
);
const POETIC_EDDA = source(
  "sacred-texts-poetic-edda",
  "The Poetic Edda",
  "Internet Sacred Text Archive",
  "https://sacred-texts.com/neu/poe/index.htm",
  true,
);
const q = (spec) => ({
  themeId: "mythology-legends",
  qualificationRule:
    spec.qualificationRule ??
    "Les neuf noms correspondent exactement aux figures ou éléments demandés.",
  explanation:
    spec.explanation ?? "La liste suit la tradition mythologique indiquée et la source citée.",
  ...spec,
});

export const questions = [
  q({
    id: "easy-neuf-travaux-heracles",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 1,
    shortTitle: "Travaux d’Héraclès",
    questionText: "Quels sont les neuf premiers travaux d’Héraclès dans leur ordre traditionnel ?",
    answers: [
      "Lion de Némée",
      "Hydre de Lerne",
      "Biche de Cérynie",
      "Sanglier d’Érymanthe",
      "Écuries d’Augias",
      "Oiseaux du lac Stymphale",
      "Taureau de Crète",
      "Juments de Diomède",
      "Ceinture d’Hippolyte",
    ],
    sources: [THEOI],
  }),
  q({
    id: "easy-equivalents-romains-dieux-grecs",
    subthemeId: "mythology-legends:roman-mythology",
    difficultyLevel: 1,
    shortTitle: "Dieux grecs et romains",
    questionText:
      "Quels sont les équivalents romains de Zeus, Héra, Poséidon, Arès, Aphrodite, Athéna, Hermès, Artémis et Héphaïstos ?",
    answers: [
      "Jupiter",
      "Junon",
      "Neptune",
      "Mars",
      "Vénus",
      "Minerve",
      "Mercure",
      "Diane",
      "Vulcain",
    ],
    sources: [BRITANNICA],
    qualificationRule: "Une divinité romaine est attendue pour chaque nom grec, dans l’ordre.",
  }),
  q({
    id: "easy-creatures-mythologiques-neuf",
    subthemeId: "mythology-legends:heroes-creatures",
    difficultyLevel: 1,
    shortTitle: "Créatures célèbres",
    questionText: "Quelles sont ces neuf créatures célèbres de la mythologie grecque ?",
    answers: [
      "Minotaure",
      "Méduse",
      "Cerbère",
      "Hydre de Lerne",
      "Chimère",
      "Sphinx",
      "Cyclope",
      "Pégase",
      "Sirènes",
    ],
    sources: [THEOI],
    qualificationRule: "Sont attendues les neuf créatures explicitement sélectionnées.",
  }),
  q({
    id: "easy-heros-guerre-troie",
    subthemeId: "mythology-legends:heroes-creatures",
    difficultyLevel: 1,
    shortTitle: "Héros de la guerre de Troie",
    questionText: "Quels sont ces neuf héros grecs ou troyens de la guerre de Troie ?",
    answers: [
      "Achille",
      "Hector",
      "Ulysse",
      "Ajax",
      "Énée",
      "Pâris",
      "Agamemnon",
      "Ménélas",
      "Diomède",
    ],
    sources: [THEOI],
    qualificationRule: "Sont attendus les neuf héros nommés dans cette sélection homérique.",
  }),
  q({
    id: "easy-dieux-egyptiens-attributs",
    subthemeId: "mythology-legends:egyptian-mythology",
    difficultyLevel: 1,
    shortTitle: "Dieux égyptiens",
    questionText:
      "Quels dieux égyptiens associe-t-on au soleil, à la momification, à la magie maternelle, au monde des morts, au ciel, à la sagesse, au chaos, à la guerre-lionne et à la fertilité du Nil ?",
    answers: ["Rê", "Anubis", "Isis", "Osiris", "Horus", "Thot", "Seth", "Sekhmet", "Hâpy"],
    sources: [MET],
    qualificationRule: "Une divinité est attendue pour chaque domaine, dans l’ordre.",
  }),
  q({
    id: "easy-objets-mythologie-grecque",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 1,
    shortTitle: "Objets mythiques grecs",
    questionText: "Quels sont ces neuf objets célèbres de la mythologie grecque ?",
    answers: [
      "Toison d’or",
      "Boîte de Pandore",
      "Égide",
      "Foudre de Zeus",
      "Trident de Poséidon",
      "Casque d’Hadès",
      "Sandales ailées d’Hermès",
      "Arc d’Artémis",
      "Fil d’Ariane",
    ],
    sources: [THEOI],
    qualificationRule: "Sont attendus les neuf objets explicitement sélectionnés.",
  }),
  q({
    id: "easy-figures-nordiques-celebres",
    subthemeId: "mythology-legends:norse-mythology",
    difficultyLevel: 1,
    shortTitle: "Figures nordiques",
    questionText: "Quels sont ces neuf dieux ou figures majeures de la mythologie nordique ?",
    answers: ["Odin", "Thor", "Loki", "Frigg", "Freyja", "Freyr", "Týr", "Heimdall", "Baldr"],
    sources: [NORSE],
    qualificationRule: "Sont attendues les neuf figures explicitement sélectionnées.",
  }),

  q({
    id: "medium-enfants-cronos-rhea",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 2,
    shortTitle: "Descendance de Cronos",
    questionText:
      "Quels sont les six enfants de Cronos et Rhéa, auxquels s’ajoutent les trois Cyclopes libérés par Zeus ?",
    answers: [
      "Hestia",
      "Déméter",
      "Héra",
      "Hadès",
      "Poséidon",
      "Zeus",
      "Brontès",
      "Stéropès",
      "Argès",
    ],
    sources: [THEOI],
  }),
  q({
    id: "medium-argonautes-neuf",
    subthemeId: "mythology-legends:heroes-creatures",
    difficultyLevel: 2,
    shortTitle: "Argonautes",
    questionText: "Quels sont ces neuf membres célèbres de l’équipage des Argonautes ?",
    answers: [
      "Jason",
      "Héraclès",
      "Orphée",
      "Castor",
      "Pollux",
      "Pélée",
      "Télamon",
      "Méléagre",
      "Atalante",
    ],
    sources: [THEOI],
    qualificationRule: "Sont attendus les neuf Argonautes nommés dans cette sélection.",
  }),
  q({
    id: "medium-rois-mythiques-grecs",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 2,
    shortTitle: "Rois mythiques grecs",
    questionText:
      "De quelles cités ou régions mythiques sont rois Minos, Égée, Priam, Œdipe, Ménélas, Agamemnon, Ulysse, Pélée et Sisyphe ?",
    answers: [
      "Crète",
      "Athènes",
      "Troie",
      "Thèbes",
      "Sparte",
      "Mycènes",
      "Ithaque",
      "Phthie",
      "Corinthe",
    ],
    sources: [THEOI],
    qualificationRule: "Un royaume ou une cité est attendu pour chaque roi, dans l’ordre.",
  }),
  q({
    id: "medium-creatures-nordiques",
    subthemeId: "mythology-legends:norse-mythology",
    difficultyLevel: 2,
    shortTitle: "Créatures nordiques",
    questionText: "Quelles sont ces neuf créatures ou êtres de la mythologie nordique ?",
    answers: [
      "Fenrir",
      "Jörmungandr",
      "Sleipnir",
      "Níðhöggr",
      "Fáfnir",
      "Garm",
      "Ratatosk",
      "Audhumla",
      "Hræsvelgr",
    ],
    sources: [NORSE],
    qualificationRule: "Sont attendues les neuf créatures explicitement sélectionnées.",
  }),
  q({
    id: "medium-heros-legendes-monde",
    subthemeId: "mythology-legends:world-legends",
    difficultyLevel: 2,
    shortTitle: "Héros légendaires du monde",
    questionText:
      "À quelles cultures associe-t-on Gilgamesh, Sun Wukong, Maui, Cúchulainn, Sigurd, Rostam, Momotarō, Quetzalcóatl et Anansi ?",
    answers: [
      "Mésopotamie",
      "Chine",
      "Polynésie",
      "Irlande",
      "Scandinavie",
      "Perse",
      "Japon",
      "Mésoamérique",
      "Afrique de l’Ouest",
    ],
    sources: [BRITANNICA],
    qualificationRule:
      "Une aire culturelle principale est attendue pour chaque héros, dans l’ordre.",
  }),
  q({
    id: "medium-metamorphoses-zeus",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 2,
    shortTitle: "Métamorphoses de Zeus",
    questionText:
      "Sous quelles neuf formes Zeus apparaît-il dans ces récits : Europe, Léda, Danaé, Alcmène, Antiope, Égine, Ganymède, Io et Sémélé ?",
    answers: [
      "Europe — taureau",
      "Léda — cygne",
      "Danaé — pluie d’or",
      "Alcmène — Amphitryon",
      "Antiope — satyre",
      "Égine — aigle",
      "Ganymède — aigle",
      "Io — nuage",
      "Sémélé — apparence divine",
    ],
    sources: [THEOI],
    qualificationRule: "La forme, seule ou associée au personnage, est attendue pour chaque récit.",
  }),
  q({
    id: "medium-divinites-romaines-domaines",
    subthemeId: "mythology-legends:roman-mythology",
    difficultyLevel: 2,
    shortTitle: "Divinités romaines",
    questionText:
      "Quelles divinités romaines président au foyer, aux portes, aux moissons, aux fleurs, aux fruits, aux sources, aux limites, à la bonne foi et au hasard ?",
    answers: [
      "Vesta",
      "Janus",
      "Cérès",
      "Flore",
      "Pomone",
      "Fontus",
      "Terminus",
      "Fides",
      "Fortuna",
    ],
    sources: [BRITANNICA],
    qualificationRule: "Une divinité est attendue pour chaque domaine, dans l’ordre.",
  }),

  q({
    id: "hard-enneade-egyptienne",
    subthemeId: "mythology-legends:egyptian-mythology",
    difficultyLevel: 3,
    shortTitle: "Grande Ennéade",
    questionText: "Quelles sont les neuf divinités de la grande Ennéade d’Héliopolis ?",
    answers: ["Atoum", "Shou", "Tefnout", "Geb", "Nout", "Osiris", "Isis", "Seth", "Nephtys"],
    sources: [MET],
  }),
  q({
    id: "hard-muses-grecques",
    subthemeId: "mythology-legends:greek-mythology",
    difficultyLevel: 3,
    shortTitle: "Neuf Muses",
    questionText: "Quels sont les noms des neuf Muses de la mythologie grecque ?",
    answers: [
      "Calliope",
      "Clio",
      "Érato",
      "Euterpe",
      "Melpomène",
      "Polymnie",
      "Terpsichore",
      "Thalie",
      "Uranie",
    ],
    sources: [THEOI],
  }),
  q({
    id: "hard-neuf-mondes-nordiques",
    subthemeId: "mythology-legends:norse-mythology",
    difficultyLevel: 3,
    shortTitle: "Neuf mondes nordiques",
    questionText: "Quels sont les neuf mondes reliés par Yggdrasil dans la tradition nordique ?",
    answers: [
      "Ásgard",
      "Midgard",
      "Vanaheim",
      "Jötunheim",
      "Álfheim",
      "Svartálfaheim",
      "Niflheim",
      "Múspellheim",
      "Helheim",
    ],
    sources: [POETIC_EDDA],
    qualificationRule:
      "Les variantes orthographiques françaises ou vieux-norroises des neuf mondes sont acceptées.",
  }),
  q({
    id: "hard-neuf-valkyries-grimnismal",
    subthemeId: "mythology-legends:norse-mythology",
    difficultyLevel: 3,
    shortTitle: "Valkyries du Grímnismál",
    questionText:
      "Quelles sont les neuf premières Valkyries nommées dans les strophes 36 et 37 du Grímnismál ?",
    answers: [
      "Hrist",
      "Mist",
      "Skeggjöld",
      "Skögul",
      "Hildr",
      "Þrúðr",
      "Hlökk",
      "Herfjötur",
      "Göll",
    ],
    sources: [POETIC_EDDA],
    qualificationRule: "Les translittérations usuelles des neuf noms vieux-norrois sont acceptées.",
  }),
  q({
    id: "hard-neuf-rois-hell",
    subthemeId: "mythology-legends:world-legends",
    difficultyLevel: 3,
    shortTitle: "Neuf Preux",
    questionText:
      "Quels sont les neuf héros composant les Neuf Preux de la tradition médiévale européenne ?",
    answers: [
      "Hector",
      "Alexandre le Grand",
      "Jules César",
      "Josué",
      "David",
      "Judas Maccabée",
      "Arthur",
      "Charlemagne",
      "Godefroy de Bouillon",
    ],
    sources: [BRITANNICA],
  }),
  q({
    id: "hard-neuf-filles-aegir-ran",
    subthemeId: "mythology-legends:norse-mythology",
    difficultyLevel: 3,
    shortTitle: "Filles d’Ægir et Rán",
    questionText:
      "Quels sont les noms des neuf filles d’Ægir et Rán, personnifications des vagues ?",
    answers: [
      "Himinglæva",
      "Dúfa",
      "Blóðughadda",
      "Hefring",
      "Uðr",
      "Hrönn",
      "Bylgja",
      "Dröfn",
      "Kólga",
    ],
    sources: [POETIC_EDDA],
    qualificationRule: "Les translittérations usuelles des noms vieux-norrois sont acceptées.",
  }),
];
