const src=(id,title,publisher,url)=>({id,title,publisher,url,isPrimarySource:true});
const KEW=src("kew-plants","Plants of the World Online","Royal Botanic Gardens, Kew","https://powo.science.kew.org/");
const NOAA=src("noaa-ocean-service","Ocean facts","National Oceanic and Atmospheric Administration","https://oceanservice.noaa.gov/facts/");
const WMO=src("wmo-cloud-atlas","International Cloud Atlas","World Meteorological Organization","https://cloudatlas.wmo.int/en/home.html");
const USGS=src("usgs-geology","Geology and natural hazards","United States Geological Survey","https://www.usgs.gov/programs/natural-hazards");
const WWF=src("wwf-biomes","Biomes and ecoregions","World Wildlife Fund","https://www.worldwildlife.org/biomes");
const UNESCO=src("unesco-world-heritage-natural","Natural World Heritage","UNESCO World Heritage Centre","https://whc.unesco.org/en/natural-world-heritage/");
const q=([id,sub,d,title,text,answers,source=USGS,rule])=>({id,themeId:"nature",subthemeId:`nature:${sub}`,difficultyLevel:d,shortTitle:title,questionText:text,answers,sources:[source],qualificationRule:rule??"Les neuf réponses appartiennent précisément à la classification ou à la période indiquée.",explanation:"Ensemble stable vérifié dans la référence scientifique ou institutionnelle citée."});
export const questions=[
q(["easy-parties-fleur","plants",1,"Anatomie d’une fleur","Quelles sont neuf parties courantes d’une plante à fleurs ?",["Racine","Tige","Feuille","Sépale","Pétale","Étamine","Anthère","Pistil","Ovaire"],KEW]),
q(["easy-arbres-feuillus-europe","plants",1,"Arbres européens","Quels sont neuf arbres feuillus communs en Europe ?",["Chêne pédonculé","Hêtre commun","Érable sycomore","Bouleau verruqueux","Frêne élevé","Orme champêtre","Tilleul à petites feuilles","Châtaignier","Peuplier noir"],KEW]),
q(["easy-mers-mediterranee","oceans",1,"Mers de Méditerranée","Quelles sont neuf mers ou grands bassins nommés de l’ensemble méditerranéen ?",["Mer d’Alboran","Mer des Baléares","Mer Ligure","Mer Tyrrhénienne","Mer Adriatique","Mer Ionienne","Mer Égée","Mer de Crète","Mer de Libye"],NOAA]),
q(["easy-types-precipitations","climate",1,"Précipitations","Quels sont neuf types de précipitations ou dépôts atmosphériques couramment nommés ?",["Pluie","Bruine","Neige","Grêle","Grésil","Pluie verglaçante","Neige roulée","Rosée","Givre"],WMO]),
q(["easy-echelle-mohs-1-9","geology",1,"Échelle de Mohs","Quels sont les neuf premiers minéraux de référence de l’échelle de Mohs, du talc au corindon ?",["Talc","Gypse","Calcite","Fluorite","Apatite","Orthose","Quartz","Topaze","Corindon"],USGS]),
q(["easy-biomes-terrestres","ecosystems",1,"Grands biomes","Quels sont neuf grands biomes terrestres couramment distingués ?",["Toundra","Taïga","Forêt tempérée","Forêt tropicale humide","Savane","Prairie tempérée","Désert","Maquis méditerranéen","Mangrove"],WWF]),
q(["medium-genres-nuages-sans-cirrus","climate",2,"Genres de nuages","Quels sont neuf des dix genres de nuages de l’Atlas international, en excluant le cirrus ?",["Cirrocumulus","Cirrostratus","Altocumulus","Altostratus","Nimbostratus","Stratocumulus","Stratus","Cumulus","Cumulonimbus"],WMO]),
q(["medium-fosses-oceaniques","oceans",2,"Fosses océaniques","Quelles sont neuf grandes fosses océaniques nommées ?",["Fosse des Mariannes","Fosse des Tonga","Fosse des Kermadec","Fosse des Philippines","Fosse du Japon","Fosse des Kouriles","Fosse de Porto Rico","Fosse du Pérou-Chili","Fosse de Java"],NOAA]),
q(["medium-plaques-tectoniques","geology",2,"Plaques tectoniques","Quelles sont neuf grandes plaques tectoniques généralement reconnues ?",["Plaque africaine","Plaque antarctique","Plaque australienne","Plaque eurasienne","Plaque nord-américaine","Plaque sud-américaine","Plaque pacifique","Plaque de Nazca","Plaque indienne"],USGS]),
q(["medium-coniferes-europe","plants",2,"Conifères européens","Quels sont neuf conifères indigènes ou largement naturels d’Europe ?",["Pin sylvestre","Pin maritime","Pin d’Alep","Sapin blanc","Épicéa commun","Mélèze d’Europe","If commun","Genévrier commun","Pin cembro"],KEW]),
q(["medium-ecosystemes-cotiers","ecosystems",2,"Écosystèmes côtiers","Quels sont neuf grands types d’écosystèmes côtiers ou marins peu profonds ?",["Mangrove","Marais salé","Herbier marin","Récif corallien","Forêt de kelp","Estran rocheux","Vasière","Estuaire","Lagune côtière"],NOAA]),
q(["medium-volcans-ceinture-feu","natural-phenomena",2,"Ceinture de feu","Quels sont neuf volcans actifs ou historiquement actifs de la ceinture de feu du Pacifique ?",["Mont Saint Helens","Mont Rainier","Popocatépetl","Fuego","Cotopaxi","Villarrica","Mont Fuji","Pinatubo","Krakatoa"],USGS]),
q(["hard-ordres-plantes-fleurs","plants",3,"Ordres botaniques","Quels sont neuf grands ordres de plantes à fleurs reconnus par la classification APG ?",["Rosales","Fabales","Fagales","Poales","Asterales","Lamiales","Brassicales","Malpighiales","Sapindales"],KEW]),
q(["hard-courants-oceaniques","oceans",3,"Courants océaniques","Quels sont neuf grands courants de surface nommés de l’Atlantique Nord et de ses marges ?",["Gulf Stream","Courant nord-atlantique","Courant des Canaries","Courant nord-équatorial","Courant des Antilles","Courant du Labrador","Courant du Groenland oriental","Courant de Norvège","Courant des Açores"],NOAA]),
q(["hard-echelle-beaufort-4-12","climate",3,"Échelle de Beaufort","Quels sont les neuf termes français de l’échelle de Beaufort des forces 4 à 12 ?",["Jolie brise","Bonne brise","Vent frais","Grand frais","Coup de vent","Fort coup de vent","Tempête","Violente tempête","Ouragan"],WMO]),
q(["hard-types-roches-metamorphiques","geology",3,"Roches métamorphiques","Quelles sont neuf roches métamorphiques couramment reconnues ?",["Ardoise","Phyllade","Schiste","Gneiss","Marbre","Quartzite","Amphibolite","Éclogite","Migmatite"],USGS]),
q(["hard-sites-naturels-france-portugal-unesco","ecosystems",3,"Nature à l’UNESCO","Quels sont neuf biens naturels ou mixtes de l’UNESCO sous juridiction française ou portugaise ?",["Golfe de Porto","Lagons de Nouvelle-Calédonie","Pitons cirques et remparts de La Réunion","Terres et mers australes françaises","Chaîne des Puys - faille de Limagne","Mont Perdu","Forêts primaires de hêtres des Carpates et d’autres régions d’Europe","Volcans et forêts de la montagne Pelée et des pitons du nord de la Martinique","Forêt laurifère de Madère"],UNESCO])
];
