const source = (id, title, url) => ({
  id,
  title,
  publisher: "Wikipédia",
  url,
  isPrimarySource: false,
});

const q = (spec) => ({
  qualificationRule:
    spec.qualificationRule ??
    "Le jeu retient neuf réponses connues et valides parmi les exemples possibles de cette catégorie.",
  explanation:
    spec.explanation ??
    "Ces neuf réponses forment une sélection jouable, reconnaissable et non exhaustive.",
  ...spec,
});

const tvCharacters = source(
  "playable-tv-characters",
  "Listes de personnages de séries télévisées",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Personnage_de_s%C3%A9rie_t%C3%A9l%C3%A9vis%C3%A9e",
);
const tvSeries = source(
  "playable-tv-series",
  "Listes de séries télévisées",
  "https://fr.wikipedia.org/wiki/Liste_de_s%C3%A9ries_t%C3%A9l%C3%A9vis%C3%A9es",
);
const animation = source(
  "playable-animation",
  "Animation et personnages animés",
  "https://fr.wikipedia.org/wiki/Animation_(audiovisuel)",
);
const celebrities = source(
  "playable-celebrities",
  "Personnalités du cinéma, de la mode et des médias",
  "https://fr.wikipedia.org/wiki/C%C3%A9l%C3%A9brit%C3%A9",
);
const cinema = source(
  "playable-cinema",
  "Listes de films",
  "https://fr.wikipedia.org/wiki/Liste_de_films",
);
const internet = source(
  "playable-internet-culture",
  "Culture Internet",
  "https://fr.wikipedia.org/wiki/Culture_Internet",
);
const science = source(
  "playable-science",
  "Portail des sciences",
  "https://fr.wikipedia.org/wiki/Portail:Sciences",
);
const sport = source(
  "playable-sport",
  "Liste de sports",
  "https://fr.wikipedia.org/wiki/Liste_de_sports",
);
const technology = source(
  "playable-technology",
  "Portail des technologies",
  "https://fr.wikipedia.org/wiki/Portail:Technologies",
);
const comics = source(
  "playable-comics",
  "Bandes dessinées et mangas",
  "https://fr.wikipedia.org/wiki/Bande_dessin%C3%A9e",
);
const music = source(
  "playable-music",
  "Portail de la musique",
  "https://fr.wikipedia.org/wiki/Portail:Musique",
);
const literature = source(
  "playable-literature",
  "Portail de la littérature",
  "https://fr.wikipedia.org/wiki/Portail:Litt%C3%A9rature",
);
const mythology = source(
  "playable-mythology",
  "Mythologies du monde",
  "https://fr.wikipedia.org/wiki/Mythologie",
);
const history = source(
  "playable-history",
  "Portail de l’histoire",
  "https://fr.wikipedia.org/wiki/Portail:Histoire",
);
const france = source(
  "playable-france",
  "Histoire et culture de la France",
  "https://fr.wikipedia.org/wiki/France",
);
const popCulture = source(
  "playable-pop-culture",
  "Culture populaire",
  "https://fr.wikipedia.org/wiki/Culture_populaire",
);
const videoGames = source(
  "playable-video-games",
  "Portail du jeu vidéo",
  "https://fr.wikipedia.org/wiki/Portail:Jeu_vid%C3%A9o",
);
const geography = source(
  "playable-geography",
  "Portail de la géographie",
  "https://fr.wikipedia.org/wiki/Portail:G%C3%A9ographie",
);
const football = source(
  "playable-football",
  "Portail du football",
  "https://fr.wikipedia.org/wiki/Portail:Football",
);
const nature = source(
  "playable-nature",
  "Portail de la nature",
  "https://fr.wikipedia.org/wiki/Portail:Biologie",
);

export const obsoleteQuestionIds = [
  "easy-arcane-saison-1",
  "easy-friends-neuf-premiers",
  "easy-http-200-a-208",
  "easy-http-400-a-408",
  "easy-last-of-us-saison-1",
  "easy-mandalorian-neuf-premiers",
  "easy-neuf-bluetooth-jusqua-42",
  "easy-neuf-methodes-http",
  "easy-neuf-premieres-ubuntu",
  "easy-neuf-premiers-ios",
  "easy-neuf-schemas-uri",
  "easy-squid-game-saison-1",
  "easy-stranger-things-saison-2",
  "easy-wandavision-neuf-episodes",
  "hard-angouleme-fauve-2015-2023",
  "hard-annecy-cristal-2014-2022",
  "hard-ballon-or-1961-1969",
  "hard-cannes-acteur-2011-2019",
  "hard-cannes-palme-realisateurs-2011-2019",
  "hard-elements-100-108",
  "hard-elements-37-45",
  "hard-elements-55-63",
  "hard-elements-73-81",
  "hard-elements-91-99",
  "hard-fleischer-superman-neuf-premiers",
  "hard-http-500-a-508",
  "hard-lions-or-2015-2023",
  "hard-mad-men-neuf-premiers",
  "hard-neuf-entetes-usenet-rfc850",
  "hard-neuf-laureats-nobel-paix-2000-2008",
  "hard-neuf-macos-classiques",
  "hard-neuf-schemas-uri-a",
  "hard-neuf-sites-arpanet",
  "hard-neuf-types-media-iana",
  "hard-neuf-usb-jusqua-32",
  "hard-nobel-litterature-2015-2023",
  "hard-oscar-court-animation-neuf-premiers",
  "hard-ours-or-2015-2023",
  "hard-palmes-or-2014-2023",
  "hard-signaux-posix-1-a-9",
  "hard-silly-symphonies-neuf-premieres",
  "hard-six-feet-under-neuf-premiers",
  "hard-sopranos-neuf-premiers",
  "hard-succession-neuf-premiers",
  "hard-tex-avery-mgm-neuf-premiers",
  "hard-the-wire-neuf-premiers",
  "hard-time-person-2014-2022",
  "hard-twin-peaks-neuf-premiers",
  "hard-venise-acteur-2015-2023",
  "hard-venise-actrice-2015-2023",
  "medium-arbitres-finales-rugby-1987-2019",
  "medium-black-mirror-neuf-premiers",
  "medium-crown-neuf-premiers",
  "medium-doctor-who-neuf-docteurs",
  "medium-elements-10-18",
  "medium-elements-un-neuf",
  "medium-futurama-neuf-premiers",
  "medium-goncourt-2015-2023",
  "medium-grammy-album-2015-2023",
  "medium-http-300-a-308",
  "medium-hugo-roman-2015-2023",
  "medium-mvp-finales-nba-2015-2023",
  "medium-neuf-blocs-ipv4-speciaux",
  "medium-neuf-java-jusqua-8",
  "medium-neuf-premieres-debian",
  "medium-neuf-premiers-asteroides-numerotes",
  "medium-neuf-python-3-0-a-3-8",
  "medium-neuf-quotients-nist",
  "medium-neuf-tld-sponsorises",
  "medium-neuf-types-dns",
  "medium-neuf-ubuntu-lts",
  "medium-neuf-wifi-lettres",
  "medium-peaky-blinders-neuf-premiers",
  "medium-rick-morty-neuf-premiers",
  "medium-sherlock-neuf-episodes",
  "medium-south-park-neuf-premiers",
  "medium-spongebob-neuf-premiers",
  "medium-ted-lasso-neuf-premiers",
  "medium-vainqueurs-tour-2012-2020",
  "medium-vainqueurs-wimbledon-2003-2011",
  "medium-x-files-neuf-premiers",
  "easy-bowie-neuf-premiers",
  "easy-metallica-neuf-premiers",
  "easy-champions-f1-2015-2023",
  "easy-champions-rugby-1987-2019",
  "easy-equipes-nba-titres-2015-2024",
  "easy-premiers-ballon-or-differents",
  "easy-stades-finales-mondial-1990-2022",
  "easy-neuf-premiers-presidents-republique",
  "easy-neuf-rois-anglais-1066",
  "easy-saga-skywalker",
  "hard-buteurs-france-euro-1984",
  "hard-capitaines-champions-rugby",
  "hard-neuf-elements-html-a",
  "hard-neuf-mega-man-x",
  "hard-blueberry-neuf-premiers",
  "hard-corto-neuf-premiers",
  "hard-spirou-franquin-neuf-premiers",
  "hard-thorgal-neuf-premiers",
  "hard-valerian-neuf-premiers",
  "hard-bjork-neuf-internationaux",
  "hard-joni-mitchell-neuf-premiers",
  "hard-kraftwerk-neuf-premiers",
  "hard-nick-cave-neuf-premiers",
  "hard-pj-harvey-neuf-premiers",
  "hard-symphonies-beethoven",
  "hard-booker-neuf-premiers-romans",
  "hard-modiano-neuf-premiers",
  "hard-nobel-neuf-premiers-laureats",
  "hard-pulitzer-roman-neuf-premiers",
  "hard-woolf-neuf-romans",
  "hard-neuf-filles-aegir-ran",
  "hard-neuf-rois-hell",
  "hard-neuf-valkyries-grimnismal",
  "hard-neuf-empereurs-byzantins-macedoniens",
  "hard-neuf-etats-confederes-initiaux",
  "hard-neuf-membres-expedition-lewis-clark",
  "hard-neuf-rois-assyriens",
  "hard-neuf-constitutions-1791-1848",
  "hard-neuf-departements-revolutionnaires-belgique",
  "hard-neuf-presidents-assemblee-constituante-1789",
  "hard-kurosawa-neuf-premiers",
  "hard-scorsese-neuf-premiers-fictions",
  "hard-american-girl-neuf-historiques",
  "hard-big-finish-neuf-premiers-doctor-who",
  "hard-dnd-neuf-premiers-univers",
  "hard-lego-ideas-neuf-premiers",
  "hard-magic-neuf-premieres-extensions",
  "hard-pokemon-tcg-neuf-premieres-extensions",
  "hard-neuf-premiers-atelier",
  "hard-neuf-premiers-castlevania",
  "hard-neuf-premiers-fire-emblem",
  "hard-ys-1-a-9",
  "hard-comtes-ulster",
  "hard-neuf-iles-tuvalu",
  "hard-provinces-canada-avant-1949",
  "hard-provinces-iles-salomon",
  "hard-provinces-sri-lanka",
  "hard-regions-angleterre",
  "hard-marques-annees-fondation",
  "hard-normes-formats-papier",
  "hard-finales-c1-neuf-villes",
  "hard-neuf-stades-france-mondial-1938",
  "hard-ordres-plantes-fleurs",
  "hard-sites-naturels-france-portugal-unesco",
  "hard-neuf-sites-unesco-numero-ordre",
  "easy-oscar-acteur-2015-2023",
  "easy-oscar-actrice-2004-2012",
  "easy-emma-watson-neuf-premiers",
  "easy-daniel-radcliffe-neuf-films",
  "easy-tom-cruise-neuf-premiers",
  "easy-will-smith-neuf-premiers",
  "easy-jennifer-lawrence-neuf-premiers",
  "medium-tom-hanks-neuf-premiers",
  "medium-dicaprio-neuf-premiers",
  "medium-denzel-neuf-premiers",
  "medium-natalie-portman-neuf-premiers",
  "medium-meryl-streep-neuf-premiers",
  "medium-scarlett-neuf-premiers",
  "medium-jean-dujardin-neuf-premiers",
  "easy-neuf-croisades-numerotees",
  "easy-neuf-sonic-classiques",
  "easy-power-rangers-neuf-premieres-series",
  "easy-rougon-macquart-neuf-premiers",
  "hard-neuf-premiers-vainqueurs-tour",
  "hard-premieres-championnes-wimbledon",
  "hard-premiers-mvp-nba",
];

export const difficultyOverrides = {
  "easy-mcu-neuf-premiers": 2,
  "medium-miyazaki-neuf-premiers": 3,
  "easy-princesses-neuf-films": 2,
  "medium-naruto-neuf-jinchuriki": 3,
  "medium-doctor-who-neuf-incarnations": 3,
  "easy-races-chats": 2,
  "medium-amphibiens-europe": 3,
  "easy-departements-10-18": 2,
};

export const questions = [
  q({
    id: "play-tv-friends",
    themeId: "television-series",
    subthemeId: "television-series:comedy-series",
    difficultyLevel: 1,
    shortTitle: "La bande de Friends",
    questionText: "Cite 9 personnages de Friends.",
    answers: [
      "Rachel Green",
      "Ross Geller",
      "Monica Geller",
      "Chandler Bing",
      "Joey Tribbiani",
      "Phoebe Buffay",
      "Gunther",
      "Janice",
      "Mike Hannigan",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-stranger-things",
    themeId: "television-series",
    subthemeId: "television-series:characters",
    difficultyLevel: 1,
    shortTitle: "Stranger Things",
    questionText: "Cite 9 personnages de Stranger Things.",
    answers: [
      "Eleven",
      "Mike Wheeler",
      "Dustin Henderson",
      "Lucas Sinclair",
      "Will Byers",
      "Max Mayfield",
      "Jim Hopper",
      "Joyce Byers",
      "Steve Harrington",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-office",
    themeId: "television-series",
    subthemeId: "television-series:comedy-series",
    difficultyLevel: 1,
    shortTitle: "The Office US",
    questionText: "Cite 9 personnages de The Office US.",
    answers: [
      "Michael Scott",
      "Dwight Schrute",
      "Jim Halpert",
      "Pam Beesly",
      "Ryan Howard",
      "Kelly Kapoor",
      "Angela Martin",
      "Kevin Malone",
      "Andy Bernard",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-simpsons",
    themeId: "television-series",
    subthemeId: "television-series:characters",
    difficultyLevel: 1,
    shortTitle: "Les Simpson",
    questionText: "Cite 9 personnages des Simpson.",
    answers: [
      "Homer",
      "Marge",
      "Bart",
      "Lisa",
      "Maggie",
      "Moe",
      "Ned Flanders",
      "Monsieur Burns",
      "Krusty",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-casa-papel",
    themeId: "television-series",
    subthemeId: "television-series:drama-series",
    difficultyLevel: 1,
    shortTitle: "La Casa de Papel",
    questionText: "Cite 9 braqueurs de La Casa de Papel.",
    answers: [
      "Tokyo",
      "Berlin",
      "Nairobi",
      "Rio",
      "Denver",
      "Moscou",
      "Helsinki",
      "Oslo",
      "Lisbonne",
    ],
    sources: [tvCharacters],
  }),

  q({
    id: "play-tv-game-thrones",
    themeId: "television-series",
    subthemeId: "television-series:characters",
    difficultyLevel: 2,
    shortTitle: "Game of Thrones",
    questionText: "Cite 9 personnages de Game of Thrones.",
    answers: [
      "Jon Snow",
      "Daenerys Targaryen",
      "Tyrion Lannister",
      "Arya Stark",
      "Sansa Stark",
      "Cersei Lannister",
      "Jaime Lannister",
      "Bran Stark",
      "Theon Greyjoy",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-kaamelott",
    themeId: "television-series",
    subthemeId: "television-series:french-television",
    difficultyLevel: 2,
    shortTitle: "Kaamelott",
    questionText: "Cite 9 personnages de Kaamelott.",
    answers: [
      "Arthur",
      "Perceval",
      "Karadoc",
      "Léodagan",
      "Guenièvre",
      "Lancelot",
      "Bohort",
      "Merlin",
      "Dame Séli",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-brooklyn-99",
    themeId: "television-series",
    subthemeId: "television-series:comedy-series",
    difficultyLevel: 2,
    shortTitle: "Brooklyn Nine-Nine",
    questionText: "Cite 9 personnages de Brooklyn Nine-Nine.",
    answers: [
      "Jake Peralta",
      "Amy Santiago",
      "Raymond Holt",
      "Rosa Diaz",
      "Terry Jeffords",
      "Charles Boyle",
      "Gina Linetti",
      "Hitchcock",
      "Scully",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-the-boys",
    themeId: "television-series",
    subthemeId: "television-series:characters",
    difficultyLevel: 2,
    shortTitle: "The Boys",
    questionText: "Cite 9 personnages de The Boys.",
    answers: [
      "Homelander",
      "Billy Butcher",
      "Hughie Campbell",
      "Starlight",
      "Mother's Milk",
      "Frenchie",
      "Kimiko",
      "A-Train",
      "The Deep",
    ],
    sources: [tvCharacters],
  }),
  q({
    id: "play-tv-sex-education",
    themeId: "television-series",
    subthemeId: "television-series:comedy-series",
    difficultyLevel: 2,
    shortTitle: "Sex Education",
    questionText: "Cite 9 personnages de Sex Education.",
    answers: [
      "Otis Milburn",
      "Maeve Wiley",
      "Eric Effiong",
      "Jean Milburn",
      "Adam Groff",
      "Aimee Gibbs",
      "Jackson Marchetti",
      "Ruby Matthews",
      "Isaac Goodwin",
    ],
    sources: [tvCharacters],
  }),

  q({
    id: "play-tv-detectives",
    themeId: "television-series",
    subthemeId: "television-series:characters",
    difficultyLevel: 3,
    shortTitle: "Détectives de séries",
    questionText: "Cite 9 enquêteurs cultes de séries télé.",
    answers: [
      "Columbo",
      "Jessica Fletcher",
      "Hercule Poirot",
      "Sherlock Holmes",
      "Veronica Mars",
      "Dale Cooper",
      "Rust Cohle",
      "Sarah Lund",
      "Saga Norén",
    ],
    sources: [tvSeries],
  }),
  q({
    id: "play-tv-companies",
    themeId: "television-series",
    subthemeId: "television-series:shows",
    difficultyLevel: 3,
    shortTitle: "Entreprises fictives",
    questionText: "Cite 9 entreprises fictives vues dans des séries.",
    answers: [
      "Dunder Mifflin",
      "Waystar Royco",
      "Los Pollos Hermanos",
      "Sterling Cooper",
      "Pied Piper",
      "E Corp",
      "Lumon Industries",
      "Hooli",
      "Vought International",
    ],
    sources: [tvSeries],
  }),
  q({
    id: "play-tv-video-games",
    themeId: "television-series",
    subthemeId: "television-series:drama-series",
    difficultyLevel: 3,
    shortTitle: "Du jeu à la série",
    questionText: "Cite 9 séries issues d’un univers de jeu vidéo.",
    answers: [
      "The Last of Us",
      "Fallout",
      "Arcane",
      "Castlevania",
      "Cyberpunk: Edgerunners",
      "Halo",
      "Pokémon",
      "Twisted Metal",
      "Tomb Raider : La Légende de Lara Croft",
    ],
    sources: [tvSeries],
  }),
  q({
    id: "play-tv-scifi",
    themeId: "television-series",
    subthemeId: "television-series:drama-series",
    difficultyLevel: 3,
    shortTitle: "Science-fiction télé",
    questionText: "Cite 9 séries de science-fiction modernes.",
    answers: [
      "Black Mirror",
      "Dark",
      "Westworld",
      "The Expanse",
      "Severance",
      "Stranger Things",
      "The Handmaid's Tale",
      "Altered Carbon",
      "Foundation",
    ],
    sources: [tvSeries],
  }),
  q({
    id: "play-tv-france",
    themeId: "television-series",
    subthemeId: "television-series:french-television",
    difficultyLevel: 3,
    shortTitle: "Séries françaises",
    questionText: "Cite 9 séries françaises saluées par la critique.",
    answers: [
      "Le Bureau des légendes",
      "Engrenages",
      "Dix pour cent",
      "Baron noir",
      "Les Revenants",
      "OVNI(s)",
      "Hippocrate",
      "Cœurs noirs",
      "Drôle",
    ],
    sources: [tvSeries],
  }),

  q({
    id: "play-animation-vilains-disney",
    themeId: "animation",
    subthemeId: "animation:characters",
    difficultyLevel: 2,
    shortTitle: "Méchants Disney",
    questionText: "Cite 9 méchants des classiques Disney.",
    answers: [
      "Maléfique",
      "Cruella",
      "Ursula",
      "Jafar",
      "Scar",
      "Hadès",
      "Gaston",
      "Capitaine Crochet",
      "La Reine-sorcière",
    ],
    sources: [animation],
  }),
  q({
    id: "play-animation-pixar",
    themeId: "animation",
    subthemeId: "animation:characters",
    difficultyLevel: 2,
    shortTitle: "Personnages Pixar",
    questionText: "Cite 9 personnages de films Pixar.",
    answers: [
      "Woody",
      "Buzz l'Éclair",
      "Nemo",
      "Dory",
      "Sully",
      "Bob Parr",
      "Wall-E",
      "Rémy",
      "Joie",
    ],
    sources: [animation],
  }),
  q({
    id: "play-animation-ghibli-heroines",
    themeId: "animation",
    subthemeId: "animation:anime",
    difficultyLevel: 3,
    shortTitle: "Héroïnes Ghibli",
    questionText: "Cite 9 héroïnes de films du Studio Ghibli.",
    answers: ["Nausicaä", "Sheeta", "Satsuki", "Kiki", "Gina", "San", "Chihiro", "Sophie", "Ponyo"],
    sources: [animation],
  }),
  q({
    id: "play-animation-anime-mentors",
    themeId: "animation",
    subthemeId: "animation:anime",
    difficultyLevel: 3,
    shortTitle: "Mentors d'anime",
    questionText: "Cite 9 mentors célèbres d’anime ou de manga.",
    answers: [
      "Maître Roshi",
      "Kakashi Hatake",
      "Jiraya",
      "All Might",
      "Satoru Gojo",
      "Silvers Rayleigh",
      "Genkai",
      "Koro-sensei",
      "Urokodaki",
    ],
    sources: [animation],
  }),
  q({
    id: "play-animation-worlds",
    themeId: "animation",
    subthemeId: "animation:animated-films",
    difficultyLevel: 3,
    shortTitle: "Mondes animés",
    questionText: "Cite 9 lieux fictifs célèbres de films d’animation.",
    answers: [
      "Arendelle",
      "Agrabah",
      "Zootopie",
      "Monstropolis",
      "Radiator Springs",
      "Kumandra",
      "Motunui",
      "Atlantide",
      "Halloween Town",
    ],
    sources: [animation],
  }),
  q({
    id: "play-animation-studios",
    themeId: "animation",
    subthemeId: "animation:studios",
    difficultyLevel: 3,
    shortTitle: "Studios d’animation",
    questionText: "Cite 9 studios d’animation connus dans le monde.",
    answers: [
      "Pixar",
      "DreamWorks Animation",
      "Studio Ghibli",
      "Illumination",
      "Aardman",
      "Laika",
      "Cartoon Saloon",
      "Madhouse",
      "Toei Animation",
    ],
    sources: [animation],
  }),

  q({
    id: "play-celebrities-mononyms",
    themeId: "celebrities",
    subthemeId: "celebrities:singers",
    difficultyLevel: 3,
    shortTitle: "Un seul nom",
    questionText: "Cite 9 chanteuses connues sous un seul nom.",
    answers: [
      "Beyoncé",
      "Rihanna",
      "Adele",
      "Madonna",
      "Cher",
      "Shakira",
      "Björk",
      "Lorde",
      "Pink",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-batman",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 3,
    shortTitle: "Les visages de Batman",
    questionText: "Cite 9 acteurs ayant incarné Batman à l’écran ou en voix.",
    answers: [
      "Adam West",
      "Michael Keaton",
      "Val Kilmer",
      "George Clooney",
      "Christian Bale",
      "Ben Affleck",
      "Robert Pattinson",
      "Kevin Conroy",
      "Will Arnett",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-chefs",
    themeId: "celebrities",
    subthemeId: "celebrities:media-figures",
    difficultyLevel: 3,
    shortTitle: "Chefs médiatiques",
    questionText: "Cite 9 chefs devenus célèbres à la télévision.",
    answers: [
      "Philippe Etchebest",
      "Cyril Lignac",
      "Hélène Darroze",
      "Gordon Ramsay",
      "Jamie Oliver",
      "Anne-Sophie Pic",
      "Thierry Marx",
      "Norbert Tarayre",
      "Pierre Gagnaire",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-models",
    themeId: "celebrities",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 3,
    shortTitle: "Mannequins iconiques",
    questionText: "Cite 9 mannequins devenus des icônes internationales.",
    answers: [
      "Naomi Campbell",
      "Cindy Crawford",
      "Claudia Schiffer",
      "Kate Moss",
      "Gisele Bündchen",
      "Tyra Banks",
      "Heidi Klum",
      "Cara Delevingne",
      "Iman",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-comedians",
    themeId: "celebrities",
    subthemeId: "celebrities:international-icons",
    difficultyLevel: 3,
    shortTitle: "Stand-up international",
    questionText: "Cite 9 humoristes de stand-up connus à l’international.",
    answers: [
      "Dave Chappelle",
      "Chris Rock",
      "Eddie Murphy",
      "Ali Wong",
      "Ricky Gervais",
      "Kevin Hart",
      "Hannah Gadsby",
      "Trevor Noah",
      "Jerry Seinfeld",
    ],
    sources: [celebrities],
  }),

  q({
    id: "play-cinema-realisatrices",
    themeId: "cinema",
    subthemeId: "cinema:directors",
    difficultyLevel: 3,
    shortTitle: "Films de réalisatrices",
    questionText: "Cite 9 films marquants réalisés par des femmes.",
    answers: [
      "Barbie",
      "Lady Bird",
      "Nomadland",
      "Lost in Translation",
      "Démineurs",
      "Wonder Woman",
      "Titane",
      "Anatomie d'une chute",
      "Portrait de la jeune fille en feu",
    ],
    sources: [cinema],
  }),
  q({
    id: "play-cinema-international",
    themeId: "cinema",
    subthemeId: "cinema:world-cinema",
    difficultyLevel: 3,
    shortTitle: "Cinéma mondial",
    questionText: "Cite 9 films non anglophones devenus cultes.",
    answers: [
      "Parasite",
      "Old Boy",
      "Le Fabuleux Destin d'Amélie Poulain",
      "La Vie des autres",
      "Le Voyage de Chihiro",
      "Intouchables",
      "Roma",
      "Une séparation",
      "Le Labyrinthe de Pan",
    ],
    sources: [cinema],
  }),

  q({
    id: "play-internet-video-platforms",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:platforms",
    difficultyLevel: 1,
    shortTitle: "Plateformes vidéo",
    questionText: "Cite 9 plateformes où l’on regarde ou publie des vidéos.",
    answers: [
      "YouTube",
      "TikTok",
      "Twitch",
      "Instagram",
      "Dailymotion",
      "Vimeo",
      "Snapchat",
      "Facebook",
      "Kick",
    ],
    sources: [internet],
  }),
  q({
    id: "play-internet-memes",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:memes",
    difficultyLevel: 2,
    shortTitle: "Mèmes cultes",
    questionText: "Cite 9 mèmes Internet devenus cultes.",
    answers: [
      "Doge",
      "Distracted Boyfriend",
      "Success Kid",
      "Drake Hotline Bling",
      "This Is Fine",
      "Woman Yelling at a Cat",
      "Hide the Pain Harold",
      "Disaster Girl",
      "Rickroll",
    ],
    sources: [internet],
  }),
  q({
    id: "play-internet-slang",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:online-communities",
    difficultyLevel: 2,
    shortTitle: "Argot du web",
    questionText: "Cite 9 sigles ou expressions courantes du web.",
    answers: ["LOL", "MDR", "IRL", "DM", "POV", "AMA", "TL;DR", "NSFW", "GG"],
    sources: [internet],
  }),
  q({
    id: "play-internet-browsers",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:web-history",
    difficultyLevel: 3,
    shortTitle: "Navigateurs web",
    questionText: "Cite 9 navigateurs web actuels ou historiques.",
    answers: [
      "Chrome",
      "Firefox",
      "Safari",
      "Edge",
      "Opera",
      "Internet Explorer",
      "Netscape Navigator",
      "Brave",
      "Vivaldi",
    ],
    sources: [internet],
  }),
  q({
    id: "play-internet-pioneers",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:web-history",
    difficultyLevel: 3,
    shortTitle: "Pionniers du web",
    questionText: "Cite 9 personnalités qui ont marqué l’histoire du web.",
    answers: [
      "Tim Berners-Lee",
      "Vint Cerf",
      "Bob Kahn",
      "Marc Andreessen",
      "Jimmy Wales",
      "Larry Page",
      "Sergey Brin",
      "Mark Zuckerberg",
      "Jack Dorsey",
    ],
    sources: [internet],
  }),
  q({
    id: "play-internet-communities",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:online-communities",
    difficultyLevel: 3,
    shortTitle: "Communautés en ligne",
    questionText: "Cite 9 grandes communautés ou plateformes de discussion en ligne.",
    answers: [
      "Reddit",
      "Discord",
      "Stack Overflow",
      "Quora",
      "4chan",
      "Twitch",
      "Tumblr",
      "Mastodon",
      "Bluesky",
    ],
    sources: [internet],
  }),
  q({
    id: "play-internet-formats",
    themeId: "internet-social-media",
    subthemeId: "internet-social-media:platforms",
    difficultyLevel: 3,
    shortTitle: "Formats du web",
    questionText: "Cite 9 formats de fichiers très utilisés sur Internet.",
    answers: ["JPEG", "PNG", "GIF", "SVG", "MP3", "MP4", "PDF", "ZIP", "WebP"],
    sources: [internet],
  }),

  q({
    id: "play-science-organs",
    themeId: "science",
    subthemeId: "science:biology",
    difficultyLevel: 2,
    shortTitle: "Corps humain",
    questionText: "Cite 9 organes importants du corps humain.",
    answers: [
      "Cerveau",
      "Cœur",
      "Poumons",
      "Foie",
      "Estomac",
      "Reins",
      "Pancréas",
      "Rate",
      "Intestin grêle",
    ],
    sources: [science],
  }),
  q({
    id: "play-science-moons",
    themeId: "science",
    subthemeId: "science:astronomy",
    difficultyLevel: 2,
    shortTitle: "Lunes célèbres",
    questionText: "Cite 9 lunes connues du Système solaire.",
    answers: [
      "Lune",
      "Europe",
      "Io",
      "Ganymède",
      "Callisto",
      "Titan",
      "Encelade",
      "Triton",
      "Phobos",
    ],
    sources: [science],
  }),
  q({
    id: "play-science-particles",
    themeId: "science",
    subthemeId: "science:physics",
    difficultyLevel: 3,
    shortTitle: "Particules",
    questionText: "Cite 9 particules étudiées en physique.",
    answers: [
      "Électron",
      "Proton",
      "Neutron",
      "Photon",
      "Neutrino",
      "Muon",
      "Quark",
      "Gluon",
      "Boson de Higgs",
    ],
    sources: [science],
  }),
  q({
    id: "play-science-women",
    themeId: "science",
    subthemeId: "science:discoveries",
    difficultyLevel: 3,
    shortTitle: "Femmes de science",
    questionText: "Cite 9 femmes qui ont marqué l’histoire des sciences.",
    answers: [
      "Marie Curie",
      "Rosalind Franklin",
      "Ada Lovelace",
      "Jane Goodall",
      "Katherine Johnson",
      "Lise Meitner",
      "Chien-Shiung Wu",
      "Vera Rubin",
      "Emmanuelle Charpentier",
    ],
    sources: [science],
  }),
  q({
    id: "play-science-space-missions",
    themeId: "science",
    subthemeId: "science:astronomy",
    difficultyLevel: 3,
    shortTitle: "Exploration spatiale",
    questionText: "Cite 9 sondes ou télescopes spatiaux célèbres.",
    answers: [
      "Hubble",
      "James-Webb",
      "Voyager 1",
      "Voyager 2",
      "Cassini",
      "New Horizons",
      "Juno",
      "Gaia",
      "Kepler",
    ],
    sources: [science],
  }),
  q({
    id: "play-science-instruments",
    themeId: "science",
    subthemeId: "science:discoveries",
    difficultyLevel: 3,
    shortTitle: "Instruments scientifiques",
    questionText: "Cite 9 instruments utilisés pour observer ou mesurer en science.",
    answers: [
      "Microscope",
      "Télescope",
      "Spectromètre",
      "Sismographe",
      "Baromètre",
      "Accéléromètre",
      "Oscilloscope",
      "Calorimètre",
      "Interféromètre",
    ],
    sources: [science],
  }),

  q({
    id: "play-sport-rackets",
    themeId: "sport",
    subthemeId: "sport:tennis",
    difficultyLevel: 2,
    shortTitle: "Sports de raquette",
    questionText: "Cite 9 sports qui se jouent avec une raquette ou une palette.",
    answers: [
      "Tennis",
      "Badminton",
      "Squash",
      "Padel",
      "Tennis de table",
      "Racquetball",
      "Pickleball",
      "Beach tennis",
      "Jeu de paume",
    ],
    sources: [sport],
  }),
  q({
    id: "play-sport-icons",
    themeId: "sport",
    subthemeId: "sport:team-sports",
    difficultyLevel: 2,
    shortTitle: "Icônes du sport",
    questionText: "Cite 9 sportives devenues des icônes mondiales.",
    answers: [
      "Serena Williams",
      "Simone Biles",
      "Marta",
      "Allyson Felix",
      "Nadia Comăneci",
      "Billie Jean King",
      "Megan Rapinoe",
      "Katie Ledecky",
      "Ronda Rousey",
    ],
    sources: [sport],
  }),

  q({
    id: "play-tech-operating-systems",
    themeId: "technology",
    subthemeId: "technology:operating-systems",
    difficultyLevel: 1,
    shortTitle: "Systèmes connus",
    questionText: "Cite 9 systèmes d’exploitation connus du grand public.",
    answers: [
      "Windows",
      "macOS",
      "Android",
      "iOS",
      "Linux",
      "ChromeOS",
      "Ubuntu",
      "PlayStation OS",
      "HarmonyOS",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-devices",
    themeId: "technology",
    subthemeId: "technology:devices",
    difficultyLevel: 1,
    shortTitle: "Appareils connectés",
    questionText: "Cite 9 types d’appareils que l’on peut connecter à Internet.",
    answers: [
      "Smartphone",
      "Ordinateur",
      "Tablette",
      "Télévision",
      "Console de jeux",
      "Montre connectée",
      "Enceinte connectée",
      "Caméra",
      "Imprimante",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-languages",
    themeId: "technology",
    subthemeId: "technology:software",
    difficultyLevel: 2,
    shortTitle: "Langages informatiques",
    questionText: "Cite 9 langages de programmation connus.",
    answers: [
      "Python",
      "JavaScript",
      "Java",
      "Langage C",
      "C Plus Plus",
      "C Sharp",
      "PHP",
      "Swift",
      "Ruby",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-creative-software",
    themeId: "technology",
    subthemeId: "technology:software",
    difficultyLevel: 2,
    shortTitle: "Logiciels créatifs",
    questionText: "Cite 9 logiciels utilisés pour créer des images, vidéos ou sons.",
    answers: [
      "Photoshop",
      "Illustrator",
      "Premiere Pro",
      "After Effects",
      "Blender",
      "Final Cut Pro",
      "Pro Tools",
      "Ableton Live",
      "DaVinci Resolve",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-storage",
    themeId: "technology",
    subthemeId: "technology:devices",
    difficultyLevel: 2,
    shortTitle: "Stockage numérique",
    questionText: "Cite 9 supports ou services de stockage numérique.",
    answers: [
      "Disque dur",
      "SSD",
      "Clé USB",
      "Carte SD",
      "CD-ROM",
      "DVD",
      "Blu-ray",
      "Google Drive",
      "iCloud",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-open-source",
    themeId: "technology",
    subthemeId: "technology:software",
    difficultyLevel: 3,
    shortTitle: "Open source",
    questionText: "Cite 9 logiciels ou projets open source très connus.",
    answers: [
      "Linux",
      "Firefox",
      "LibreOffice",
      "VLC",
      "Blender",
      "GIMP",
      "WordPress",
      "Kubernetes",
      "Git",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-cybersecurity",
    themeId: "technology",
    subthemeId: "technology:computers",
    difficultyLevel: 3,
    shortTitle: "Cybersécurité",
    questionText: "Cite 9 termes courants de cybersécurité.",
    answers: [
      "Phishing",
      "Ransomware",
      "Malware",
      "Pare-feu",
      "VPN",
      "Chiffrement",
      "Authentification à deux facteurs",
      "Cheval de Troie",
      "Attaque DDoS",
    ],
    sources: [technology],
  }),
  q({
    id: "play-tech-inventors",
    themeId: "technology",
    subthemeId: "technology:inventions",
    difficultyLevel: 3,
    shortTitle: "Inventeurs et inventrices",
    questionText: "Cite 9 personnes liées à une invention technologique majeure.",
    answers: [
      "Alexander Graham Bell",
      "Thomas Edison",
      "Nikola Tesla",
      "Hedy Lamarr",
      "Tim Berners-Lee",
      "Ada Lovelace",
      "Grace Hopper",
      "Steve Wozniak",
      "James Dyson",
    ],
    sources: [technology],
  }),

  q({
    id: "play-celebrities-tom-cruise",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Tom Cruise",
    questionText: "Cite 9 films connus avec Tom Cruise.",
    answers: [
      "Top Gun",
      "Mission: Impossible",
      "Rain Man",
      "Jerry Maguire",
      "Minority Report",
      "Le Dernier Samouraï",
      "La Guerre des mondes",
      "Jack Reacher",
      "Edge of Tomorrow",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-will-smith",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Will Smith",
    questionText: "Cite 9 films connus avec Will Smith.",
    answers: [
      "Bad Boys",
      "Independence Day",
      "Men in Black",
      "Ali",
      "I, Robot",
      "Hitch",
      "À la recherche du bonheur",
      "Je suis une légende",
      "Aladdin",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-dicaprio",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Leonardo DiCaprio",
    questionText: "Cite 9 films connus avec Leonardo DiCaprio.",
    answers: [
      "Titanic",
      "Roméo + Juliette",
      "Arrête-moi si tu peux",
      "Aviator",
      "Les Infiltrés",
      "Inception",
      "Django Unchained",
      "Le Loup de Wall Street",
      "The Revenant",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-jennifer-lawrence",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Jennifer Lawrence",
    questionText: "Cite 9 films connus avec Jennifer Lawrence.",
    answers: [
      "Hunger Games",
      "Happiness Therapy",
      "X-Men : Le Commencement",
      "American Bluff",
      "Joy",
      "Passengers",
      "Mother!",
      "Red Sparrow",
      "Don't Look Up",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-emma-watson",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 1,
    shortTitle: "Emma Watson",
    questionText: "Cite 9 films avec Emma Watson.",
    answers: [
      "Harry Potter à l'école des sorciers",
      "Harry Potter et la Chambre des secrets",
      "Harry Potter et le Prisonnier d'Azkaban",
      "Harry Potter et la Coupe de feu",
      "Harry Potter et l'Ordre du Phénix",
      "Harry Potter et le Prince de sang-mêlé",
      "Harry Potter et les Reliques de la Mort",
      "La Belle et la Bête",
      "Les Filles du docteur March",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-meryl",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Meryl Streep",
    questionText: "Cite 9 films connus avec Meryl Streep.",
    answers: [
      "Kramer contre Kramer",
      "Le Choix de Sophie",
      "Out of Africa",
      "Sur la route de Madison",
      "Le Diable s'habille en Prada",
      "Mamma Mia!",
      "Julie et Julia",
      "La Dame de fer",
      "Pentagon Papers",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-denzel",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Denzel Washington",
    questionText: "Cite 9 films connus avec Denzel Washington.",
    answers: [
      "Glory",
      "Malcolm X",
      "Philadelphia",
      "Training Day",
      "Man on Fire",
      "Inside Man",
      "American Gangster",
      "Equalizer",
      "Fences",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-portman",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Natalie Portman",
    questionText: "Cite 9 films connus avec Natalie Portman.",
    answers: [
      "Léon",
      "Heat",
      "Mars Attacks!",
      "Star Wars : La Menace fantôme",
      "V pour Vendetta",
      "Black Swan",
      "Thor",
      "Jackie",
      "May December",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-scarlett",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Scarlett Johansson",
    questionText: "Cite 9 films connus avec Scarlett Johansson.",
    answers: [
      "Lost in Translation",
      "La Jeune Fille à la perle",
      "Match Point",
      "Iron Man 2",
      "Avengers",
      "Lucy",
      "Ghost in the Shell",
      "Marriage Story",
      "Black Widow",
    ],
    sources: [celebrities],
  }),
  q({
    id: "play-celebrities-dujardin",
    themeId: "celebrities",
    subthemeId: "celebrities:actors",
    difficultyLevel: 2,
    shortTitle: "Jean Dujardin",
    questionText: "Cite 9 films connus avec Jean Dujardin.",
    answers: [
      "Brice de Nice",
      "OSS 117 : Le Caire, nid d'espions",
      "99 francs",
      "Un balcon sur la mer",
      "The Artist",
      "Les Infidèles",
      "Le Loup de Wall Street",
      "La French",
      "Novembre",
    ],
    sources: [celebrities],
  }),

  q({
    id: "play-comics-marvel-villains",
    themeId: "comics-manga",
    subthemeId: "comics-manga:superheroes",
    difficultyLevel: 3,
    shortTitle: "Vilains Marvel",
    questionText: "Cite 9 grands ennemis des héros Marvel.",
    answers: [
      "Thanos",
      "Loki",
      "Docteur Fatalis",
      "Magnéto",
      "Bouffon vert",
      "Crâne rouge",
      "Ultron",
      "Kingpin",
      "Galactus",
    ],
    sources: [comics],
  }),
  q({
    id: "play-comics-dc-villains",
    themeId: "comics-manga",
    subthemeId: "comics-manga:superheroes",
    difficultyLevel: 3,
    shortTitle: "Vilains DC",
    questionText: "Cite 9 grands ennemis des héros DC Comics.",
    answers: [
      "Joker",
      "Lex Luthor",
      "Darkseid",
      "Harley Quinn",
      "Bane",
      "Sinestro",
      "Reverse-Flash",
      "Black Manta",
      "Brainiac",
    ],
    sources: [comics],
  }),
  q({
    id: "play-comics-manga-heroes",
    themeId: "comics-manga",
    subthemeId: "comics-manga:manga",
    difficultyLevel: 3,
    shortTitle: "Héros de manga",
    questionText: "Cite 9 héros ou héroïnes de mangas célèbres.",
    answers: [
      "Son Goku",
      "Naruto Uzumaki",
      "Monkey D. Luffy",
      "Ichigo Kurosaki",
      "Sailor Moon",
      "Edward Elric",
      "Eren Jäger",
      "Izuku Midoriya",
      "Tanjiro Kamado",
    ],
    sources: [comics],
  }),
  q({
    id: "play-comics-cities",
    themeId: "comics-manga",
    subthemeId: "comics-manga:superheroes",
    difficultyLevel: 3,
    shortTitle: "Villes de comics",
    questionText: "Cite 9 villes ou pays fictifs célèbres des comics.",
    answers: [
      "Gotham City",
      "Metropolis",
      "Wakanda",
      "Latveria",
      "Atlantis",
      "Themyscira",
      "Central City",
      "Genosha",
      "Asgard",
    ],
    sources: [comics],
  }),
  q({
    id: "play-comics-objects",
    themeId: "comics-manga",
    subthemeId: "comics-manga:superheroes",
    difficultyLevel: 3,
    shortTitle: "Objets de comics",
    questionText: "Cite 9 objets ou substances cultes des comics.",
    answers: [
      "Kryptonite",
      "Gant de l'Infini",
      "Mjolnir",
      "Bouclier de Captain America",
      "Anneau de Green Lantern",
      "Lasso de vérité",
      "Toile de Spider-Man",
      "Adamantium",
      "Sérum du Super-Soldat",
    ],
    sources: [comics],
  }),

  q({
    id: "play-music-stage-names",
    themeId: "music",
    subthemeId: "music:artists-groups",
    difficultyLevel: 3,
    shortTitle: "Noms de scène",
    questionText: "Cite 9 artistes connus sous un nom de scène.",
    answers: [
      "Sting",
      "Bono",
      "Lady Gaga",
      "The Weeknd",
      "Snoop Dogg",
      "Elton John",
      "Freddie Mercury",
      "M. Pokora",
      "Christine and the Queens",
    ],
    sources: [music],
  }),
  q({
    id: "play-music-siblings",
    themeId: "music",
    subthemeId: "music:artists-groups",
    difficultyLevel: 3,
    shortTitle: "Groupes de famille",
    questionText: "Cite 9 groupes comprenant des frères ou des sœurs.",
    answers: [
      "Oasis",
      "AC/DC",
      "Bee Gees",
      "The Beach Boys",
      "The Corrs",
      "Kings of Leon",
      "The Jackson 5",
      "Hanson",
      "HAIM",
    ],
    sources: [music],
  }),
  q({
    id: "play-music-film-composers",
    themeId: "music",
    subthemeId: "music:artists-groups",
    difficultyLevel: 3,
    shortTitle: "Musique de film",
    questionText: "Cite 9 compositeurs ou compositrices de musique de film.",
    answers: [
      "John Williams",
      "Hans Zimmer",
      "Ennio Morricone",
      "Howard Shore",
      "Alexandre Desplat",
      "Danny Elfman",
      "James Horner",
      "Hildur Guðnadóttir",
      "Ryuichi Sakamoto",
    ],
    sources: [music],
  }),
  q({
    id: "play-music-djs",
    themeId: "music",
    subthemeId: "music:genres",
    difficultyLevel: 3,
    shortTitle: "DJ célèbres",
    questionText: "Cite 9 DJ ou artistes électro connus dans le monde.",
    answers: [
      "David Guetta",
      "Martin Garrix",
      "Calvin Harris",
      "Tiësto",
      "Skrillex",
      "Deadmau5",
      "Avicii",
      "Charlotte de Witte",
      "Peggy Gou",
    ],
    sources: [music],
  }),
  q({
    id: "play-music-festivals",
    themeId: "music",
    subthemeId: "music:awards-festivals",
    difficultyLevel: 3,
    shortTitle: "Festivals de musique",
    questionText: "Cite 9 grands festivals de musique dans le monde.",
    answers: [
      "Glastonbury",
      "Coachella",
      "Tomorrowland",
      "Rock en Seine",
      "Hellfest",
      "Lollapalooza",
      "Primavera Sound",
      "Sziget",
      "Fuji Rock",
    ],
    sources: [music],
  }),

  q({
    id: "play-literature-detectives",
    themeId: "literature",
    subthemeId: "literature:genres",
    difficultyLevel: 3,
    shortTitle: "Détectives de romans",
    questionText: "Cite 9 enquêteurs célèbres de la littérature.",
    answers: [
      "Sherlock Holmes",
      "Hercule Poirot",
      "Miss Marple",
      "Arsène Lupin",
      "Jules Maigret",
      "Philip Marlowe",
      "C. Auguste Dupin",
      "Harry Bosch",
      "Cormoran Strike",
    ],
    sources: [literature],
  }),
  q({
    id: "play-literature-dystopias",
    themeId: "literature",
    subthemeId: "literature:novels",
    difficultyLevel: 3,
    shortTitle: "Romans dystopiques",
    questionText: "Cite 9 romans dystopiques connus.",
    answers: [
      "1984",
      "Le Meilleur des mondes",
      "Fahrenheit 451",
      "La Servante écarlate",
      "Hunger Games",
      "Nous autres",
      "Le Passeur",
      "La Route",
      "Never Let Me Go",
    ],
    sources: [literature],
  }),
  q({
    id: "play-literature-pen-names",
    themeId: "literature",
    subthemeId: "literature:authors",
    difficultyLevel: 3,
    shortTitle: "Noms de plume",
    questionText: "Cite 9 noms de plume d’écrivains ou d’écrivaines.",
    answers: [
      "George Sand",
      "Voltaire",
      "Mark Twain",
      "George Orwell",
      "Stendhal",
      "Lewis Carroll",
      "Colette",
      "Romain Gary",
      "Robert Galbraith",
    ],
    sources: [literature],
  }),
  q({
    id: "play-literature-fantasy-objects",
    themeId: "literature",
    subthemeId: "literature:genres",
    difficultyLevel: 3,
    shortTitle: "Objets de fantasy",
    questionText: "Cite 9 objets magiques célèbres de romans fantastiques.",
    answers: [
      "Anneau Unique",
      "Baguette de Sureau",
      "Excalibur",
      "Armoire de Narnia",
      "Aléthiomètre",
      "Tapis volant",
      "Pierre philosophale",
      "Épée de Gryffondor",
      "Palantír",
    ],
    sources: [literature],
  }),
  q({
    id: "play-literature-world-authors",
    themeId: "literature",
    subthemeId: "literature:authors",
    difficultyLevel: 3,
    shortTitle: "Auteurs du monde",
    questionText: "Cite 9 auteurs ou autrices majeurs hors France et monde anglophone.",
    answers: [
      "Gabriel García Márquez",
      "Haruki Murakami",
      "Jorge Luis Borges",
      "Franz Kafka",
      "Umberto Eco",
      "Elena Ferrante",
      "Chimamanda Ngozi Adichie",
      "Orhan Pamuk",
      "Isabel Allende",
    ],
    sources: [literature],
  }),

  q({
    id: "play-mythology-underworld",
    themeId: "mythology-legends",
    subthemeId: "mythology-legends:world-legends",
    difficultyLevel: 3,
    shortTitle: "Divinités des morts",
    questionText: "Cite 9 divinités liées à la mort ou au monde souterrain.",
    answers: [
      "Hadès",
      "Anubis",
      "Osiris",
      "Hel",
      "Yama",
      "Ereshkigal",
      "Mictlantecuhtli",
      "Baron Samedi",
      "Perséphone",
    ],
    sources: [mythology],
  }),
  q({
    id: "play-mythology-tricksters",
    themeId: "mythology-legends",
    subthemeId: "mythology-legends:world-legends",
    difficultyLevel: 3,
    shortTitle: "Figures rusées",
    questionText: "Cite 9 figures de filou ou trickster dans les mythologies.",
    answers: [
      "Loki",
      "Hermès",
      "Anansi",
      "Coyote",
      "Renard",
      "Sun Wukong",
      "Maui",
      "Èṣù",
      "Kitsune",
    ],
    sources: [mythology],
  }),

  q({
    id: "play-history-ancient-cities",
    themeId: "history",
    subthemeId: "history:antiquity",
    difficultyLevel: 3,
    shortTitle: "Cités antiques",
    questionText: "Cite 9 grandes cités du monde antique.",
    answers: [
      "Rome",
      "Athènes",
      "Sparte",
      "Alexandrie",
      "Carthage",
      "Babylone",
      "Thèbes",
      "Pompéi",
      "Persépolis",
    ],
    sources: [history],
  }),
  q({
    id: "play-history-women-rulers",
    themeId: "history",
    subthemeId: "history:leaders",
    difficultyLevel: 3,
    shortTitle: "Femmes de pouvoir",
    questionText: "Cite 9 femmes ayant dirigé un État ou un empire avant 1950.",
    answers: [
      "Cléopâtre",
      "Élisabeth Ire",
      "Catherine II",
      "Victoria",
      "Wu Zetian",
      "Isabelle de Castille",
      "Marie-Thérèse d'Autriche",
      "Rani Lakshmibai",
      "Liliʻuokalani",
    ],
    sources: [history],
  }),
  q({
    id: "play-history-explorers",
    themeId: "history",
    subthemeId: "history:modern-era",
    difficultyLevel: 3,
    shortTitle: "Explorateurs",
    questionText: "Cite 9 explorateurs ou exploratrices célèbres.",
    answers: [
      "Christophe Colomb",
      "Vasco de Gama",
      "Fernand de Magellan",
      "James Cook",
      "Marco Polo",
      "Zheng He",
      "Ibn Battûta",
      "Jeanne Barret",
      "Roald Amundsen",
    ],
    sources: [history],
  }),
  q({
    id: "play-history-revolutions",
    themeId: "history",
    subthemeId: "history:contemporary-history",
    difficultyLevel: 3,
    shortTitle: "Révolutions",
    questionText: "Cite 9 révolutions ou grands soulèvements historiques.",
    answers: [
      "Révolution française",
      "Révolution américaine",
      "Révolution russe",
      "Révolution haïtienne",
      "Révolution mexicaine",
      "Printemps des peuples",
      "Révolution des Œillets",
      "Révolution iranienne",
      "Printemps arabe",
    ],
    sources: [history],
  }),

  q({
    id: "play-france-inventions",
    themeId: "france",
    subthemeId: "france:heritage",
    difficultyLevel: 3,
    shortTitle: "Inventions françaises",
    questionText: "Cite 9 inventions ou innovations associées à la France.",
    answers: [
      "Montgolfière",
      "Photographie",
      "Cinématographe",
      "Braille",
      "Pasteurisation",
      "Stéthoscope",
      "Parachute",
      "Minitel",
      "Carte à puce",
    ],
    sources: [france],
  }),
  q({
    id: "play-france-women-history",
    themeId: "france",
    subthemeId: "france:history",
    difficultyLevel: 3,
    shortTitle: "Françaises historiques",
    questionText: "Cite 9 femmes qui ont marqué l’histoire de France.",
    answers: [
      "Jeanne d'Arc",
      "Olympe de Gouges",
      "Marie Curie",
      "Simone Veil",
      "Joséphine Baker",
      "George Sand",
      "Louise Michel",
      "Hubertine Auclert",
      "Agnès Varda",
    ],
    sources: [france],
  }),

  q({
    id: "play-cinema-composers",
    themeId: "cinema",
    subthemeId: "cinema:films",
    difficultyLevel: 3,
    shortTitle: "Compositeurs de cinéma",
    questionText: "Cite 9 compositeurs connus pour leurs musiques de film.",
    answers: [
      "John Williams",
      "Hans Zimmer",
      "Ennio Morricone",
      "Howard Shore",
      "Alexandre Desplat",
      "Danny Elfman",
      "James Horner",
      "Vangelis",
      "Joe Hisaishi",
    ],
    sources: [cinema],
  }),
  q({
    id: "play-cinema-horror-franchises",
    themeId: "cinema",
    subthemeId: "cinema:films",
    difficultyLevel: 3,
    shortTitle: "Sagas horrifiques",
    questionText: "Cite 9 grandes sagas du cinéma d’horreur.",
    answers: [
      "Halloween",
      "Vendredi 13",
      "Scream",
      "Saw",
      "Conjuring",
      "Evil Dead",
      "L'Exorciste",
      "Alien",
      "Destination finale",
    ],
    sources: [cinema],
  }),
  q({
    id: "play-cinema-star-wars",
    themeId: "cinema",
    subthemeId: "cinema:sagas",
    difficultyLevel: 1,
    shortTitle: "Personnages Star Wars",
    questionText: "Cite 9 personnages très connus de Star Wars.",
    answers: [
      "Luke Skywalker",
      "Leia Organa",
      "Han Solo",
      "Dark Vador",
      "Yoda",
      "Obi-Wan Kenobi",
      "Chewbacca",
      "R2-D2",
      "C-3PO",
    ],
    sources: [cinema],
  }),

  q({
    id: "play-pop-artifacts",
    themeId: "pop-culture",
    subthemeId: "pop-culture:franchises",
    difficultyLevel: 3,
    shortTitle: "Objets cultes",
    questionText: "Cite 9 objets fictifs cultes de la pop culture.",
    answers: [
      "Sabre laser",
      "Anneau Unique",
      "Baguette magique",
      "Hoverboard",
      "DeLorean",
      "Tricordeur",
      "Poké Ball",
      "Dragon Balls",
      "Omnitrix",
    ],
    sources: [popCulture],
  }),
  q({
    id: "play-pop-board-games",
    themeId: "pop-culture",
    subthemeId: "pop-culture:toys-games",
    difficultyLevel: 3,
    shortTitle: "Jeux de société modernes",
    questionText: "Cite 9 jeux de société modernes très connus.",
    answers: [
      "Catan",
      "Carcassonne",
      "7 Wonders",
      "Dixit",
      "Codenames",
      "Azul",
      "Ticket to Ride",
      "Pandemic",
      "Time's Up!",
    ],
    sources: [popCulture],
  }),
  q({
    id: "play-pop-mascots",
    themeId: "pop-culture",
    subthemeId: "pop-culture:characters",
    difficultyLevel: 3,
    shortTitle: "Mascottes célèbres",
    questionText: "Cite 9 mascottes célèbres de marques ou de franchises.",
    answers: [
      "Bibendum",
      "Mario",
      "Pikachu",
      "Sonic",
      "Tony le Tigre",
      "Colonel Sanders",
      "Ronald McDonald",
      "M. Propre",
      "Duo le hibou",
    ],
    sources: [popCulture],
  }),
  q({
    id: "play-pop-fictional-schools",
    themeId: "pop-culture",
    subthemeId: "pop-culture:franchises",
    difficultyLevel: 3,
    shortTitle: "Écoles fictives",
    questionText: "Cite 9 écoles ou académies fictives de la pop culture.",
    answers: [
      "Poudlard",
      "Xavier's School",
      "U.A. High School",
      "Nevermore Academy",
      "Greendale Community College",
      "Beacon Academy",
      "Hexside",
      "East High",
      "Académie Jedi",
    ],
    sources: [popCulture],
  }),
  q({
    id: "play-pop-teams",
    themeId: "pop-culture",
    subthemeId: "pop-culture:characters",
    difficultyLevel: 3,
    shortTitle: "Équipes de héros",
    questionText: "Cite 9 équipes de héros ou d’aventuriers fictifs.",
    answers: [
      "Avengers",
      "Justice League",
      "X-Men",
      "Gardiens de la Galaxie",
      "Tortues Ninja",
      "Fantastic Four",
      "Power Rangers",
      "Ghostbusters",
      "Communauté de l'Anneau",
    ],
    sources: [popCulture],
  }),

  q({
    id: "play-games-villains",
    themeId: "video-games",
    subthemeId: "video-games:characters",
    difficultyLevel: 3,
    shortTitle: "Méchant de jeux vidéo",
    questionText: "Cite 9 grands antagonistes de jeux vidéo.",
    answers: [
      "Bowser",
      "Ganondorf",
      "Sephiroth",
      "Dr Eggman",
      "Albert Wesker",
      "GLaDOS",
      "Vaas Montenegro",
      "Pagan Min",
      "Handsome Jack",
    ],
    sources: [videoGames],
  }),
  q({
    id: "play-games-heroines",
    themeId: "video-games",
    subthemeId: "video-games:characters",
    difficultyLevel: 3,
    shortTitle: "Héroïnes de jeux vidéo",
    questionText: "Cite 9 héroïnes jouables de jeux vidéo.",
    answers: [
      "Lara Croft",
      "Samus Aran",
      "Aloy",
      "Ellie",
      "Bayonetta",
      "Chun-Li",
      "Jill Valentine",
      "Clementine",
      "Senua",
    ],
    sources: [videoGames],
  }),
  q({
    id: "play-games-cities",
    themeId: "video-games",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Villes de jeux vidéo",
    questionText: "Cite 9 villes ou régions fictives célèbres de jeux vidéo.",
    answers: [
      "Hyrule",
      "Raccoon City",
      "Night City",
      "Los Santos",
      "Vice City",
      "City 17",
      "Midgar",
      "Columbia",
      "Yharnam",
    ],
    sources: [videoGames],
  }),
  q({
    id: "play-games-studios",
    themeId: "video-games",
    subthemeId: "video-games:studios",
    difficultyLevel: 3,
    shortTitle: "Studios de jeux vidéo",
    questionText: "Cite 9 studios de jeux vidéo connus dans le monde.",
    answers: [
      "Nintendo",
      "Rockstar Games",
      "Naughty Dog",
      "FromSoftware",
      "Ubisoft",
      "Bethesda Game Studios",
      "CD Projekt Red",
      "Capcom",
      "Valve",
    ],
    sources: [videoGames],
  }),

  q({
    id: "play-geography-equator",
    themeId: "geography",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 3,
    shortTitle: "Sur l’équateur",
    questionText: "Cite 9 pays traversés par l’équateur.",
    answers: [
      "Équateur",
      "Colombie",
      "Brésil",
      "Gabon",
      "Congo",
      "République démocratique du Congo",
      "Ouganda",
      "Kenya",
      "Indonésie",
    ],
    sources: [geography],
  }),
  q({
    id: "play-geography-landlocked-africa",
    themeId: "geography",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 3,
    shortTitle: "Afrique sans littoral",
    questionText: "Cite 9 pays africains sans accès à la mer.",
    answers: [
      "Mali",
      "Niger",
      "Tchad",
      "Burkina Faso",
      "Zambie",
      "Zimbabwe",
      "Rwanda",
      "Ouganda",
      "Botswana",
    ],
    sources: [geography],
  }),
  q({
    id: "play-geography-islands-caribbean",
    themeId: "geography",
    subthemeId: "geography:mountains-islands",
    difficultyLevel: 3,
    shortTitle: "Caraïbes",
    questionText: "Cite 9 États insulaires des Caraïbes.",
    answers: [
      "Cuba",
      "Jamaïque",
      "Haïti",
      "République dominicaine",
      "Bahamas",
      "Barbade",
      "Sainte-Lucie",
      "Grenade",
      "Trinité-et-Tobago",
    ],
    sources: [geography],
  }),
  q({
    id: "play-geography-mountain-capitals",
    themeId: "geography",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 3,
    shortTitle: "Capitales en altitude",
    questionText: "Cite 9 capitales situées à plus de 1 000 mètres d’altitude.",
    answers: [
      "La Paz",
      "Quito",
      "Bogotá",
      "Addis-Abeba",
      "Mexico",
      "Kaboul",
      "Nairobi",
      "Sanaa",
      "Thimphou",
    ],
    sources: [geography],
  }),
  q({
    id: "play-geography-two-seas",
    themeId: "geography",
    subthemeId: "geography:countries-capitals",
    difficultyLevel: 3,
    shortTitle: "Entre deux mers",
    questionText: "Cite 9 pays bordés par au moins deux mers ou océans distincts.",
    answers: [
      "France",
      "Espagne",
      "Maroc",
      "Égypte",
      "Turquie",
      "Russie",
      "Canada",
      "Mexique",
      "Afrique du Sud",
    ],
    sources: [geography],
  }),

  q({
    id: "play-football-stadiums",
    themeId: "football",
    subthemeId: "football:stadiums",
    difficultyLevel: 3,
    shortTitle: "Stades mythiques",
    questionText: "Cite 9 stades mythiques du football mondial.",
    answers: [
      "Maracanã",
      "Wembley",
      "Camp Nou",
      "Santiago-Bernabéu",
      "San Siro",
      "Anfield",
      "Signal Iduna Park",
      "La Bombonera",
      "Stade de France",
    ],
    sources: [football],
  }),
  q({
    id: "play-football-coaches",
    themeId: "football",
    subthemeId: "football:clubs-players",
    difficultyLevel: 3,
    shortTitle: "Grands entraîneurs",
    questionText: "Cite 9 entraîneurs célèbres du football moderne.",
    answers: [
      "Pep Guardiola",
      "José Mourinho",
      "Carlo Ancelotti",
      "Jürgen Klopp",
      "Zinédine Zidane",
      "Alex Ferguson",
      "Arsène Wenger",
      "Didier Deschamps",
      "Diego Simeone",
    ],
    sources: [football],
  }),
  q({
    id: "play-football-derbies",
    themeId: "football",
    subthemeId: "football:clubs-players",
    difficultyLevel: 3,
    shortTitle: "Grands derbies",
    questionText: "Cite 9 affiches considérées comme de grands derbies ou classiques.",
    answers: [
      "Real Madrid - FC Barcelone",
      "Celtic - Rangers",
      "Boca Juniors - River Plate",
      "Inter - AC Milan",
      "Liverpool - Manchester United",
      "Marseille - Paris",
      "Roma - Lazio",
      "Fenerbahçe - Galatasaray",
      "Benfica - Porto",
    ],
    sources: [football],
  }),

  q({
    id: "play-sport-ball-games",
    themeId: "sport",
    subthemeId: "sport:team-sports",
    difficultyLevel: 1,
    shortTitle: "Sports de ballon",
    questionText: "Cite 9 sports collectifs qui se jouent avec un ballon ou une balle.",
    answers: [
      "Football",
      "Basketball",
      "Handball",
      "Volleyball",
      "Rugby",
      "Baseball",
      "Hockey sur gazon",
      "Water-polo",
      "Cricket",
    ],
    sources: [sport],
  }),

  q({
    id: "play-nature-phenomena",
    themeId: "nature",
    subthemeId: "nature:climate",
    difficultyLevel: 3,
    shortTitle: "Phénomènes naturels",
    questionText: "Cite 9 phénomènes naturels rares ou spectaculaires.",
    answers: [
      "Aurore polaire",
      "Éclipse",
      "Tornade",
      "Tsunami",
      "Foudre en boule",
      "Geyser",
      "Volcan de boue",
      "Halo solaire",
      "Pluie d'étoiles filantes",
    ],
    sources: [nature],
  }),
  q({
    id: "play-sport-martial-arts",
    themeId: "sport",
    subthemeId: "sport:team-sports",
    difficultyLevel: 3,
    shortTitle: "Arts martiaux",
    questionText: "Cite 9 arts martiaux ou sports de combat nés en Asie.",
    answers: [
      "Judo",
      "Karaté",
      "Taekwondo",
      "Kung-fu",
      "Aïkido",
      "Muay-thaï",
      "Kendo",
      "Sumo",
      "Silat",
    ],
    sources: [sport],
  }),
  q({
    id: "play-sport-endurance",
    themeId: "sport",
    subthemeId: "sport:athletics",
    difficultyLevel: 3,
    shortTitle: "Épreuves d’endurance",
    questionText: "Cite 9 grandes compétitions d’endurance.",
    answers: [
      "Marathon de New York",
      "Ironman d'Hawaï",
      "Tour de France",
      "Giro",
      "Vuelta",
      "Dakar",
      "24 Heures du Mans",
      "Ultra-Trail du Mont-Blanc",
      "Vendée Globe",
    ],
    sources: [sport],
  }),
  q({
    id: "play-sport-winter",
    themeId: "sport",
    subthemeId: "sport:olympic-games",
    difficultyLevel: 3,
    shortTitle: "Sports d’hiver",
    questionText: "Cite 9 disciplines présentes aux Jeux olympiques d’hiver.",
    answers: [
      "Ski alpin",
      "Biathlon",
      "Ski de fond",
      "Saut à ski",
      "Snowboard",
      "Patinage artistique",
      "Patinage de vitesse",
      "Bobsleigh",
      "Curling",
    ],
    sources: [sport],
  }),
];
