const source=(id,title,publisher,url,primary=true)=>({id,title,publisher,url,isPrimarySource:primary});
const q=(s)=>({themeId:"pop-culture",qualificationRule:s.qualificationRule??"Sont retenus les neuf éléments de franchise exactement délimités dans la question.",explanation:s.explanation??"Le catalogue ou guide officiel cité confirme cet ensemble de neuf réponses.",...s});
export const obsoleteQuestionIds=["easy-cluedo-neuf-pieces"];
export const questions=[
q({id:"easy-pokemon-neuf-regions",subthemeId:"pop-culture:franchises",difficultyLevel:1,shortTitle:"Les régions de Pokémon",questionText:"Quelles sont les neuf régions principales des jeux Pokémon des générations I à IX ?",answers:["Kanto","Johto","Hoenn","Sinnoh","Unys","Kalos","Alola","Galar","Paldea"],sources:[source("pokemon-regions","Explore the world of Pokémon","The Pokémon Company International","https://www.pokemon.com/us/pokemon-video-games/all-pokemon-games",true)]}),
q({id:"easy-dnd-neuf-alignements",subthemeId:"pop-culture:toys-games",difficultyLevel:1,shortTitle:"Les alignements de D&D",questionText:"Quels sont les neuf alignements classiques de Donjons & Dragons ?",answers:["Loyal bon","Neutre bon","Chaotique bon","Loyal neutre","Neutre strict","Chaotique neutre","Loyal mauvais","Neutre mauvais","Chaotique mauvais"],sources:[source("dnd-alignments","Alignment","D&D Beyond","https://www.dndbeyond.com/sources/dnd/basic-rules-2014/personality-and-background#Alignment",true)]}),
q({id:"easy-mario-kart-neuf-premiers",subthemeId:"pop-culture:toys-games",difficultyLevel:1,shortTitle:"Les pièces du Cluedo",questionText:"Quelles sont les neuf pièces du manoir sur le plateau classique du Cluedo ?",answers:["Cuisine","Salle de bal","Véranda","Salle à manger","Salle de billard","Bibliothèque","Petit salon","Hall","Bureau"],sources:[source("hasbro-cluedo-rules","Cluedo — règles du jeu classique","Hasbro","https://instructions.hasbro.com/fr-fr/instruction/clue-game",true)]}),
q({id:"easy-power-rangers-neuf-premieres-series",subthemeId:"pop-culture:franchises",difficultyLevel:1,shortTitle:"Premiers Power Rangers",questionText:"Quelles sont les neuf premières séries ou ères télévisées de Power Rangers, de Mighty Morphin à Force Cyclone ?",answers:["Mighty Morphin Power Rangers","Power Rangers Zeo","Power Rangers Turbo","Power Rangers dans l’espace","Power Rangers : L’Autre Galaxie","Power Rangers : Sauvetage éclair","Power Rangers : La Force du temps","Power Rangers : Force animale","Power Rangers : Force Cyclone"],sources:[source("hasbro-power-rangers","Power Rangers","Hasbro","https://powerrangers.hasbro.com/",true)]}),
q({id:"easy-barbie-neuf-premiers-films",subthemeId:"pop-culture:icons",difficultyLevel:1,shortTitle:"Premiers films Barbie",questionText:"Quels sont les neuf premiers longs-métrages d’animation Barbie, de Casse-Noisette aux 12 Princesses ?",answers:["Barbie dans Casse-Noisette","Barbie, princesse Raiponce","Barbie et le Lac des cygnes","Barbie : Cœur de princesse","Barbie Fairytopia","Barbie et le Cheval magique","Barbie Mermaidia","Le Journal de Barbie","Barbie au bal des douze princesses"],sources:[source("mattel-barbie-movies","Barbie movies","Mattel","https://www.barbie.com/en-us/movies",true)]}),
q({id:"easy-transformers-neuf-films-cinema",subthemeId:"pop-culture:cross-media",difficultyLevel:1,shortTitle:"Films Transformers",questionText:"Quels sont les neuf films Transformers sortis au cinéma de 1986 à Transformers : Le Commencement ?",answers:["La Guerre des robots","Transformers","Transformers 2 : La Revanche","Transformers 3 : La Face cachée de la Lune","Transformers : L’Âge de l’extinction","Transformers: The Last Knight","Bumblebee","Transformers: Rise of the Beasts","Transformers : Le Commencement"],sources:[source("transformers-movies","Transformers movies","Hasbro","https://transformers.hasbro.com/",true)]}),
q({id:"easy-tortues-ninja-neuf-personnages",subthemeId:"pop-culture:characters",difficultyLevel:1,shortTitle:"Personnages des Tortues Ninja",questionText:"Quels sont les quatre Tortues Ninja et les cinq personnages récurrents Splinter, April, Casey, Shredder et Krang ?",answers:["Leonardo","Raphael","Donatello","Michelangelo","Splinter","April O’Neil","Casey Jones","Shredder","Krang"],sources:[source("tmnt-characters","Teenage Mutant Ninja Turtles characters","Nickelodeon","https://www.nick.com/shows/teenage-mutant-ninja-turtles",true)]}),
q({id:"medium-mcu-disney-plus-neuf-premieres",subthemeId:"pop-culture:cross-media",difficultyLevel:2,shortTitle:"Premières séries Marvel Disney+",questionText:"Quelles sont les neuf premières séries Marvel Studios diffusées sur Disney+ ?",answers:["WandaVision","Falcon et le Soldat de l’hiver","Loki","What If…?","Hawkeye","Moon Knight","Miss Marvel","She-Hulk : Avocate","Secret Invasion"],sources:[source("marvel-disney-series","Marvel TV shows","Marvel","https://www.marvel.com/tv-shows",true)]}),
q({id:"medium-star-trek-neuf-premiers-films",subthemeId:"pop-culture:franchises",difficultyLevel:2,shortTitle:"Films Star Trek",questionText:"Quels sont les neuf premiers films Star Trek, du Film à Insurrection ?",answers:["Star Trek, le film","Star Trek 2 : La Colère de Khan","Star Trek 3 : À la recherche de Spock","Star Trek 4 : Retour sur Terre","Star Trek 5 : L’Ultime Frontière","Star Trek 6 : Terre inconnue","Star Trek : Générations","Star Trek : Premier Contact","Star Trek : Insurrection"],sources:[source("startrek-movies","Star Trek movies","Paramount","https://www.startrek.com/movies",true)]}),
q({id:"medium-pokemon-neuf-premieres-sorties",subthemeId:"pop-culture:toys-games",difficultyLevel:2,shortTitle:"Premières versions Pokémon",questionText:"Quelles sont les neuf premières sorties principales ou remakes Pokémon au Japon, de Rouge et Vert à Diamant et Perle ?",answers:["Pokémon Rouge et Vert","Pokémon Bleu","Pokémon Jaune","Pokémon Or et Argent","Pokémon Cristal","Pokémon Rubis et Saphir","Pokémon Émeraude","Pokémon Rouge Feu et Vert Feuille","Pokémon Diamant et Perle"],sources:[source("pokemon-games","All Pokémon games","The Pokémon Company International","https://www.pokemon.com/us/pokemon-video-games/all-pokemon-games",true)]}),
q({id:"medium-kanto-champions-arene",subthemeId:"pop-culture:characters",difficultyLevel:2,shortTitle:"Dresseurs de Kanto",questionText:"Quels sont les huit Champions d’Arène de Kanto et le Maître de la Ligue dans Pokémon Rouge et Bleu ?",answers:["Pierre","Ondine","Major Bob","Erika","Koga","Morgane","Auguste","Giovanni","Blue"],sources:[source("pokemon-kanto","Pokémon Red and Blue","The Pokémon Company International","https://www.pokemon.com/us/pokemon-video-games/pokemon-red-version-and-pokemon-blue-version",true)]}),
q({id:"medium-ghostbusters-neuf-personnages",subthemeId:"pop-culture:characters",difficultyLevel:2,shortTitle:"Personnages de Ghostbusters",questionText:"Quels sont les neuf personnages majeurs des deux premiers films Ghostbusters retenus ici ?",answers:["Peter Venkman","Ray Stantz","Egon Spengler","Winston Zeddemore","Dana Barrett","Louis Tully","Janine Melnitz","Gozer","Bouffe-tout"],sources:[source("sony-ghostbusters","Ghostbusters franchise","Sony Pictures","https://www.sonypictures.com/movies/ghostbusters",true)],qualificationRule:"Sont retenus les quatre chasseurs, leurs trois alliés humains récurrents, Gozer et le fantôme Bouffe-tout."}),
q({id:"medium-doctor-who-neuf-incarnations",subthemeId:"pop-culture:characters",difficultyLevel:2,shortTitle:"Premières incarnations du Docteur",questionText:"Comment désigne-t-on les neuf premières incarnations principales du Docteur dans Doctor Who ?",answers:["Premier Docteur","Deuxième Docteur","Troisième Docteur","Quatrième Docteur","Cinquième Docteur","Sixième Docteur","Septième Docteur","Huitième Docteur","Neuvième Docteur"],sources:[source("bbc-doctors","The Doctors","BBC","https://www.bbc.co.uk/doctorwho/classic/episodeguide/index.shtml",true)]}),
q({id:"medium-star-trek-neuf-capitaines",subthemeId:"pop-culture:characters",difficultyLevel:2,shortTitle:"Capitaines de Star Trek",questionText:"Quels sont les neuf capitaines ou commandants centraux des séries Star Trek retenus, de Kirk à Burnham ?",answers:["James T. Kirk","Jean-Luc Picard","Benjamin Sisko","Kathryn Janeway","Jonathan Archer","Gabriel Lorca","Christopher Pike","Carol Freeman","Michael Burnham"],sources:[source("startrek-captains","Captains","Star Trek","https://www.startrek.com/database?category=characters",true)],qualificationRule:"Sont retenus les commandants centraux de The Original Series, The Next Generation, Deep Space Nine, Voyager, Enterprise, Discovery, Strange New Worlds et Lower Decks."}),
q({id:"hard-magic-neuf-premieres-extensions",subthemeId:"pop-culture:toys-games",difficultyLevel:3,shortTitle:"Premières extensions de Magic",questionText:"Quelles sont les neuf premières extensions autonomes de Magic: The Gathering, d’Arabian Nights à Mirage ?",answers:["Arabian Nights","Antiquities","Legends","The Dark","Fallen Empires","Ice Age","Homelands","Alliances","Mirage"],sources:[source("wizards-magic-sets","Magic card sets archive","Wizards of the Coast","https://magic.wizards.com/en/products/card-set-archive",true)]}),
q({id:"hard-pokemon-tcg-neuf-premieres-extensions",subthemeId:"pop-culture:toys-games",difficultyLevel:3,shortTitle:"Premières extensions Pokémon",questionText:"Quelles sont les neuf premières extensions anglophones du Jeu de Cartes à Collectionner Pokémon ?",answers:["Base Set","Jungle","Fossil","Base Set 2","Team Rocket","Gym Heroes","Gym Challenge","Neo Genesis","Neo Discovery"],sources:[source("pokemon-tcg-expansions","Pokémon TCG card database","The Pokémon Company International","https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/",true)]}),
q({id:"hard-american-girl-neuf-historiques",subthemeId:"pop-culture:toys-games",difficultyLevel:3,shortTitle:"Premières American Girl",questionText:"Quelles sont les neuf premières héroïnes historiques lancées par American Girl, de Samantha à Julie ?",answers:["Samantha Parkington","Kirsten Larson","Molly McIntire","Felicity Merriman","Addy Walker","Josefina Montoya","Kit Kittredge","Kaya’aton’my","Julie Albright"],sources:[source("american-girl-history","Historical Characters","American Girl","https://www.americangirl.com/pages/historical-characters",true)]}),
q({id:"hard-lego-ideas-neuf-premiers",subthemeId:"pop-culture:toys-games",difficultyLevel:3,shortTitle:"Premiers LEGO Ideas",questionText:"Quels sont les neuf premiers projets commercialisés via LEGO Cuusoo puis LEGO Ideas ?",answers:["Shinkai 6500 Submarine","Hayabusa","Minecraft Micro World","Back to the Future DeLorean Time Machine","Mars Science Laboratory Curiosity Rover","Ghostbusters Ecto-1","Exo Suit","Research Institute","Birds"],sources:[source("lego-ideas-products","LEGO Ideas products","LEGO Group","https://ideas.lego.com/blogs/a4ae09b6-0d4c-4307-9da8-3ee9f3d368d6",true)]}),
q({id:"hard-dnd-neuf-premiers-univers",subthemeId:"pop-culture:fandoms",difficultyLevel:3,shortTitle:"Univers de Donjons & Dragons",questionText:"Quels sont les neuf premiers grands univers de campagne publiés pour Donjons & Dragons, de Greyhawk à Planescape ?",answers:["Greyhawk","Blackmoor","Mystara","Dragonlance","Forgotten Realms","Ravenloft","Spelljammer","Dark Sun","Planescape"],sources:[source("dnd-settings","Dungeons & Dragons campaign settings","Wizards of the Coast","https://dnd.wizards.com/products",true)]}),
q({id:"hard-big-finish-neuf-premiers-doctor-who",subthemeId:"pop-culture:fandoms",difficultyLevel:3,shortTitle:"Premiers audios Doctor Who",questionText:"Quels sont les neuf premiers drames audio Doctor Who de la gamme mensuelle Big Finish ?",answers:["The Sirens of Time","Phantasmagoria","Whispers of Terror","The Land of the Dead","The Fearmonger","The Marian Conspiracy","The Genocide Machine","Red Dawn","The Spectre of Lanyon Moor"],sources:[source("big-finish-doctor-who","Doctor Who — The Monthly Adventures","Big Finish Productions","https://www.bigfinish.com/ranges/v/monthly-series",true)]}),
];
