const src = (id, title, publisher, url) => ({ id, title, publisher, url, isPrimarySource: true });
const IOC = src(
  "ioc-olympic-results",
  "Olympic results and history",
  "International Olympic Committee",
  "https://olympics.com/en/olympic-games/olympic-results",
);
const ATP = src(
  "atp-tour-stats",
  "ATP Tour records and statistics",
  "ATP Tour",
  "https://www.atptour.com/en/stats",
);
const WTA = src(
  "wta-stats",
  "WTA official statistics",
  "Women's Tennis Association",
  "https://www.wtatennis.com/stats",
);
const WR = src(
  "world-rugby-records",
  "Rugby World Cup records",
  "World Rugby",
  "https://www.world.rugby/tournaments/rugby-world-cup",
);
const NBA = src(
  "nba-history",
  "NBA history and records",
  "National Basketball Association",
  "https://www.nba.com/history",
);
const F1 = src(
  "f1-hall-of-fame",
  "Formula 1 Hall of Fame",
  "Formula 1",
  "https://www.formula1.com/en/information/drivers-hall-of-fame.7D8eBRy7j95DJV5n5rZC3R",
);
const WA = src(
  "world-athletics-records",
  "World Athletics records",
  "World Athletics",
  "https://worldathletics.org/records/all-time-toplists",
);
const TDF = src(
  "tour-de-france-palmares",
  "Palmarès du Tour de France",
  "Amaury Sport Organisation",
  "https://www.letour.fr/fr/histoire",
);
const q = ([id, sub, d, title, text, answers, source = IOC, rule]) => ({
  id,
  themeId: "sport",
  subthemeId: `sport:${sub}`,
  difficultyLevel: d,
  shortTitle: title,
  questionText: text,
  answers,
  sources: [source],
  qualificationRule:
    rule ?? "Les neuf réponses suivent exactement la période ou la catégorie précisée.",
  explanation: "Liste vérifiable dans les résultats et archives officiels cités.",
});
export const questions = [
  q([
    "easy-villes-jo-ete-1988-2020",
    "olympic-games",
    1,
    "Villes olympiques",
    "Quelles sont les neuf villes hôtes des Jeux olympiques d’été de 1988 à 2020 ?",
    [
      "Séoul",
      "Barcelone",
      "Atlanta",
      "Sydney",
      "Athènes",
      "Pékin",
      "Londres",
      "Rio de Janeiro",
      "Tokyo",
    ],
  ]),
  q([
    "easy-tournois-atp-masters1000",
    "tennis",
    1,
    "Masters 1000",
    "Quels sont les neuf tournois de la catégorie ATP Masters 1000 ?",
    [
      "Indian Wells",
      "Miami",
      "Monte-Carlo",
      "Madrid",
      "Rome",
      "Canada",
      "Cincinnati",
      "Shanghai",
      "Paris",
    ],
    ATP,
  ]),
  q([
    "easy-champions-rugby-1987-2019",
    "rugby",
    1,
    "Champions du monde de rugby",
    "Quelles équipes ont remporté les neuf éditions de la Coupe du monde masculine de rugby de 1987 à 2019 ?",
    [
      "Nouvelle-Zélande 1987",
      "Australie 1991",
      "Afrique du Sud 1995",
      "Australie 1999",
      "Angleterre 2003",
      "Afrique du Sud 2007",
      "Nouvelle-Zélande 2011",
      "Nouvelle-Zélande 2015",
      "Afrique du Sud 2019",
    ],
    WR,
  ]),
  q([
    "easy-equipes-nba-titres-2015-2024",
    "basketball",
    1,
    "Champions NBA récents",
    "Quelles équipes ont remporté les neuf titres NBA de 2015 à 2023 ?",
    [
      "Golden State Warriors 2015",
      "Cleveland Cavaliers 2016",
      "Golden State Warriors 2017",
      "Golden State Warriors 2018",
      "Toronto Raptors 2019",
      "Los Angeles Lakers 2020",
      "Milwaukee Bucks 2021",
      "Golden State Warriors 2022",
      "Denver Nuggets 2023",
    ],
    NBA,
  ]),
  q([
    "easy-champions-f1-2015-2023",
    "motorsport",
    1,
    "Champions de Formule 1",
    "Quels sont les neuf champions du monde de Formule 1 de 2015 à 2023, année par année ?",
    [
      "Lewis Hamilton 2015",
      "Nico Rosberg 2016",
      "Lewis Hamilton 2017",
      "Lewis Hamilton 2018",
      "Lewis Hamilton 2019",
      "Lewis Hamilton 2020",
      "Max Verstappen 2021",
      "Max Verstappen 2022",
      "Max Verstappen 2023",
    ],
    F1,
  ]),
  q([
    "easy-epreuves-decathlon",
    "athletics",
    1,
    "Décathlon",
    "Quelles sont neuf des dix épreuves du décathlon masculin, en excluant le 1 500 mètres ?",
    [
      "100 mètres",
      "Saut en longueur",
      "Lancer du poids",
      "Saut en hauteur",
      "400 mètres",
      "110 mètres haies",
      "Lancer du disque",
      "Saut à la perche",
      "Lancer du javelot",
    ],
    WA,
  ]),
  q([
    "medium-vainqueurs-wimbledon-2003-2011",
    "tennis",
    2,
    "Wimbledon masculin",
    "Quels sont les neuf vainqueurs du simple messieurs à Wimbledon de 2003 à 2011, année par année ?",
    [
      "Roger Federer 2003",
      "Roger Federer 2004",
      "Roger Federer 2005",
      "Roger Federer 2006",
      "Roger Federer 2007",
      "Rafael Nadal 2008",
      "Roger Federer 2009",
      "Rafael Nadal 2010",
      "Novak Djokovic 2011",
    ],
    ATP,
  ]),
  q([
    "medium-arbitres-finales-rugby-1987-2019",
    "rugby",
    2,
    "Arbitres des finales",
    "Quels sont les neuf arbitres des finales de Coupe du monde masculine de rugby de 1987 à 2019, année par année ?",
    [
      "Kerry Fitzgerald 1987",
      "Derek Bevan 1991",
      "Ed Morrison 1995",
      "André Watson 1999",
      "André Watson 2003",
      "Alain Rolland 2007",
      "Craig Joubert 2011",
      "Nigel Owens 2015",
      "Jérôme Garcès 2019",
    ],
    WR,
  ]),
  q([
    "medium-mvp-finales-nba-2015-2023",
    "basketball",
    2,
    "MVP des Finales NBA",
    "Quels sont les neuf MVP des Finales NBA de 2015 à 2023, année par année ?",
    [
      "Andre Iguodala 2015",
      "LeBron James 2016",
      "Kevin Durant 2017",
      "Kevin Durant 2018",
      "Kawhi Leonard 2019",
      "LeBron James 2020",
      "Giannis Antetokounmpo 2021",
      "Stephen Curry 2022",
      "Nikola Jokić 2023",
    ],
    NBA,
  ]),
  q([
    "medium-circuits-f1-2023-europe",
    "motorsport",
    2,
    "Circuits européens de F1",
    "Quels sont les neuf circuits européens inscrits au calendrier initial de Formule 1 en 2023 ?",
    [
      "Imola",
      "Monaco",
      "Barcelone-Catalogne",
      "Red Bull Ring",
      "Silverstone",
      "Hungaroring",
      "Spa-Francorchamps",
      "Zandvoort",
      "Monza",
    ],
    F1,
  ]),
  q([
    "medium-disciplines-heptathlon",
    "athletics",
    2,
    "Heptathlon et relais",
    "Quelles sont les sept épreuves de l’heptathlon féminin, complétées par les deux relais olympiques traditionnels ?",
    [
      "100 mètres haies",
      "Saut en hauteur",
      "Lancer du poids",
      "200 mètres",
      "Saut en longueur",
      "Lancer du javelot",
      "800 mètres",
      "Relais 4 × 100 mètres",
      "Relais 4 × 400 mètres",
    ],
    WA,
  ]),
  q([
    "medium-vainqueurs-tour-2012-2020",
    "cycling",
    2,
    "Vainqueurs du Tour",
    "Quels sont les neuf vainqueurs du Tour de France de 2012 à 2020, année par année ?",
    [
      "Bradley Wiggins 2012",
      "Chris Froome 2013",
      "Vincenzo Nibali 2014",
      "Chris Froome 2015",
      "Chris Froome 2016",
      "Chris Froome 2017",
      "Geraint Thomas 2018",
      "Egan Bernal 2019",
      "Tadej Pogačar 2020",
    ],
    TDF,
  ]),
  q([
    "hard-premieres-championnes-wimbledon",
    "tennis",
    3,
    "Pionnières de Wimbledon",
    "Qui sont les neuf premières championnes différentes du simple dames à Wimbledon ?",
    [
      "Maud Watson",
      "Blanche Bingley",
      "Lottie Dod",
      "Lena Rice",
      "Charlotte Cooper",
      "Muriel Robb",
      "Dorothea Douglass",
      "May Sutton",
      "Dora Boothby",
    ],
    WTA,
  ]),
  q([
    "hard-capitaines-champions-rugby",
    "rugby",
    3,
    "Capitaines champions du monde",
    "Quels sont les neuf capitaines vainqueurs des Coupes du monde masculines de rugby de 1987 à 2019 ?",
    [
      "David Kirk",
      "Nick Farr-Jones",
      "François Pienaar",
      "John Eales",
      "Martin Johnson",
      "John Smit",
      "Richie McCaw 2011",
      "Richie McCaw 2015",
      "Siya Kolisi",
    ],
    WR,
  ]),
  q([
    "hard-premiers-mvp-nba",
    "basketball",
    3,
    "Premiers MVP NBA",
    "Qui sont les neuf premiers lauréats différents du trophée de MVP de la saison NBA ?",
    [
      "Bob Pettit",
      "Bob Cousy",
      "Bill Russell",
      "Wilt Chamberlain",
      "Oscar Robertson",
      "Wes Unseld",
      "Willis Reed",
      "Kareem Abdul-Jabbar",
      "Dave Cowens",
    ],
    NBA,
  ]),
  q([
    "hard-champions-f1-1950-1958",
    "athletics",
    3,
    "Concours et épreuves combinées",
    "Quelles sont les huit disciplines de concours masculines en plein air, complétées par le décathlon ?",
    [
      "Saut en hauteur",
      "Saut à la perche",
      "Saut en longueur",
      "Triple saut",
      "Lancer du poids",
      "Lancer du disque",
      "Lancer du marteau",
      "Lancer du javelot",
      "Décathlon",
    ],
    WA,
    "Sont retenus les quatre sauts, les quatre lancers et l’épreuve combinée masculine du décathlon.",
  ]),
  q([
    "hard-neuf-premiers-vainqueurs-tour",
    "cycling",
    3,
    "Pionniers du Tour",
    "Qui sont les neuf premiers vainqueurs différents du Tour de France ?",
    [
      "Maurice Garin",
      "Henri Cornet",
      "Louis Trousselier",
      "René Pottier",
      "Lucien Petit-Breton",
      "François Faber",
      "Octave Lapize",
      "Gustave Garrigou",
      "Odile Defraye",
    ],
    TDF,
  ]),
];
