const source = (id, title, publisher, url) => ({ id, title, publisher, url, isPrimarySource: false });
const imdb = (id, title, url) => source(id, `${title} — épisodes`, "Internet Movie Database", url);
const q = (spec) => ({
  themeId: "television-series",
  qualificationRule: spec.qualificationRule ?? "Sont retenus les neuf épisodes précisément délimités dans la question, selon leur ordre de diffusion.",
  explanation: spec.explanation ?? "La liste d’épisodes citée confirme les neuf titres et leur ordre de diffusion.",
  ...spec,
});

export const questions = [
  q({ id: "easy-stranger-things-saison-2", subthemeId: "television-series:drama-series", difficultyLevel: 1, shortTitle: "Stranger Things 2", questionText: "Quels sont les neuf épisodes de la saison 2 de Stranger Things ?", answers: ["MADMAX", "Des bonbons ou un sort, espèce de taré", "Le Batracien", "Will le sage", "Dig Dug", "L’Espion", "La Sœur perdue", "Le Flagelleur mental", "Le Portail"], sources: [imdb("imdb-stranger-things-s2", "Stranger Things, saison 2", "https://www.imdb.com/title/tt4574334/episodes/?season=2")] }),
  q({ id: "easy-squid-game-saison-1", subthemeId: "television-series:drama-series", difficultyLevel: 1, shortTitle: "Squid Game", questionText: "Quels sont les neuf épisodes de la première saison de Squid Game ?", answers: ["Un, deux, trois, soleil", "Enfer", "L’Homme au parapluie", "L’Équipe avant tout", "Un monde juste", "Gganbu", "VIP", "Leader", "Jour de chance"], sources: [imdb("imdb-squid-game-s1", "Squid Game, saison 1", "https://www.imdb.com/title/tt10919420/episodes/?season=1")] }),
  q({ id: "easy-last-of-us-saison-1", subthemeId: "television-series:drama-series", difficultyLevel: 1, shortTitle: "The Last of Us", questionText: "Quels sont les neuf épisodes de la première saison de The Last of Us ?", answers: ["Quand tu es perdu dans les ténèbres", "Infectés", "Longtemps…", "S’il te plaît, tiens ma main", "Endurer et survivre", "Parenté", "Abandonnée", "Quand on est dans le besoin", "Cherchez la lumière"], sources: [imdb("imdb-last-of-us-s1", "The Last of Us, saison 1", "https://www.imdb.com/title/tt3581920/episodes/?season=1")] }),
  q({ id: "easy-wandavision-neuf-episodes", subthemeId: "television-series:drama-series", difficultyLevel: 1, shortTitle: "WandaVision", questionText: "Quels sont les neuf épisodes de la série WandaVision ?", answers: ["Filmée devant public", "Ne zappez pas", "On passe à la couleur", "Interruption du programme", "Dans cet épisode très spécial…", "Spécial Halloween", "Briser le quatrième mur", "Précédemment dans…", "Le Grand Final"], sources: [imdb("imdb-wandavision", "WandaVision", "https://www.imdb.com/title/tt9140560/episodes/")] }),
  q({ id: "easy-arcane-saison-1", subthemeId: "television-series:drama-series", difficultyLevel: 1, shortTitle: "Arcane", questionText: "Quels sont les neuf épisodes de la première saison d’Arcane ?", answers: ["Welcome to the Playground", "Some Mysteries Are Better Left Unsolved", "The Base Violence Necessary for Change", "Happy Progress Day!", "Everybody Wants to Be My Enemy", "When These Walls Come Tumbling Down", "The Boy Savior", "Oil and Water", "The Monster You Created"], sources: [imdb("imdb-arcane-s1", "Arcane, saison 1", "https://www.imdb.com/title/tt11126994/episodes/?season=1")] }),
  q({ id: "easy-friends-neuf-premiers", subthemeId: "television-series:comedy-series", difficultyLevel: 1, shortTitle: "Débuts de Friends", questionText: "Quels sont les neuf premiers épisodes de Friends ?", answers: ["Celui qui déménage", "Celui qui est perdu", "Celui qui a un rôle", "Celui avec George", "Celui qui lave plus blanc", "Celui qui est verni", "Celui qui a du jus", "Celui qui était hystérique", "Celui qui parle au ventre de sa femme"], sources: [imdb("imdb-friends-s1", "Friends, saison 1", "https://www.imdb.com/title/tt0108778/episodes/?season=1")] }),
  q({ id: "easy-mandalorian-neuf-premiers", subthemeId: "television-series:characters", difficultyLevel: 1, shortTitle: "The Mandalorian", questionText: "Quels sont les neuf premiers chapitres de The Mandalorian ?", answers: ["Le Mandalorien", "L’Enfant", "Le Péché", "Le Sanctuaire", "Le Mercenaire", "Le Prisonnier", "La Confrontation", "Rédemption", "Le Marshal"], sources: [imdb("imdb-mandalorian", "The Mandalorian", "https://www.imdb.com/title/tt8111088/episodes/")] }),

  q({ id: "medium-doctor-who-neuf-docteurs", subthemeId: "television-series:characters", difficultyLevel: 2, shortTitle: "Les neuf Docteurs", questionText: "Quels acteurs ont incarné les neuf premières incarnations principales du Docteur dans Doctor Who ?", answers: ["William Hartnell", "Patrick Troughton", "Jon Pertwee", "Tom Baker", "Peter Davison", "Colin Baker", "Sylvester McCoy", "Paul McGann", "Christopher Eccleston"], sources: [source("bbc-doctor-who-doctors", "The Doctors", "BBC", "https://www.bbc.co.uk/doctorwho/classic/episodeguide/index.shtml")] }),
  q({ id: "medium-sherlock-neuf-episodes", subthemeId: "television-series:drama-series", difficultyLevel: 2, shortTitle: "Sherlock", questionText: "Quels sont les neuf épisodes des trois premières saisons de Sherlock ?", answers: ["Une étude en rose", "Le Banquier aveugle", "Le Grand Jeu", "Un scandale à Buckingham", "Les Chiens de Baskerville", "La Chute du Reichenbach", "Le Cercueil vide", "Le Signe des trois", "Son dernier coup d’éclat"], sources: [imdb("imdb-sherlock", "Sherlock", "https://www.imdb.com/title/tt1475582/episodes/")] }),
  q({ id: "medium-black-mirror-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 2, shortTitle: "Black Mirror", questionText: "Quels sont les neuf premiers épisodes de Black Mirror, de L’Hymne national à Phase d’essai ?", answers: ["L’Hymne national", "15 millions de mérites", "Retour sur image", "Bientôt de retour", "La Chasse", "Le Show de Waldo", "Blanc comme neige", "La Chute libre", "Phase d’essai"], sources: [imdb("imdb-black-mirror", "Black Mirror", "https://www.imdb.com/title/tt2085059/episodes/")], qualificationRule: "Sont retenus les neuf premiers épisodes selon l’ordre général de diffusion, spécial Blanc comme neige inclus." }),
  q({ id: "medium-ted-lasso-neuf-premiers", subthemeId: "television-series:comedy-series", difficultyLevel: 2, shortTitle: "Ted Lasso", questionText: "Quels sont les neuf premiers épisodes de Ted Lasso ?", answers: ["Pilot", "Biscuits", "Trent Crimm: The Independent", "For the Children", "Tan Lines", "Two Aces", "Make Rebecca Great Again", "The Diamond Dogs", "All Apologies"], sources: [imdb("imdb-ted-lasso", "Ted Lasso", "https://www.imdb.com/title/tt10986410/episodes/?season=1")] }),
  q({ id: "medium-peaky-blinders-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 2, shortTitle: "Peaky Blinders", questionText: "Quels sont les neuf premiers épisodes de Peaky Blinders ?", answers: ["Épisode 1", "Épisode 2", "Épisode 3", "Épisode 4", "Épisode 5", "Épisode 6", "Épisode 1 — saison 2", "Épisode 2 — saison 2", "Épisode 3 — saison 2"], sources: [imdb("imdb-peaky-blinders", "Peaky Blinders", "https://www.imdb.com/title/tt2442560/episodes/")] }),
  q({ id: "medium-crown-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 2, shortTitle: "The Crown", questionText: "Quels sont les neuf premiers épisodes de The Crown ?", answers: ["Wolferton Splash", "Hyde Park Corner", "Windsor", "Catastrophe naturelle", "Poudre aux yeux", "Bombe à retardement", "Le Savoir, c’est le pouvoir", "Joie et Fierté", "Assassins"], sources: [imdb("imdb-crown", "The Crown", "https://www.imdb.com/title/tt4786824/episodes/?season=1")] }),
  q({ id: "medium-x-files-neuf-premiers", subthemeId: "television-series:characters", difficultyLevel: 2, shortTitle: "Aux frontières du réel", questionText: "Quels sont les neuf premiers épisodes de X-Files : Aux frontières du réel ?", answers: ["Nous ne sommes pas seuls", "Gorge profonde", "Compressions", "L’Enlèvement", "Le Diable du New Jersey", "L’Ombre de la mort", "Un fantôme dans l’ordinateur", "Projet Arctique", "Espace"], sources: [imdb("imdb-xfiles", "The X-Files", "https://www.imdb.com/title/tt0106179/episodes/?season=1")] }),

  q({ id: "hard-twin-peaks-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Twin Peaks", questionText: "Quels sont les neuf premiers épisodes de Twin Peaks, pilote compris ?", answers: ["Pilote", "Traces vers nulle part", "Zen, ou l’Art d’attraper un tueur", "Repos en douleur", "L’Homme à un bras", "Les Rêves de Cooper", "Le Temps de le réaliser", "La Dernière Soirée", "Que le géant soit avec vous"], sources: [imdb("imdb-twin-peaks", "Twin Peaks", "https://www.imdb.com/title/tt0098936/episodes/")] }),
  q({ id: "hard-sopranos-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Les Soprano", questionText: "Quels sont les neuf premiers épisodes des Soprano ?", answers: ["Égarement", "Le Clan Soprano", "À bout de souffle", "La Nouvelle Ère", "Suspicion", "Pax Soprana", "Pris à la gorge", "La Légende de Tennessee Moltisanti", "Révélations intimes"], sources: [imdb("imdb-sopranos", "The Sopranos", "https://www.imdb.com/title/tt0141842/episodes/?season=1")] }),
  q({ id: "hard-the-wire-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Sur écoute", questionText: "Quels sont les neuf premiers épisodes de Sur écoute ?", answers: ["La Cible", "Le Détail", "La Poudre aux yeux", "Affaires anciennes", "La Balance", "Le Lien", "Une arrestation", "La Leçon", "Quitte ou double"], sources: [imdb("imdb-wire", "The Wire", "https://www.imdb.com/title/tt0306414/episodes/?season=1")] }),
  q({ id: "hard-mad-men-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Mad Men", questionText: "Quels sont les neuf premiers épisodes de Mad Men ?", answers: ["Smoke Gets in Your Eyes", "Ce que veulent les femmes", "Le Mariage de Figaro", "La Ville nous appartient", "Secret de famille", "Babylone", "Sous influence", "Langage codé", "Changement de décor"], sources: [imdb("imdb-mad-men", "Mad Men", "https://www.imdb.com/title/tt0804503/episodes/?season=1")] }),
  q({ id: "hard-succession-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Succession", questionText: "Quels sont les neuf premiers épisodes de Succession ?", answers: ["La Célébration", "Le Merdeux dans l’usine", "À vous de jouer", "Triste anniversaire", "Je suis allé au marché", "De quel côté êtes-vous ?", "Austerlitz", "Prague", "Prénuptial"], sources: [imdb("imdb-succession", "Succession", "https://www.imdb.com/title/tt7660850/episodes/?season=1")] }),
  q({ id: "hard-six-feet-under-neuf-premiers", subthemeId: "television-series:drama-series", difficultyLevel: 3, shortTitle: "Six Feet Under", questionText: "Quels sont les neuf premiers épisodes de Six Feet Under ?", answers: ["La Mort", "Le Testament", "Le Pied", "La Famille", "À livre ouvert", "La Chambre", "Fraternité", "Départs et retrouvailles", "La Vie est trop courte"], sources: [imdb("imdb-six-feet-under", "Six Feet Under", "https://www.imdb.com/title/tt0248654/episodes/?season=1")] }),
];
