const source = (id, title, publisher, url, isPrimarySource = true) => ({
  id,
  title,
  publisher,
  url,
  isPrimarySource,
});
const POKEMON = source(
  "pokemon-pokedex-pack",
  "Pokédex",
  "The Pokémon Company",
  "https://www.pokemon.com/fr/pokedex",
  true,
);
const NINTENDO_MARIO = source(
  "nintendo-mario-kart-pack",
  "Mario Kart Portal",
  "Nintendo",
  "https://mariokart8.nintendo.com/history/",
  true,
);
const NINTENDO_ZELDA = source(
  "nintendo-zelda-history-pack",
  "The Legend of Zelda — History",
  "Nintendo",
  "https://zelda.nintendo.com/about/",
  true,
);
const UBISOFT_AC = source(
  "ubisoft-assassins-creed-pack",
  "Assassin’s Creed games",
  "Ubisoft",
  "https://www.ubisoft.com/en-us/game/assassins-creed/all-games",
  true,
);
const CAPCOM_RE = source(
  "capcom-resident-evil-pack",
  "Resident Evil Portal",
  "Capcom",
  "https://game.capcom.com/residentevil/en/",
  true,
);
const ROCKSTAR = source(
  "rockstar-games-pack",
  "Games",
  "Rockstar Games",
  "https://www.rockstargames.com/games",
  true,
);
const SEGA_SONIC = source(
  "sega-sonic-history-pack",
  "Sonic games",
  "Sega",
  "https://www.sonicthehedgehog.com/",
  true,
);
const SQUARE_FF = source(
  "square-final-fantasy-pack",
  "Final Fantasy Portal",
  "Square Enix",
  "https://na.finalfantasy.com/titles",
  true,
);
const SQUARE_DQ = source(
  "square-dragon-quest-pack",
  "Dragon Quest Portal",
  "Square Enix",
  "https://dragonquest.square-enix-games.com/",
  true,
);
const ACTIVISION = source(
  "activision-call-duty-pack",
  "Call of Duty games",
  "Activision",
  "https://www.callofduty.com/games",
  true,
);
const EA_NFS = source(
  "ea-need-speed-pack",
  "Need for Speed games",
  "Electronic Arts",
  "https://www.ea.com/games/need-for-speed",
  true,
);
const CRYSTAL = source(
  "tombraider-games-pack",
  "Tomb Raider games",
  "Crystal Dynamics",
  "https://www.tombraider.com/games",
  true,
);
const KONAMI_MG = source(
  "konami-metal-gear-pack",
  "Metal Gear Portal",
  "Konami",
  "https://www.konami.com/mg/history/",
  true,
);
const VALVE = source(
  "valve-tf2-classes-pack",
  "Team Fortress 2 — Classes",
  "Valve",
  "https://www.teamfortress.com/classes.php",
  true,
);
const KOEI = source(
  "koei-atelier-pack",
  "Atelier Series Portal",
  "Koei Tecmo",
  "https://www.koeitecmoeurope.com/atelier/",
  true,
);
const FALCOM = source(
  "falcom-ys-pack",
  "Ys series",
  "Nihon Falcom",
  "https://www.falcom.co.jp/ys/",
  true,
);
const CAPCOM_MM = source(
  "capcom-megaman-pack",
  "Mega Man Portal",
  "Capcom",
  "https://megaman.capcom.com/",
  true,
);
const NINTENDO_FE = source(
  "nintendo-fire-emblem-pack",
  "Fire Emblem World",
  "Nintendo",
  "https://fire-emblem-heroes.com/en/",
  true,
);
const KONAMI_CASTLE = source(
  "konami-castlevania-pack",
  "Castlevania Portal",
  "Konami",
  "https://www.konami.com/games/castlevania/",
  true,
);

const q = (spec) => ({
  themeId: "video-games",
  qualificationRule:
    spec.qualificationRule ??
    "Sont retenus les neuf jeux ou personnages correspondant exactement à la borne annoncée.",
  explanation:
    spec.explanation ?? "La liste suit l’ordre de sortie ou l’ordre officiel de la franchise.",
  ...spec,
});

export const questions = [
  q({
    id: "easy-starters-pokemon",
    subthemeId: "video-games:characters",
    difficultyLevel: 1,
    shortTitle: "Départs Pokémon",
    questionText: "Quels sont les neuf Pokémon de départ des trois premières générations ?",
    answers: [
      { display: "Bulbizarre", aliases: ["Bulbasaur"] },
      { display: "Salamèche", aliases: ["Charmander"] },
      { display: "Carapuce", aliases: ["Squirtle"] },
      { display: "Germignon", aliases: ["Chikorita"] },
      { display: "Héricendre", aliases: ["Cyndaquil"] },
      { display: "Kaiminus", aliases: ["Totodile"] },
      { display: "Arcko", aliases: ["Treecko"] },
      { display: "Poussifeu", aliases: ["Torchic"] },
      { display: "Gobou", aliases: ["Mudkip"] },
    ],
    sources: [POKEMON],
  }),
  q({
    id: "easy-neuf-premiers-mario-kart",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Mario Kart",
    questionText:
      "Quels sont les neuf premiers jeux principaux de Mario Kart, de Super Mario Kart à Mario Kart 8 ?",
    answers: [
      "Super Mario Kart",
      "Mario Kart 64",
      "Mario Kart: Super Circuit",
      "Mario Kart: Double Dash!!",
      "Mario Kart DS",
      "Mario Kart Wii",
      "Mario Kart 7",
      "Mario Kart 8",
      "Mario Kart 8 Deluxe",
    ],
    sources: [NINTENDO_MARIO],
    exclusionNotes: "Les jeux d’arcade et mobiles ne sont pas inclus.",
  }),
  q({
    id: "easy-neuf-premiers-zelda",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Premiers Zelda",
    questionText:
      "Quels sont les neuf premiers jeux principaux de The Legend of Zelda, du jeu original à Majora’s Mask ?",
    answers: [
      "The Legend of Zelda",
      "Zelda II: The Adventure of Link",
      "A Link to the Past",
      "Link’s Awakening",
      "Ocarina of Time",
      "Majora’s Mask",
      "Oracle of Seasons",
      "Oracle of Ages",
      "Four Swords",
    ],
    sources: [NINTENDO_ZELDA],
    exclusionNotes: "La sélection suit la chronologie officielle et s’arrête à Four Swords.",
  }),
  q({
    id: "easy-neuf-assassins-creed",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Assassin’s Creed",
    questionText:
      "Quels sont les neuf premiers jeux principaux d’Assassin’s Creed, du premier épisode à Syndicate ?",
    answers: [
      "Assassin’s Creed",
      "Assassin’s Creed II",
      "Assassin’s Creed: Brotherhood",
      "Assassin’s Creed: Revelations",
      "Assassin’s Creed III",
      "Assassin’s Creed IV: Black Flag",
      "Assassin’s Creed Rogue",
      "Assassin’s Creed Unity",
      "Assassin’s Creed Syndicate",
    ],
    sources: [UBISOFT_AC],
  }),
  q({
    id: "easy-resident-evil-0-a-8",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Resident Evil numérotés",
    questionText: "Quels sont les neuf Resident Evil principaux portant les numéros 0 à 8 ?",
    answers: [
      "Resident Evil 0",
      "Resident Evil",
      "Resident Evil 2",
      "Resident Evil 3",
      "Resident Evil 4",
      "Resident Evil 5",
      "Resident Evil 6",
      "Resident Evil 7",
      "Resident Evil Village",
    ],
    sources: [CAPCOM_RE],
    qualificationRule:
      "Sont retenus Resident Evil 0, le premier jeu non numéroté, puis les épisodes 2 à 8, Village correspondant à Resident Evil 8.",
  }),
  q({
    id: "easy-neuf-premiers-gta",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Premiers GTA",
    questionText:
      "Quels sont les neuf premiers jeux Grand Theft Auto sortis, du jeu original à Liberty City Stories ?",
    answers: [
      "Grand Theft Auto",
      "GTA: London 1969",
      "GTA: London 1961",
      "Grand Theft Auto 2",
      "Grand Theft Auto III",
      "Grand Theft Auto: Vice City",
      "Grand Theft Auto: San Andreas",
      "Grand Theft Auto Advance",
      "Grand Theft Auto: Liberty City Stories",
    ],
    sources: [ROCKSTAR],
  }),
  q({
    id: "easy-neuf-sonic-classiques",
    subthemeId: "video-games:franchises",
    difficultyLevel: 1,
    shortTitle: "Sonic historique",
    questionText:
      "Quels sont ces neuf jeux de plates-formes Sonic sortis du premier Sonic à Sonic Heroes ?",
    answers: [
      "Sonic the Hedgehog",
      "Sonic the Hedgehog 2",
      "Sonic CD",
      "Sonic the Hedgehog 3",
      "Sonic & Knuckles",
      "Sonic 3D Blast",
      "Sonic Adventure",
      "Sonic Adventure 2",
      "Sonic Heroes",
    ],
    sources: [SEGA_SONIC],
    qualificationRule:
      "Sont retenus les neuf titres de plates-formes explicitement bornés, hors jeux de course et compilations.",
  }),

  q({
    id: "medium-famille-evoli",
    subthemeId: "video-games:characters",
    difficultyLevel: 2,
    shortTitle: "Famille d’Évoli",
    questionText: "Quels sont les neuf membres de la famille d’Évoli, en comptant Évoli lui-même ?",
    answers: [
      { display: "Évoli", aliases: ["Eevee"] },
      { display: "Aquali", aliases: ["Vaporeon"] },
      { display: "Voltali", aliases: ["Jolteon"] },
      { display: "Pyroli", aliases: ["Flareon"] },
      { display: "Mentali", aliases: ["Espeon"] },
      { display: "Noctali", aliases: ["Umbreon"] },
      { display: "Phyllali", aliases: ["Leafeon"] },
      { display: "Givrali", aliases: ["Glaceon"] },
      { display: "Nymphali", aliases: ["Sylveon"] },
    ],
    sources: [POKEMON],
  }),
  q({
    id: "medium-final-fantasy-1-a-9",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Final Fantasy I à IX",
    questionText: "Quels sont les neuf premiers Final Fantasy numérotés ?",
    answers: [
      "Final Fantasy",
      "Final Fantasy II",
      "Final Fantasy III",
      "Final Fantasy IV",
      "Final Fantasy V",
      "Final Fantasy VI",
      "Final Fantasy VII",
      "Final Fantasy VIII",
      "Final Fantasy IX",
    ],
    sources: [SQUARE_FF],
  }),
  q({
    id: "medium-dragon-quest-1-a-9",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Dragon Quest I à IX",
    questionText: "Quels sont les neuf premiers Dragon Quest numérotés ?",
    answers: [
      "Dragon Quest",
      "Dragon Quest II",
      "Dragon Quest III",
      "Dragon Quest IV",
      "Dragon Quest V",
      "Dragon Quest VI",
      "Dragon Quest VII",
      "Dragon Quest VIII",
      "Dragon Quest IX",
    ],
    sources: [SQUARE_DQ],
  }),
  q({
    id: "medium-neuf-premiers-call-of-duty",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Call of Duty historique",
    questionText:
      "Quels sont les neuf premiers jeux principaux Call of Duty, du premier à Black Ops II ?",
    answers: [
      "Call of Duty",
      "Call of Duty 2",
      "Call of Duty 3",
      "Call of Duty 4: Modern Warfare",
      "Call of Duty: World at War",
      "Call of Duty: Modern Warfare 2",
      "Call of Duty: Black Ops",
      "Call of Duty: Modern Warfare 3",
      "Call of Duty: Black Ops II",
    ],
    sources: [ACTIVISION],
  }),
  q({
    id: "medium-neuf-premiers-need-for-speed",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Need for Speed historique",
    questionText:
      "Quels sont les neuf premiers Need for Speed principaux, du jeu original à Underground 2 ?",
    answers: [
      "The Need for Speed",
      "Need for Speed II",
      "Need for Speed III: Hot Pursuit",
      "Need for Speed: High Stakes",
      "Need for Speed: Porsche Unleashed",
      "Motor City Online",
      "Need for Speed: Hot Pursuit 2",
      "Need for Speed: Underground",
      "Need for Speed: Underground 2",
    ],
    sources: [EA_NFS],
    qualificationRule:
      "Sont retenus les neuf jeux de course de la chronologie EA jusqu’à Underground 2, Motor City Online inclus.",
  }),
  q({
    id: "medium-neuf-premiers-tomb-raider",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Tomb Raider historique",
    questionText:
      "Quels sont les neuf premiers jeux principaux Tomb Raider, du jeu original à Underworld ?",
    answers: [
      "Tomb Raider",
      "Tomb Raider II",
      "Tomb Raider III",
      "The Last Revelation",
      "Chronicles",
      "The Angel of Darkness",
      "Legend",
      "Anniversary",
      "Underworld",
    ],
    sources: [CRYSTAL],
  }),
  q({
    id: "medium-neuf-premiers-metal-gear",
    subthemeId: "video-games:franchises",
    difficultyLevel: 2,
    shortTitle: "Metal Gear historique",
    questionText:
      "Quels sont ces neuf jeux principaux de Metal Gear, du premier Metal Gear à The Phantom Pain ?",
    answers: [
      "Metal Gear",
      "Metal Gear 2: Solid Snake",
      "Metal Gear Solid",
      "Metal Gear Solid 2: Sons of Liberty",
      "Metal Gear Solid 3: Snake Eater",
      "Metal Gear Solid 4: Guns of the Patriots",
      "Metal Gear Solid: Peace Walker",
      "Metal Gear Solid V: Ground Zeroes",
      "Metal Gear Solid V: The Phantom Pain",
    ],
    sources: [KONAMI_MG],
  }),

  q({
    id: "hard-classes-team-fortress-2",
    subthemeId: "video-games:characters",
    difficultyLevel: 3,
    shortTitle: "Classes de TF2",
    questionText: "Quelles sont les neuf classes jouables de Team Fortress 2 ?",
    answers: ["Scout", "Soldier", "Pyro", "Demoman", "Heavy", "Engineer", "Medic", "Sniper", "Spy"],
    sources: [VALVE],
  }),
  q({
    id: "hard-neuf-premiers-atelier",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Atelier historique",
    questionText:
      "Quels sont les neuf premiers jeux principaux de la série Atelier, de Marie à Viorate ?",
    answers: [
      "Atelier Marie",
      "Atelier Elie",
      "Atelier Lilie",
      "Atelier Judie",
      "Atelier Viorate",
      "Atelier Iris",
      "Atelier Iris 2",
      "Atelier Iris 3",
      "Mana Khemia",
    ],
    sources: [KOEI],
    qualificationRule:
      "Sont retenus les neuf premiers titres principaux de la chronologie japonaise jusqu’à Mana Khemia.",
  }),
  q({
    id: "hard-ys-1-a-9",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Ys I à IX",
    questionText: "Quels sont les neuf jeux numérotés Ys, de Ys I à Ys IX ?",
    answers: ["Ys I", "Ys II", "Ys III", "Ys IV", "Ys V", "Ys VI", "Ys Seven", "Ys VIII", "Ys IX"],
    sources: [FALCOM],
  }),
  q({
    id: "hard-neuf-mega-man-x",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Mega Man X",
    questionText:
      "Quels sont les neuf jeux Mega Man X constitués des épisodes X à X8 et de Command Mission ?",
    answers: [
      "Mega Man X",
      "Mega Man X2",
      "Mega Man X3",
      "Mega Man X4",
      "Mega Man X5",
      "Mega Man X6",
      "Mega Man X7",
      "Mega Man X8",
      "Mega Man X: Command Mission",
    ],
    sources: [CAPCOM_MM],
  }),
  q({
    id: "hard-neuf-premiers-fire-emblem",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Fire Emblem historique",
    questionText:
      "Quels sont les neuf premiers Fire Emblem principaux, du premier épisode à The Sacred Stones ?",
    answers: [
      "Shadow Dragon and the Blade of Light",
      "Gaiden",
      "Mystery of the Emblem",
      "Genealogy of the Holy War",
      "Thracia 776",
      "The Binding Blade",
      "The Blazing Blade",
      "The Sacred Stones",
      "Path of Radiance",
    ],
    sources: [NINTENDO_FE],
    qualificationRule:
      "Sont retenus les neuf premiers titres principaux par ordre de sortie, jusqu’à Path of Radiance.",
  }),
  q({
    id: "hard-neuf-premiers-castlevania",
    subthemeId: "video-games:franchises",
    difficultyLevel: 3,
    shortTitle: "Castlevania historique",
    questionText:
      "Quels sont ces neuf premiers jeux Castlevania sortis au Japon ou en Occident, du jeu original à Belmont’s Revenge ?",
    answers: [
      "Castlevania",
      "Vampire Killer",
      "Castlevania II: Simon’s Quest",
      "Haunted Castle",
      "Castlevania: The Adventure",
      "Castlevania III: Dracula’s Curse",
      "Kid Dracula",
      "Super Castlevania IV",
      "Castlevania II: Belmont’s Revenge",
    ],
    sources: [KONAMI_CASTLE],
  }),
];
