const source = (id, title, publisher, url, isPrimarySource = true) => ({ id, title, publisher, url, isPrimarySource });
const UNESCO = source("unesco-intangible-lists-pack", "Intangible Cultural Heritage Lists", "UNESCO", "https://ich.unesco.org/en/lists", true);
const UN = source("un-member-states-pack", "Member States", "United Nations", "https://www.un.org/en/about-us/member-states", true);
const CLDR = source("unicode-cldr-charts", "Unicode CLDR charts", "Unicode Consortium", "https://www.unicode.org/cldr/charts/latest/", true);
const BRITANNICA = source("britannica-world-culture-pack", "Culture", "Encyclopaedia Britannica", "https://www.britannica.com/topic/culture");
const EU = source("eu-official-languages", "Languages of the European Union", "European Union", "https://european-union.europa.eu/principles-countries-history/languages_en", true);
const q = (spec) => ({ themeId:"world-culture", qualificationRule:spec.qualificationRule ?? "Les neuf réponses correspondent au périmètre culturel explicitement indiqué.", explanation:spec.explanation ?? "La liste est vérifiée dans la source culturelle ou institutionnelle citée.", ...spec });

export const questions = [
  q({ id:"easy-rennes-noel", subthemeId:"world-culture:celebrations", difficultyLevel:1, shortTitle:"Rennes du Père Noël", questionText:"Quels sont les neuf rennes du Père Noël en comptant Rudolph ?", answers:["Tornade","Danseur","Furie","Fringant","Comète","Cupidon","Tonnerre","Éclair","Rudolph"], sources:[BRITANNICA], qualificationRule:"Les noms français usuels des huit rennes du poème de 1823 et Rudolph sont acceptés." }),
  q({ id:"easy-fetes-neuf-pays", subthemeId:"world-culture:celebrations", difficultyLevel:1, shortTitle:"Fêtes et pays", questionText:"À quels neuf pays associe-t-on respectivement le Día de Muertos, Thanksgiving, Hanami, Holi, Songkran, Oktoberfest, Inti Raymi, Sainte-Lucie et Waitangi Day ?", answers:["Mexique","États-Unis","Japon","Inde","Thaïlande","Allemagne","Pérou","Suède","Nouvelle-Zélande"], sources:[UNESCO], qualificationRule:"Une réponse est le pays associé à chaque fête dans l’ordre de la question." }),
  q({ id:"easy-salutations-neuf-langues", subthemeId:"world-culture:languages", difficultyLevel:1, shortTitle:"Bonjour en neuf langues", questionText:"Comment dit-on « bonjour » dans ces neuf langues : anglais, espagnol, italien, allemand, portugais, japonais, arabe, hindi et swahili ?", answers:["Hello","Hola","Buongiorno","Guten Tag","Olá","Konnichiwa","Marhaban","Namaste","Jambo"], sources:[CLDR], qualificationRule:"Une salutation standard par langue est attendue, dans l’ordre de la question." }),
  q({ id:"easy-monnaies-neuf-pays", subthemeId:"world-culture:symbols", difficultyLevel:1, shortTitle:"Monnaies du monde", questionText:"Quelles monnaies utilisent respectivement les États-Unis, le Japon, le Royaume-Uni, la Suisse, l’Inde, la Chine, le Mexique, le Brésil et l’Afrique du Sud ?", answers:["Dollar américain","Yen","Livre sterling","Franc suisse","Roupie indienne","Yuan renminbi","Peso mexicain","Réal brésilien","Rand"], sources:[UN], qualificationRule:"Une monnaie est attendue pour chaque pays, dans l’ordre indiqué." }),
  q({ id:"easy-symboles-neuf-pays", subthemeId:"world-culture:symbols", difficultyLevel:1, shortTitle:"Symboles nationaux", questionText:"À quels pays associe-t-on l’érable, le coq gaulois, le kiwi, le trèfle, le cèdre, le chrysanthème impérial, l’aigle à tête blanche, le kangourou et le quetzal ?", answers:["Canada","France","Nouvelle-Zélande","Irlande","Liban","Japon","États-Unis","Australie","Guatemala"], sources:[BRITANNICA], qualificationRule:"Une réponse est le pays symbolisé par chaque élément, dans l’ordre." }),
  q({ id:"easy-danses-neuf-pays", subthemeId:"world-culture:traditions", difficultyLevel:1, shortTitle:"Danses et origines", questionText:"De quels pays viennent principalement le tango, le flamenco, la samba, le haka, le bhangra, le dabké, le hula, la polka et le sirtaki ?", answers:["Argentine","Espagne","Brésil","Nouvelle-Zélande","Inde","Liban","États-Unis","Tchéquie","Grèce"], sources:[UNESCO], qualificationRule:"Le pays d’origine ou d’ancrage culturel principal de chaque danse est attendu, dans l’ordre." }),
  q({ id:"easy-nouvel-an-neuf-calendriers", subthemeId:"world-culture:celebrations", difficultyLevel:1, shortTitle:"Nouveaux Ans du monde", questionText:"Quels sont ces neuf noms de fêtes marquant une nouvelle année dans différentes cultures ?", answers:["Nouvel An grégorien","Nouvel An chinois","Rosh Hashanah","Nowruz","Songkran","Têt","Losar","Enkutatash","Matariki"], sources:[UNESCO], qualificationRule:"Sont attendues les neuf fêtes du Nouvel An explicitement sélectionnées." }),

  q({ id:"medium-neuf-langues-ue-alphabetique", subthemeId:"world-culture:languages", difficultyLevel:2, shortTitle:"Langues de l’Union européenne", questionText:"Quelles sont les neuf premières langues officielles de l’Union européenne par ordre alphabétique français ?", answers:["Allemand","Anglais","Bulgare","Croate","Danois","Espagnol","Estonien","Finnois","Français"], sources:[EU] }),
  q({ id:"medium-neuf-sites-merveilles-selection", subthemeId:"world-culture:heritage", difficultyLevel:2, shortTitle:"Patrimoines emblématiques", questionText:"Dans quels pays se trouvent Angkor, Pétra, Machu Picchu, le Taj Mahal, Chichén Itzá, Borobudur, Lalibela, l’Alhambra et la Grande Muraille ?", answers:["Cambodge","Jordanie","Pérou","Inde","Mexique","Indonésie","Éthiopie","Espagne","Chine"], sources:[UNESCO], qualificationRule:"Un pays est attendu pour chaque site, dans l’ordre de la question." }),
  q({ id:"medium-neuf-ecritures", subthemeId:"world-culture:languages", difficultyLevel:2, shortTitle:"Systèmes d’écriture", questionText:"Quels systèmes d’écriture servent principalement à noter le russe, le grec, l’hindi, l’hébreu, l’arabe, l’amharique, le coréen, le japonais et le pendjabi ?", answers:["Cyrillique","Alphabet grec","Devanagari","Alphabet hébreu","Alphabet arabe","Guèze","Hangeul","Kanji et kana","Gourmoukhi"], sources:[CLDR], qualificationRule:"Le système d’écriture principal de chaque langue est attendu, dans l’ordre." }),
  q({ id:"medium-neuf-elements-patrimoine-immateriel", subthemeId:"world-culture:heritage", difficultyLevel:2, shortTitle:"Patrimoine immatériel", questionText:"À quels pays l’UNESCO associe-t-elle principalement le washoku, le yoga, le fado, le flamenco, la capoeira, le tango, la calligraphie chinoise, le café turc et la rumba cubaine ?", answers:["Japon","Inde","Portugal","Espagne","Brésil","Argentine et Uruguay","Chine","Turquie","Cuba"], sources:[UNESCO], qualificationRule:"Le ou les États porteurs indiqués par l’UNESCO sont attendus dans l’ordre." }),
  q({ id:"medium-neuf-couleurs-drapeaux", subthemeId:"world-culture:symbols", difficultyLevel:2, shortTitle:"Drapeaux monochromes repères", questionText:"Quelles couleurs dominantes ou distinctives associe-t-on à ces neuf drapeaux : Japon, Libye avant 2011, Bangladesh, Ukraine, Nigeria, Indonésie, Finlande, Albanie et Kazakhstan ?", answers:["Blanc et rouge","Vert","Vert et rouge","Bleu et jaune","Vert et blanc","Rouge et blanc","Bleu et blanc","Rouge et noir","Bleu ciel et or"], sources:[UN], qualificationRule:"La combinaison chromatique distinctive de chaque drapeau est attendue, dans l’ordre." }),
  q({ id:"medium-neuf-pays-carnavals", subthemeId:"world-culture:celebrations", difficultyLevel:2, shortTitle:"Carnavals du monde", questionText:"Dans quels pays se tiennent les carnavals de Rio, Venise, Notting Hill, Binche, Oruro, Barranquilla, Québec, Goa et Bâle ?", answers:["Brésil","Italie","Royaume-Uni","Belgique","Bolivie","Colombie","Canada","Inde","Suisse"], sources:[UNESCO], qualificationRule:"Un pays est attendu pour chaque carnaval, dans l’ordre." }),
  q({ id:"medium-neuf-instruments-traditionnels", subthemeId:"world-culture:traditions", difficultyLevel:2, shortTitle:"Instruments traditionnels", questionText:"À quelles cultures ou régions associe-t-on le sitar, le shamisen, la kora, le didgeridoo, la cornemuse, le gamelan, le charango, l’oud et le balafon ?", answers:["Inde","Japon","Afrique de l’Ouest","Australie aborigène","Écosse","Indonésie","Andes","Monde arabe","Afrique de l’Ouest mandingue"], sources:[UNESCO], qualificationRule:"La région ou culture d’ancrage principale de chaque instrument est attendue." }),

  q({ id:"hard-neuf-danses-unesco-pays", subthemeId:"world-culture:heritage", difficultyLevel:3, shortTitle:"Danses inscrites à l’UNESCO", questionText:"À quels pays l’UNESCO associe-t-elle le zaouli, le merengue, le maloya, le kathakali, le khöömei, le gwoka, le tango, le wititi et le kalbelia ?", answers:["Zaouli — Côte d’Ivoire","Merengue — République dominicaine","Maloya — France","Kathakali — Inde","Khöömei — Mongolie","Gwoka — France","Tango — Argentine et Uruguay","Wititi — Pérou","Kalbelia — Inde"], sources:[UNESCO], qualificationRule:"Le pays, seul ou associé au nom de la danse, est attendu pour chaque élément." }),
  q({ id:"hard-neuf-alphabets-noms-autochtones", subthemeId:"world-culture:languages", difficultyLevel:3, shortTitle:"Noms d’écritures", questionText:"Quels sont les noms des écritures utilisées pour le géorgien, l’arménien, le thaï, le lao, le khmer, le birman, le tibétain, le cingalais et le maldivien ?", answers:["Mkhedruli","Alphabet arménien","Alphabet thaï","Alphabet lao","Alphabet khmer","Écriture birmane","Écriture tibétaine","Alphabet cingalais","Thaana"], sources:[CLDR] }),
  q({ id:"hard-neuf-sites-unesco-numero-ordre", subthemeId:"world-culture:heritage", difficultyLevel:3, shortTitle:"Premières inscriptions UNESCO", questionText:"Quels sont ces neuf biens parmi les douze premiers inscrits au patrimoine mondial en 1978 ?", answers:["Îles Galápagos","Ville de Quito","Parc national de Yellowstone","Parc national de Nahanni","L’Anse aux Meadows","Parc national du Simien","Églises creusées dans le roc de Lalibela","Île de Gorée","Centre historique de Cracovie"], sources:[UNESCO], qualificationRule:"Sont attendus les neuf premiers biens dans l’ordre de la liste UNESCO de 1978." }),
  q({ id:"hard-neuf-traditions-theatre-asiatique", subthemeId:"world-culture:traditions", difficultyLevel:3, shortTitle:"Théâtres traditionnels d’Asie", questionText:"À quels pays ou régions associe-t-on le nô, le kabuki, le pansori, l’opéra de Pékin, le wayang, le khon, le kutiyattam, le mak yong et le ca trù ?", answers:["Nô — Japon","Kabuki — Japon","Pansori — Corée","Opéra de Pékin — Chine","Wayang — Indonésie","Khon — Thaïlande","Kutiyattam — Inde","Mak yong — Malaisie","Ca trù — Vietnam"], sources:[UNESCO], qualificationRule:"Le pays, seul ou associé au nom de la tradition, est attendu pour chaque élément." }),
  q({ id:"hard-neuf-jeux-traditionnels", subthemeId:"world-culture:customs", difficultyLevel:3, shortTitle:"Jeux traditionnels", questionText:"À quels pays ou cultures associe-t-on le go, le xiangqi, le shogi, l’awalé, le senet, le hnefatafl, le pato, la pelote basque et le sepak takraw ?", answers:["Go — Chine","Xiangqi — Chine","Shogi — Japon","Awalé — Afrique de l’Ouest","Senet — Égypte antique","Hnefatafl — Scandinavie","Pato — Argentine","Pelote — Pays basque","Sepak takraw — Asie du Sud-Est"], sources:[BRITANNICA], qualificationRule:"La culture ou région, seule ou associée au jeu, est attendue pour chaque élément." }),
  q({ id:"hard-neuf-pelerinages-sites", subthemeId:"world-culture:customs", difficultyLevel:3, shortTitle:"Grands pèlerinages", questionText:"Dans quels pays se situent La Mecque, Saint-Jacques-de-Compostelle, Lourdes, Varanasi, Bodh-Gaya, Lhassa, Kumano, Lalibela et le mont Kailash ?", answers:["La Mecque — Arabie saoudite","Saint-Jacques — Espagne","Lourdes — France","Varanasi — Inde","Bodh-Gaya — Inde","Lhassa — Chine","Kumano — Japon","Lalibela — Éthiopie","Kailash — Chine"], sources:[UNESCO], qualificationRule:"Le pays, seul ou associé au lieu, est attendu pour chaque destination." }),
];
